Core/Src/adc.c File Reference
This file provides code for the configuration of the ADC instances.
#include `adc.h`
#include `uvfr_utils.h`
#include `cmsis_os.h`
Macros
#define DEBUG_TOGGLE_LED() HAL_GPIO_TogglePin(GPIOD, GPIO_PIN_15)
Functions
void MX_ADC1_Init (void)
void MX_ADC2_Init (void)
void HAL_ADC_MspInit (ADC_HandleTypeDef *adcHandle)
void HAL_ADC_MspDeInit (ADC_HandleTypeDef *adcHandle)
void StartADCTask (void *argument)
void processADCBuffer ()
void initADCTask (void)
Variables
volatile uint32_t adc_buf1 [4]
uint16_t adc1_APPS1
uint16_t adc1_APPS2
uint16_t adc1_BPS1
uint16_t adc1_BPS2
ADC_HandleTypeDef hadc1
ADC_HandleTypeDef hadc2
DMA_HandleTypeDef hdma_adc1
Detailed Description
This file provides code for the configuration of the ADC instances.
Attention
Copyright (c) 2023 STMicroelectronics. All rights reserved.
This software is licensed under terms that can be found in the LICENSE file in the root directory of this software component. If no LICENSE file comes with this software, it is provided AS-IS.
Macro Definition Documentation
DEBUG_TOGGLE_LED
#define DEBUG_TOGGLE_LED() HAL_GPIO_TogglePin(GPIOD, GPIO_PIN_15)
Definition at line 305 of file adc.c.
Function Documentation
HAL_ADC_MspDeInit()
void HAL_ADC_MspDeInit (ADC_HandleTypeDef * adcHandle)
ADC1 GPIO Configuration PA1 ------> ADC1_IN1 PA2 ------> ADC1_IN2 PA3 ------> ADC1_IN3 PA4 ------> ADC1_IN4
Uncomment the line below to disable the `ADC_IRQn` interrupt Be aware, disabling shared interrupt may affect other IPs
ADC2 GPIO Configuration PA5 ------> ADC2_IN5 PA6 ------> ADC2_IN6
Uncomment the line below to disable the `ADC_IRQn` interrupt Be aware, disabling shared interrupt may affect other IPs
Definition at line 238 of file adc.c.
HAL_ADC_MspInit()
void HAL_ADC_MspInit (ADC_HandleTypeDef * adcHandle)
ADC1 GPIO Configuration PA1 ------> ADC1_IN1 PA2 ------> ADC1_IN2 PA3 ------> ADC1_IN3 PA4 ------> ADC1_IN4
ADC2 GPIO Configuration PA5 ------> ADC2_IN5 PA6 ------> ADC2_IN6
Definition at line 161 of file adc.c.
References Error_Handler(), and hdma_adc1.
initADCTask()
void initADCTask (void)
Definition at line 358 of file adc.c.
References Error_Handler(), and StartADCTask().
Referenced by uvInit().
MX_ADC1_Init()
void MX_ADC1_Init (void)
Configure the global features of the ADC (Clock, Resolution, Data Alignment and number of conversion)
Configure for the selected ADC regular channel its corresponding rank in the sequencer and its sample time.
Configure for the selected ADC regular channel its corresponding rank in the sequencer and its sample time.
Configure for the selected ADC regular channel its corresponding rank in the sequencer and its sample time.
Configure for the selected ADC regular channel its corresponding rank in the sequencer and its sample time.
Definition at line 40 of file adc.c.
References Error_Handler(), and hadc1.
Referenced by main().
MX_ADC2_Init()
void MX_ADC2_Init (void)
Configure the global features of the ADC (Clock, Resolution, Data Alignment and number of conversion)
Configure for the selected ADC regular channel its corresponding rank in the sequencer and its sample time.
Definition at line 114 of file adc.c.
References Error_Handler(), and hadc2.
Referenced by main().
processADCBuffer()
void processADCBuffer ()
Definition at line 320 of file adc.c.
References adc1_APPS1, adc1_APPS2, adc1_BPS1, adc1_BPS2, and adc_buf1.
Referenced by HAL_ADC_ConvCpltCallback().
StartADCTask()
void StartADCTask (void * argument)
Definition at line 307 of file adc.c.
References adc_buf1, DEBUG_TOGGLE_LED, and hadc1.
Referenced by initADCTask().
Variable Documentation
adc1_APPS1
uint16_t adc1_APPS1
Definition at line 64 of file main.c.
Referenced by processADCBuffer().
adc1_APPS2
uint16_t adc1_APPS2
Definition at line 65 of file main.c.
Referenced by processADCBuffer().
adc1_BPS1
uint16_t adc1_BPS1
Definition at line 66 of file main.c.
Referenced by processADCBuffer().
adc1_BPS2
uint16_t adc1_BPS2
Definition at line 67 of file main.c.
Referenced by processADCBuffer().
adc_buf1
volatile uint32_t adc_buf1[4]
Definition at line 62 of file main.c.
Referenced by processADCBuffer(), and StartADCTask().
hadc1
ADC_HandleTypeDef hadc1
Definition at line 35 of file adc.c.
Referenced by ADC_IRQHandler(), HAL_ADC_LevelOutOfWindowCallback(), MX_ADC1_Init(), and StartADCTask().
hadc2
ADC_HandleTypeDef hadc2
Definition at line 36 of file adc.c.
Referenced by ADC_IRQHandler(), HAL_TIM_PeriodElapsedCallback(), and MX_ADC2_Init().
hdma_adc1
DMA_HandleTypeDef hdma_adc1
Definition at line 37 of file adc.c.
Referenced by DMA2_Stream0_IRQHandler(), and HAL_ADC_MspInit().