Core/Inc/adc.h File Reference
This file contains all the function prototypes for the adc.c file.
#include "main.h"
Macros
#define ADC1_BUF_LEN 40
#define ADC1_CHNL_CNT 4
#define ADC1_SAMPLES 10
#define ADC2_BUF_LEN 2
#define ADC2_CHNL_CNT 2
#define ADC2_SAMPLES 1
#define ADC1_MIN_VOLT 500
#define ADC1_MAX_VOLT 2850
#define ADC2_MIN_VOLT 69
#define ADC2_MAX_VOLT 69
Functions
void MX_ADC1_Init (void)
void MX_ADC2_Init (void)
void MX_ADC3_Init (void)
void initADCTask (void)
void processADCBuffer (uint8_t adc)
Variables
ADC_HandleTypeDef hadc1
ADC_HandleTypeDef hadc2
ADC_HandleTypeDef hadc3
Detailed Description
This file contains all the function prototypes for the adc.c file.
Attention
Copyright (c) 2023 STMicroelectronics. All rights reserved.
This software is licensed under terms that can be found in the LICENSE file in the root directory of this software component. If no LICENSE file comes with this software, it is provided AS-IS.
Definition in file adc.h.
Macro Definition Documentation
ADC1_BUF_LEN
#define ADC1_BUF_LEN 40
Definition at line 45 of file adc.h.
ADC1_CHNL_CNT
#define ADC1_CHNL_CNT 4
Definition at line 46 of file adc.h.
ADC1_MAX_VOLT
#define ADC1_MAX_VOLT 2850
Definition at line 57 of file adc.h.
ADC1_MIN_VOLT
#define ADC1_MIN_VOLT 500
Definition at line 56 of file adc.h.
ADC1_SAMPLES
#define ADC1_SAMPLES 10
Definition at line 47 of file adc.h.
ADC2_BUF_LEN
#define ADC2_BUF_LEN 2
Definition at line 50 of file adc.h.
ADC2_CHNL_CNT
#define ADC2_CHNL_CNT 2
Definition at line 51 of file adc.h.
ADC2_MAX_VOLT
#define ADC2_MAX_VOLT 69
Definition at line 60 of file adc.h.
ADC2_MIN_VOLT
#define ADC2_MIN_VOLT 69
Definition at line 59 of file adc.h.
ADC2_SAMPLES
#define ADC2_SAMPLES 1
Definition at line 52 of file adc.h.
Function Documentation
initADCTask()
void initADCTask (void)
Definition at line 687 of file adc.c.
References Error_Handler(), osPriorityAboveNormal, pdPASS, and StartADCTask().
Referenced by uvInit().
MX_ADC1_Init()
void MX_ADC1_Init (void)
Configure the global features of the ADC (Clock, Resolution, Data Alignment and number of conversion)
Configure for the selected ADC regular channel its corresponding rank in the sequencer and its sample time.
Configure for the selected ADC regular channel its corresponding rank in the sequencer and its sample time.
Configure for the selected ADC regular channel its corresponding rank in the sequencer and its sample time.
Configure for the selected ADC regular channel its corresponding rank in the sequencer and its sample time.
Configure for the selected ADC regular channel its corresponding rank in the sequencer and its sample time.
Configures for the selected ADC injected channel its corresponding rank in the sequencer and its sample time
Configures for the selected ADC injected channel its corresponding rank in the sequencer and its sample time
Configures for the selected ADC injected channel its corresponding rank in the sequencer and its sample time
Configures for the selected ADC injected channel its corresponding rank in the sequencer and its sample time
Definition at line 57 of file adc.c.
References Error_Handler(), and hadc1.
Referenced by main().
MX_ADC2_Init()
void MX_ADC2_Init (void)
Configure the global features of the ADC (Clock, Resolution, Data Alignment and number of conversion)
Configure for the selected ADC regular channel its corresponding rank in the sequencer and its sample time.
Configure for the selected ADC regular channel its corresponding rank in the sequencer and its sample time.
Configure for the selected ADC regular channel its corresponding rank in the sequencer and its sample time.
Configure for the selected ADC regular channel its corresponding rank in the sequencer and its sample time.
Configure for the selected ADC regular channel its corresponding rank in the sequencer and its sample time.
Configure for the selected ADC regular channel its corresponding rank in the sequencer and its sample time.
Configure for the selected ADC regular channel its corresponding rank in the sequencer and its sample time.
Definition at line 181 of file adc.c.
References Error_Handler(), and hadc2.
Referenced by main().
MX_ADC3_Init()
void MX_ADC3_Init (void)
Configure the global features of the ADC (Clock, Resolution, Data Alignment and number of conversion)
Configure for the selected ADC regular channel its corresponding rank in the sequencer and its sample time.
Configure for the selected ADC regular channel its corresponding rank in the sequencer and its sample time.
Configure for the selected ADC regular channel its corresponding rank in the sequencer and its sample time.
Configure for the selected ADC regular channel its corresponding rank in the sequencer and its sample time.
Definition at line 282 of file adc.c.
References Error_Handler(), and hadc3.
Referenced by main().
processADCBuffer()
void processADCBuffer (uint8_t adc)
Definition at line 654 of file adc.c.
References adc1_APPS1, adc1_APPS2, adc1_BPS1, adc1_BPS2, adc1_pack_curr, adc2_CoolantFlow, adc2_CoolantTemp1, adc2_CoolantTemp2, adc2_steering_pos, adc3_damper_FL, adc3_damper_FR, adc3_damper_RL, adc3_damper_RR, adc_buf1, adc_buf2, and adc_buf3.
Referenced by HAL_ADC_ConvCpltCallback().
Variable Documentation
hadc1
ADC_HandleTypeDef hadc1 [extern]
Definition at line 49 of file adc.c.
Referenced by HAL_ADC_ConvCpltCallback(), and HAL_ADC_LevelOutOfWindowCallback().
hadc2
ADC_HandleTypeDef hadc2 [extern]
Definition at line 50 of file adc.c.
Referenced by HAL_ADC_ConvCpltCallback().
hadc3
ADC_HandleTypeDef hadc3 [extern]
Definition at line 51 of file adc.c.
Referenced by HAL_ADC_ConvCpltCallback().