Core/Src/bms.c File Reference
#include "main.h"
#include "bms.h"
#include "constants.h"
#include "pdu.h"
#include "can.h"
#include "tim.h"
#include "dash.h"
#include "uvfr_utils.h"
Macros
#define bms_settings current_vehicle_settings->bms_settings
Functions
void BMS_msg1 (uv_CAN_msg *msg)
void BMS_msg2 (uv_CAN_msg *msg)
void BMS_Init (void *args)
Variables
bms_settings_t default_bms_settings
TickType_t bms_last_msg_time = 0
uint8_t is_bms_connected = 0
uint16_t packCurrent = 0
uint16_t packVoltage = 0
uint16_t stateOfCharge = 0
uint16_t relayState = 0
uint16_t msg1corrupt = 0
uint16_t packDCL = 0
uint16_t lowTemp = 0
uint16_t highTemp = 0
uint16_t msg2corrupt = 0
Macro Definition Documentation
bms_settings
#define bms_settings current_vehicle_settings->bms_settings
Definition at line 12 of file bms.c.
Referenced by BMS_Init().
Function Documentation
BMS_Init()
void BMS_Init (void * args)
Definition at line 100 of file bms.c.
References BMS, BMS_msg1(), BMS_msg2(), bms_settings, CAN_BUS_1, uv_init_task_args::init_info_queue, insertCANMessageHandler(), is_bms_connected, uv_init_task_args::meta_task_handle, osDelay(), pdPASS, UV_OK, vTaskSuspend(), xQueueSendToBack, and xTaskGetTickCount().
Referenced by uvInit().
BMS_msg1()
void BMS_msg1 (uv_CAN_msg * msg)
Definition at line 47 of file bms.c.
References bms_last_msg_time, uv_CAN_msg::data, is_bms_connected, msg1corrupt, packCurrent, packVoltage, relayState, stateOfCharge, and xTaskGetTickCount().
Referenced by BMS_Init().
BMS_msg2()
void BMS_msg2 (uv_CAN_msg * msg)
Definition at line 75 of file bms.c.
References bms_last_msg_time, uv_CAN_msg::data, highTemp, is_bms_connected, lowTemp, msg2corrupt, packDCL, and xTaskGetTickCount().
Referenced by BMS_Init().
Variable Documentation
bms_last_msg_time
TickType_t bms_last_msg_time = 0
Definition at line 31 of file bms.c.
Referenced by BMS_msg1(), and BMS_msg2().
default_bms_settings
bms_settings_t default_bms_settings
Initial value:
= {
.BMS_CAN_timeout = 200,
.max_cell_temp = 500,
.min_cell_temp = -200,
.min_soc = 10,
.min_cell_voltage = 2.5,
.max_cell_voltage = 4.2,
.max_pack_voltage = 5000,
.max_variance_between_cells = 1
}
Definition at line 14 of file bms.c.
Referenced by setupDefaultSettings(), and uvResetFlashToDefault().
highTemp
uint16_t highTemp = 0
Definition at line 42 of file bms.c.
Referenced by BMS_msg2().
is_bms_connected
uint8_t is_bms_connected = 0
Definition at line 32 of file bms.c.
Referenced by BMS_Init(), BMS_msg1(), and BMS_msg2().
lowTemp
uint16_t lowTemp = 0
Definition at line 41 of file bms.c.
Referenced by BMS_msg2().
msg1corrupt
uint16_t msg1corrupt = 0
Definition at line 38 of file bms.c.
Referenced by BMS_msg1().
msg2corrupt
uint16_t msg2corrupt = 0
Definition at line 43 of file bms.c.
Referenced by BMS_msg2().
packCurrent
uint16_t packCurrent = 0
Definition at line 34 of file bms.c.
Referenced by BMS_msg1().
packDCL
uint16_t packDCL = 0
Definition at line 40 of file bms.c.
Referenced by BMS_msg2().
packVoltage
uint16_t packVoltage = 0
Definition at line 35 of file bms.c.
Referenced by BMS_msg1().
relayState
uint16_t relayState = 0
Definition at line 37 of file bms.c.
Referenced by BMS_msg1().
stateOfCharge
uint16_t stateOfCharge = 0
Definition at line 36 of file bms.c.
Referenced by BMS_msg1().