Core/Inc/bms.h File Reference
#include "main.h"
#include "uvfr_utils.h"
Data Structures
struct bms_settings_t
Macros
#define DEFAULT_BMS_CAN_TIMEOUT ((uv_timespan_ms)200)
Typedefs
typedef struct bms_settings_t bms_settings_t
Functions
void BMS_Init (void *args)
Macro Definition Documentation
DEFAULT_BMS_CAN_TIMEOUT
#define DEFAULT_BMS_CAN_TIMEOUT ((uv_timespan_ms)200)
Definition at line 11 of file bms.h.
Typedef Documentation
bms_settings_t
typedef struct bms_settings_t bms_settings_t
Function Documentation
BMS_Init()
void BMS_Init (void * args)
Definition at line 100 of file bms.c.
References BMS, BMS_msg1(), BMS_msg2(), bms_settings, CAN_BUS_1, uv_init_task_args::init_info_queue, insertCANMessageHandler(), is_bms_connected, uv_init_task_args::meta_task_handle, and UV_OK.
Referenced by uvInit().