Core/Src/can.c File Reference
This file provides code for the configuration of the CAN instances.
#include "can.h"
#include "constants.h"
#include "imd.h"
#include "motor_controller.h"
#include "dash.h"
#include "bms.h"
#include "pdu.h"
#include "uvfr_utils.h"
#include "main.h"
#include "stdlib.h"
#include "string.h"
#include "../FreeRTOS/Source/include/task.h"
Data Structures
struct CAN_Callback
Macros
#define HAL_CAN_ERROR_INVALID_CALLBACK (0x00400000U)
#define table_size 128
#define table_size_1 table_size
#define table_size_2 table_size
Typedefs
typedef struct CAN_Callback CAN_Callback
Functions
void handleCANbusError (const CAN_HandleTypeDef *hcan, const uint32_t err_to_ignore)
void MX_CAN1_Init (void)
void MX_CAN2_Init (void)
void HAL_CAN_MspInit (CAN_HandleTypeDef *canHandle)
void HAL_CAN_MspDeInit (CAN_HandleTypeDef *canHandle)
void HAL_CAN_RxFifo0MsgPendingCallback (CAN_HandleTypeDef *hcan)
void HAL_CAN_RxFifo1MsgPendingCallback (CAN_HandleTypeDef *hcan)
unsigned int generateHash (uint32_t Incoming_CAN_id)
static uv_status callFunctionFromCANid (uv_CAN_msg *msg)
void insertCANMessageHandler (uint32_t id, void *handlerfunc, int can_num)
Function to insert an id and function into the lookup table of callback functions.
void nuke_hash_table (int can_num)
uv_status __uvCANtxCritSection (uv_CAN_msg *tx_msg)
uv_status uvSendCanMSG (uv_CAN_msg *tx_msg)
Function to send CAN message.
void CANbusTxSvcDaemon (void *args)
Background task that handles any CAN messages that are being sent.
void CANbusRxSvcDaemon (void *args)
Background task that executes the CAN message callback functions.
Variables
static QueueHandle_t Tx_msg_queue = NULL
static QueueHandle_t Rx_msg_queue = NULL
CAN_Callback CAN_callback_table_1 [table_size_1] = {0}
CAN_Callback CAN_callback_table_2 [table_size_2] = {0}
SemaphoreHandle_t callback_table_1_mutex = NULL
SemaphoreHandle_t callback_table_2_mutex = NULL
uint8_t is_can_ok = 1
CAN_TxHeaderTypeDef TxHeader2
CAN_HandleTypeDef hcan1
CAN_HandleTypeDef hcan2
static uint32_t HAL_RCC_CAN1_CLK_ENABLED =0
Detailed Description
This file provides code for the configuration of the CAN instances.
Attention
Copyright (c) 2023 STMicroelectronics. All rights reserved.
This software is licensed under terms that can be found in the LICENSE file in the root directory of this software component. If no LICENSE file comes with this software, it is provided AS-IS.
Definition in file can.c.
Macro Definition Documentation
HAL_CAN_ERROR_INVALID_CALLBACK
#define HAL_CAN_ERROR_INVALID_CALLBACK (0x00400000U)
Definition at line 44 of file can.c.
Referenced by handleCANbusError().
table_size
#define table_size 128
Definition at line 51 of file can.c.
Referenced by generateHash(), and nuke_hash_table().
table_size_1
#define table_size_1 table_size
Definition at line 52 of file can.c.
table_size_2
#define table_size_2 table_size
Definition at line 53 of file can.c.
Typedef Documentation
CAN_Callback
typedef struct CAN_Callback CAN_Callback
Function Documentation
__uvCANtxCritSection()
uv_status __uvCANtxCritSection (uv_CAN_msg * tx_msg)
Definition at line 826 of file can.c.
References uv_CAN_msg::data, uv_CAN_msg::dlc, uv_CAN_msg::flags, hcan2, is_can_ok, uv_CAN_msg::msg_id, taskENTER_CRITICAL, taskEXIT_CRITICAL, TxHeader, TxMailbox, UV_CAN_EXTENDED_ID, UV_ERROR, and UV_OK.
Referenced by uvSendCanMSG().
callFunctionFromCANid()
static uv_status callFunctionFromCANid (uv_CAN_msg * msg) [inline], [static]
Function to take CAN id and find its corresponding function Given a CAN id, find it in the hash table and call the function if it exists If it doesn't exist, return 1 If it does exist but there are multiple can ids with the same hash follow the next pointer until the right CAN id is found Then call the function
Definition at line 592 of file can.c.
References CAN_BUS_1, CAN_callback_table_1, CAN_callback_table_2, CAN_Callback::CAN_id, uv_CAN_msg::flags, CAN_Callback::function, generateHash(), is_can_ok, uv_CAN_msg::msg_id, CAN_Callback::next, UV_ERROR, UV_OK, and UV_WARNING.
Referenced by CANbusRxSvcDaemon().
CANbusRxSvcDaemon()
void CANbusRxSvcDaemon (void * args)
Background task that executes the CAN message callback functions.
dequeue can message to call function
Definition at line 1045 of file can.c.
References callback_table_1_mutex, callback_table_2_mutex, callFunctionFromCANid(), uv_task_info::cmd_data, killSelf(), pdTRUE, Rx_msg_queue, suspendSelf(), uv_task_info::task_handle, UV_KILL_CMD, UV_OK, UV_SUSPEND_CMD, vQueueDelete(), vTaskDelete(), and xQueueReceive().
Referenced by uvInit().
CANbusTxSvcDaemon()
void CANbusTxSvcDaemon (void * args)
Background task that handles any CAN messages that are being sent.
This task sits idle, until the time is right (it receives a notification from the uvSendCanMSG function) Once this condition has been met, it will actually call the HAL_CAN_AddTxMessage function. This is a very high priority task, meaning that it will pause whatever other code is going in order to run
dequeue can message to put into can bus
Definition at line 920 of file can.c.
References CAN_BUS_1, uv_task_info::cmd_data, uv_CAN_msg::data, uv_CAN_msg::dlc, uv_CAN_msg::flags, hcan1, hcan2, is_can_ok, killSelf(), uv_CAN_msg::msg_id, pdTRUE, suspendSelf(), Tx_msg_queue, TxHeader, TxHeader2, TxMailbox, UV_CAN_EXTENDED_ID, UV_KILL_CMD, UV_SUSPEND_CMD, vQueueDelete(), xQueueReceive(), and xTaskGetTickCount().
Referenced by uvInit().
generateHash()
unsigned int generateHash (uint32_t Incoming_CAN_id)
HASH FUNCTION Take a can id and return a "random" hash id The hash id is in range from 0 to table_size The hash id is similar to an array index in its implementation 11 bits in a hash
Definition at line 577 of file can.c.
References table_size.
Referenced by callFunctionFromCANid(), and insertCANMessageHandler().
HAL_CAN_MspDeInit()
void HAL_CAN_MspDeInit (CAN_HandleTypeDef * canHandle)
CAN1 GPIO Configuration PB8 ------> CAN1_RX PB9 ------> CAN1_TX
CAN2 GPIO Configuration PB12 ------> CAN2_RX PB13 ------> CAN2_TX
Definition at line 391 of file can.c.
References HAL_RCC_CAN1_CLK_ENABLED.
HAL_CAN_MspInit()
void HAL_CAN_MspInit (CAN_HandleTypeDef * canHandle)
CAN1 GPIO Configuration PB8 ------> CAN1_RX PB9 ------> CAN1_TX
CAN2 GPIO Configuration PB12 ------> CAN2_RX PB13 ------> CAN2_TX
Definition at line 312 of file can.c.
References HAL_RCC_CAN1_CLK_ENABLED.
HAL_CAN_RxFifo0MsgPendingCallback()
void HAL_CAN_RxFifo0MsgPendingCallback (CAN_HandleTypeDef * hcan)
Definition at line 456 of file can.c.
References CAN_BUS_1, CAN_BUS_2, uv_CAN_msg::data, uv_CAN_msg::dlc, Error_Handler(), uv_CAN_msg::flags, hcan1, is_can_ok, uv_CAN_msg::msg_id, pdTRUE, Rx_msg_queue, RxHeader, RxHeader2, taskYIELD, UV_CAN_EXTENDED_ID, and xQueueSendFromISR.
HAL_CAN_RxFifo1MsgPendingCallback()
void HAL_CAN_RxFifo1MsgPendingCallback (CAN_HandleTypeDef * hcan)
Definition at line 512 of file can.c.
References CAN_BUS_1, CAN_BUS_2, uv_CAN_msg::data, uv_CAN_msg::dlc, Error_Handler(), uv_CAN_msg::flags, hcan1, is_can_ok, uv_CAN_msg::msg_id, pdTRUE, Rx_msg_queue, RxHeader, RxHeader2, taskYIELD, UV_CAN_EXTENDED_ID, and xQueueSendFromISR.
handleCANbusError()
void handleCANbusError (const CAN_HandleTypeDef * hcan, const uint32_t err_to_ignore)
Definition at line 76 of file can.c.
References HAL_CAN_ERROR_INVALID_CALLBACK, and is_can_ok.
Referenced by main().
MX_CAN1_Init()
void MX_CAN1_Init (void)
Definition at line 156 of file can.c.
References Error_Handler(), hcan1, and TxHeader.
Referenced by main().
MX_CAN2_Init()
void MX_CAN2_Init (void)
Definition at line 232 of file can.c.
References Error_Handler(), hcan2, and TxHeader.
Referenced by main().
nuke_hash_table()
void nuke_hash_table (int can_num)
Function to free all malloced memory Index through the hash table and free all the malloced memory at each index
Definition at line 773 of file can.c.
References CAN_BUS_1, CAN_BUS_2, CAN_callback_table_1, CAN_callback_table_2, CAN_Callback::next, and table_size.
Variable Documentation
callback_table_1_mutex
SemaphoreHandle_t callback_table_1_mutex = NULL
Definition at line 70 of file can.c.
Referenced by CANbusRxSvcDaemon(), and insertCANMessageHandler().
callback_table_2_mutex
SemaphoreHandle_t callback_table_2_mutex = NULL
Definition at line 71 of file can.c.
Referenced by CANbusRxSvcDaemon(), and insertCANMessageHandler().
CAN_callback_table_1
CAN_Callback CAN_callback_table_1[table_size_1] = {0}
Hash Table To Store CAN Messages Creates a hash table of size table_size and type CAN_Message Initialize all CAN messages in the hash table
Definition at line 66 of file can.c.
Referenced by callFunctionFromCANid(), insertCANMessageHandler(), and nuke_hash_table().
CAN_callback_table_2
CAN_Callback CAN_callback_table_2[table_size_2] = {0}
Definition at line 68 of file can.c.
Referenced by callFunctionFromCANid(), insertCANMessageHandler(), and nuke_hash_table().
HAL_RCC_CAN1_CLK_ENABLED
uint32_t HAL_RCC_CAN1_CLK_ENABLED =0 [static]
Definition at line 310 of file can.c.
Referenced by HAL_CAN_MspDeInit(), and HAL_CAN_MspInit().
hcan1
CAN_HandleTypeDef hcan1
Definition at line 152 of file can.c.
Referenced by CAN1_RX0_IRQHandler(), CAN1_RX1_IRQHandler(), CAN1_SCE_IRQHandler(), CAN1_TX_IRQHandler(), CANbusTxSvcDaemon(), HAL_CAN_RxFifo0MsgPendingCallback(), HAL_CAN_RxFifo1MsgPendingCallback(), and MX_CAN1_Init().
hcan2
CAN_HandleTypeDef hcan2
Definition at line 153 of file can.c.
Referenced by __uvCANtxCritSection(), CAN2_RX0_IRQHandler(), CAN2_RX1_IRQHandler(), CAN2_SCE_IRQHandler(), CAN2_TX_IRQHandler(), CANbusTxSvcDaemon(), IMD_Request_Status(), main(), MX_CAN2_Init(), Update_Batt_Temp(), Update_RPM(), and Update_State_Of_Charge().
Rx_msg_queue
QueueHandle_t Rx_msg_queue = NULL [static]
Definition at line 48 of file can.c.
Referenced by CANbusRxSvcDaemon(), HAL_CAN_RxFifo0MsgPendingCallback(), and HAL_CAN_RxFifo1MsgPendingCallback().
Tx_msg_queue
QueueHandle_t Tx_msg_queue = NULL [static]
Definition at line 47 of file can.c.
Referenced by CANbusTxSvcDaemon(), and uvSendCanMSG().
TxHeader2
CAN_TxHeaderTypeDef TxHeader2 [extern]
Definition at line 5 of file constants.c.
Referenced by CANbusTxSvcDaemon().