Core/Inc/can.h File Reference
This file contains all the function prototypes for the can.c file.
#include "main.h"
#include "constants.h"
#include "uvfr_utils.h"
Macros
#define CAN_TX_DAEMON_NAME "CanTxDaemon"
#define CAN_RX_DAEMON_NAME "CanRxDaemon"
Typedefs
typedef struct uv_CAN_msg uv_CAN_msg
Representative of a CAN message.
typedef enum uv_status_t uv_status
This is meant to be a return type from functions that indicates what is actually going on.
Functions
void MX_CAN1_Init (void)
void MX_CAN2_Init (void)
void HAL_CAN_RxFifo0MsgPendingCallback (CAN_HandleTypeDef *hcan2)
void HAL_CAN_RxFifo1MsgPendingCallback (CAN_HandleTypeDef *hcan2)
uv_status uvSendCanMSG (uv_CAN_msg *msg)
Function to send CAN message.
void CANbusTxSvcDaemon (void *args)
Background task that handles any CAN messages that are being sent.
void CANbusRxSvcDaemon (void *args)
Background task that executes the CAN message callback functions.
void insertCANMessageHandler (uint32_t id, void *handlerfunc, int can_num)
Function to insert an id and function into the lookup table of callback functions.
void nuke_hash_table (int can_num)
Variables
CAN_HandleTypeDef hcan1
CAN_HandleTypeDef hcan2
Detailed Description
This file contains all the function prototypes for the can.c file.
Attention
Copyright (c) 2023 STMicroelectronics. All rights reserved.
This software is licensed under terms that can be found in the LICENSE file in the root directory of this software component. If no LICENSE file comes with this software, it is provided AS-IS.
Definition in file can.h.
Macro Definition Documentation
CAN_RX_DAEMON_NAME
#define CAN_RX_DAEMON_NAME "CanRxDaemon"
Definition at line 43 of file can.h.
Referenced by uvInit().
CAN_TX_DAEMON_NAME
#define CAN_TX_DAEMON_NAME "CanTxDaemon"
Definition at line 42 of file can.h.
Referenced by uvInit().
Typedef Documentation
uv_CAN_msg
typedef struct uv_CAN_msg uv_CAN_msg
Representative of a CAN message.
Definition at line 45 of file can.h.
uv_status
typedef enum uv_status_t uv_status
This is meant to be a return type from functions that indicates what is actually going on.
Use this as a return value for functions you want to know the success of. In general, any function you write must return something, as well as account for any possible errors that may have occurred.
Definition at line 46 of file can.h.
Function Documentation
CANbusRxSvcDaemon()
void CANbusRxSvcDaemon (void * args)
Background task that executes the CAN message callback functions.
dequeue can message to call function
Definition at line 1045 of file can.c.
References callback_table_1_mutex, callback_table_2_mutex, uv_task_info::cmd_data, killSelf(), suspendSelf(), uv_task_info::task_handle, UV_KILL_CMD, UV_OK, and UV_SUSPEND_CMD.
Referenced by uvInit().
CANbusTxSvcDaemon()
void CANbusTxSvcDaemon (void * args)
Background task that handles any CAN messages that are being sent.
This task sits idle, until the time is right (it receives a notification from the uvSendCanMSG function) Once this condition has been met, it will actually call the HAL_CAN_AddTxMessage function. This is a very high priority task, meaning that it will pause whatever other code is going in order to run
dequeue can message to put into can bus
Definition at line 920 of file can.c.
References CAN_BUS_1, uv_task_info::cmd_data, uv_CAN_msg::data, uv_CAN_msg::dlc, uv_CAN_msg::flags, hcan1, hcan2, is_can_ok, killSelf(), uv_CAN_msg::msg_id, suspendSelf(), TxHeader, TxHeader2, TxMailbox, UV_CAN_EXTENDED_ID, UV_KILL_CMD, and UV_SUSPEND_CMD.
Referenced by uvInit().
HAL_CAN_RxFifo0MsgPendingCallback()
void HAL_CAN_RxFifo0MsgPendingCallback (CAN_HandleTypeDef * hcan2)
Definition at line 456 of file can.c.
References CAN_BUS_1, CAN_BUS_2, uv_CAN_msg::data, uv_CAN_msg::dlc, Error_Handler(), uv_CAN_msg::flags, hcan1, is_can_ok, uv_CAN_msg::msg_id, RxHeader, RxHeader2, and UV_CAN_EXTENDED_ID.
HAL_CAN_RxFifo1MsgPendingCallback()
void HAL_CAN_RxFifo1MsgPendingCallback (CAN_HandleTypeDef * hcan2)
Definition at line 512 of file can.c.
References CAN_BUS_1, CAN_BUS_2, uv_CAN_msg::data, uv_CAN_msg::dlc, Error_Handler(), uv_CAN_msg::flags, hcan1, is_can_ok, uv_CAN_msg::msg_id, RxHeader, RxHeader2, and UV_CAN_EXTENDED_ID.
MX_CAN1_Init()
void MX_CAN1_Init (void)
Definition at line 156 of file can.c.
References Error_Handler(), hcan1, and TxHeader.
Referenced by main().
MX_CAN2_Init()
void MX_CAN2_Init (void)
Definition at line 232 of file can.c.
References Error_Handler(), hcan2, and TxHeader.
Referenced by main().
nuke_hash_table()
void nuke_hash_table (int can_num)
Function to free all malloced memory Index through the hash table and free all the malloced memory at each index
Definition at line 773 of file can.c.
References CAN_BUS_1, CAN_BUS_2, CAN_callback_table_1, CAN_callback_table_2, CAN_Callback::next, and table_size.
Variable Documentation
hcan1
CAN_HandleTypeDef hcan1 [extern]
Definition at line 152 of file can.c.
hcan2
CAN_HandleTypeDef hcan2 [extern]
Definition at line 153 of file can.c.
Referenced by IMD_Request_Status(), main(), Update_Batt_Temp(), Update_RPM(), and Update_State_Of_Charge().