Core/FreeRTOS/Source/CMSIS_RTOS/cmsis_os.c File Reference
#include "cmsis_os.h"
#include <string.h>
Data Structures
struct os_pool_cb
struct os_mailQ_cb
Typedefs
typedef struct os_pool_cb os_pool_cb_t
typedef struct os_mailQ_cb os_mailQ_cb_t
Functions
void xPortSysTickHandler (void)
static unsigned portBASE_TYPE makeFreeRtosPriority (osPriority priority)
static osPriority makeCmsisPriority (unsigned portBASE_TYPE fpriority)
static int inHandlerMode (void)
osStatus osKernelInitialize (void)
Initialize the RTOS Kernel for creating objects.
osStatus osKernelStart (void)
Start the RTOS Kernel with executing the specified thread.
int32_t osKernelRunning (void)
Check if the RTOS kernel is already started.
uint32_t osKernelSysTick (void)
Get the value of the Kernel SysTick timer.
osThreadId osThreadCreate (const osThreadDef_t *thread_def, void *argument)
Create a thread and add it to Active Threads and set it to state READY.
osThreadId osThreadGetId (void)
Return the thread ID of the current running thread.
osStatus osThreadTerminate (osThreadId thread_id)
Terminate execution of a thread and remove it from Active Threads.
osStatus osThreadYield (void)
Pass control to next thread that is in state READY.
osStatus osThreadSetPriority (osThreadId thread_id, osPriority priority)
Change priority of an active thread.
osPriority osThreadGetPriority (osThreadId thread_id)
Get current priority of an active thread.
osStatus osDelay (uint32_t millisec)
Wait for Timeout (Time Delay)
osTimerId osTimerCreate (const osTimerDef_t *timer_def, os_timer_type type, void *argument)
Create a timer.
osStatus osTimerStart (osTimerId timer_id, uint32_t millisec)
Start or restart a timer.
osStatus osTimerStop (osTimerId timer_id)
Stop a timer.
osStatus osTimerDelete (osTimerId timer_id)
Delete a timer.
int32_t osSignalSet (osThreadId thread_id, int32_t signal)
Set the specified Signal Flags of an active thread.
int32_t osSignalClear (osThreadId thread_id, int32_t signal)
Clear the specified Signal Flags of an active thread.
osEvent osSignalWait (int32_t signals, uint32_t millisec)
Wait for one or more Signal Flags to become signaled for the current RUNNING thread.
osMutexId osMutexCreate (const osMutexDef_t *mutex_def)
Create and Initialize a Mutex object.
osStatus osMutexWait (osMutexId mutex_id, uint32_t millisec)
Wait until a Mutex becomes available.
osStatus osMutexRelease (osMutexId mutex_id)
Release a Mutex that was obtained by osMutexWait.
osStatus osMutexDelete (osMutexId mutex_id)
Delete a Mutex.
osSemaphoreId osSemaphoreCreate (const osSemaphoreDef_t *semaphore_def, int32_t count)
Create and Initialize a Semaphore object used for managing resources.
int32_t osSemaphoreWait (osSemaphoreId semaphore_id, uint32_t millisec)
Wait until a Semaphore token becomes available.
osStatus osSemaphoreRelease (osSemaphoreId semaphore_id)
Release a Semaphore token.
osStatus osSemaphoreDelete (osSemaphoreId semaphore_id)
Delete a Semaphore.
osPoolId osPoolCreate (const osPoolDef_t *pool_def)
Create and Initialize a memory pool.
void * osPoolAlloc (osPoolId pool_id)
Allocate a memory block from a memory pool.
void * osPoolCAlloc (osPoolId pool_id)
Allocate a memory block from a memory pool and set memory block to zero.
osStatus osPoolFree (osPoolId pool_id, void *block)
Return an allocated memory block back to a specific memory pool.
osMessageQId osMessageCreate (const osMessageQDef_t *queue_def, osThreadId thread_id)
Create and Initialize a Message Queue.
osStatus osMessagePut (osMessageQId queue_id, uint32_t info, uint32_t millisec)
Put a Message to a Queue.
osEvent osMessageGet (osMessageQId queue_id, uint32_t millisec)
Get a Message or Wait for a Message from a Queue.
osMailQId osMailCreate (const osMailQDef_t *queue_def, osThreadId thread_id)
Create and Initialize mail queue.
void * osMailAlloc (osMailQId queue_id, uint32_t millisec)
Allocate a memory block from a mail.
void * osMailCAlloc (osMailQId queue_id, uint32_t millisec)
Allocate a memory block from a mail and set memory block to zero.
osStatus osMailPut (osMailQId queue_id, void *mail)
Put a mail to a queue.
osEvent osMailGet (osMailQId queue_id, uint32_t millisec)
Get a mail from a queue.
osStatus osMailFree (osMailQId queue_id, void *mail)
Free a memory block from a mail.
void osSystickHandler (void)
Handles the tick increment.
osThreadState osThreadGetState (osThreadId thread_id)
Obtain the state of any thread.
osStatus osThreadIsSuspended (osThreadId thread_id)
Check if a thread is already suspended or not.
osStatus osThreadSuspend (osThreadId thread_id)
Suspend execution of a thread.
osStatus osThreadResume (osThreadId thread_id)
Resume execution of a suspended thread.
osStatus osThreadSuspendAll (void)
Suspend execution of a all active threads.
osStatus osThreadResumeAll (void)
Resume execution of a all suspended threads.
osStatus osDelayUntil (uint32_t *PreviousWakeTime, uint32_t millisec)
Delay a task until a specified time.
osStatus osAbortDelay (osThreadId thread_id)
Abort the delay for a specific thread.
osStatus osThreadList (uint8_t *buffer)
Lists all the current threads, along with their current state and stack usage high water mark.
osEvent osMessagePeek (osMessageQId queue_id, uint32_t millisec)
Receive an item from a queue without removing the item from the queue.
uint32_t osMessageWaiting (osMessageQId queue_id)
Get the number of messaged stored in a queue.
uint32_t osMessageAvailableSpace (osMessageQId queue_id)
Get the available space in a message queue.
osStatus osMessageDelete (osMessageQId queue_id)
Delete a Message Queue.
osMutexId osRecursiveMutexCreate (const osMutexDef_t *mutex_def)
Create and Initialize a Recursive Mutex.
osStatus osRecursiveMutexRelease (osMutexId mutex_id)
Release a Recursive Mutex.
osStatus osRecursiveMutexWait (osMutexId mutex_id, uint32_t millisec)
Release a Recursive Mutex.
uint32_t osSemaphoreGetCount (osSemaphoreId semaphore_id)
Returns the current count value of a counting semaphore.
Typedef Documentation
os_mailQ_cb_t
typedef struct os_mailQ_cb os_mailQ_cb_t
os_pool_cb_t
typedef struct os_pool_cb os_pool_cb_t
Function Documentation
inHandlerMode()
static int inHandlerMode (void) [static]
Definition at line 131 of file cmsis_os.c.
Referenced by osKernelSysTick(), osMailGet(), osMailPut(), osMessageDelete(), osMessageGet(), osMessagePut(), osMessageWaiting(), osMutexDelete(), osMutexRelease(), osMutexWait(), osPoolAlloc(), osSemaphoreDelete(), osSemaphoreRelease(), osSemaphoreWait(), osSignalSet(), osSignalWait(), osThreadGetPriority(), osThreadResume(), osTimerDelete(), osTimerStart(), and osTimerStop().
makeCmsisPriority()
static osPriority makeCmsisPriority (unsigned portBASE_TYPE fpriority) [static]
Definition at line 117 of file cmsis_os.c.
References osPriorityError, osPriorityIdle, osPriorityRealtime, and tskIDLE_PRIORITY.
Referenced by osThreadGetPriority().
makeFreeRtosPriority()
static unsigned portBASE_TYPE makeFreeRtosPriority (osPriority priority) [static]
Definition at line 104 of file cmsis_os.c.
References osPriorityError, osPriorityIdle, portBASE_TYPE, and tskIDLE_PRIORITY.
Referenced by osThreadCreate(), and osThreadSetPriority().
osAbortDelay()
osStatus osAbortDelay (osThreadId thread_id)
Abort the delay for a specific thread.
Parameters
thread_id thread ID obtained by osThreadCreate or osThreadGetId
Return values
status code that indicates the execution status of the function.
Definition at line 1521 of file cmsis_os.c.
References osErrorResource, osOK, and xTaskAbortDelay().
osDelay()
osStatus osDelay (uint32_t millisec)
Wait for Timeout (Time Delay)
Parameters
millisec time delay value
Return values
status code that indicates the execution status of the function.
Definition at line 323 of file cmsis_os.c.
References osErrorResource, osOK, portTICK_PERIOD_MS, and vTaskDelay().
Referenced by BMS_Init(), and flushLogsToCAN().
osDelayUntil()
osStatus osDelayUntil (uint32_t * PreviousWakeTime, uint32_t millisec)
Delay a task until a specified time.
Parameters
PreviousWakeTime Pointer to a variable that holds the time at which the task was last unblocked. PreviousWakeTime must be initialised with the current time prior to its first use (PreviousWakeTime = osKernelSysTick())
millisec time delay value
Return values
status code that indicates the execution status of the function.
Definition at line 1501 of file cmsis_os.c.
References osErrorResource, osOK, portTICK_PERIOD_MS, and vTaskDelayUntil().
osKernelInitialize()
osStatus osKernelInitialize (void)
Initialize the RTOS Kernel for creating objects.
Return values
status code that indicates the execution status of the function.
Note
MUST REMAIN UNCHANGED: osKernelInitialize shall be consistent in every CMSIS-RTOS.
osKernelRunning()
int32_t osKernelRunning (void)
Check if the RTOS kernel is already started.
Parameters
None
Return values
(0) RTOS is not started (1) RTOS is started (-1) if this feature is disabled in FreeRTOSConfig.h
Note
MUST REMAIN UNCHANGED: osKernelRunning shall be consistent in every CMSIS-RTOS.
Definition at line 166 of file cmsis_os.c.
References taskSCHEDULER_NOT_STARTED, and xTaskGetSchedulerState().
osKernelStart()
osStatus osKernelStart (void)
Start the RTOS Kernel with executing the specified thread.
Parameters
thread_def thread definition referenced with osThread.
argument pointer that is passed to the thread function as start argument.
Return values
status code that indicates the execution status of the function
Note
MUST REMAIN UNCHANGED: osKernelStart shall be consistent in every CMSIS-RTOS.
Definition at line 151 of file cmsis_os.c.
References osOK, and vTaskStartScheduler().
osKernelSysTick()
uint32_t osKernelSysTick (void)
Get the value of the Kernel SysTick timer.
Parameters
None
Return values
None
Note
MUST REMAIN UNCHANGED: osKernelSysTick shall be consistent in every CMSIS-RTOS.
Definition at line 185 of file cmsis_os.c.
References inHandlerMode(), xTaskGetTickCount(), and xTaskGetTickCountFromISR().
osMailAlloc()
void * osMailAlloc (osMailQId queue_id, uint32_t millisec)
Allocate a memory block from a mail.
Parameters
queue_id mail queue ID obtained with osMailCreate.
millisec timeout value or 0 in case of no time-out.
Return values
pointer to memory block that can be filled with mail or NULL in case error.
Note
MUST REMAIN UNCHANGED: osMailAlloc shall be consistent in every CMSIS-RTOS.
Definition at line 1215 of file cmsis_os.c.
References osPoolAlloc(), and os_mailQ_cb::pool.
Referenced by osMailCAlloc().
osMailCAlloc()
void * osMailCAlloc (osMailQId queue_id, uint32_t millisec)
Allocate a memory block from a mail and set memory block to zero.
Parameters
queue_id mail queue ID obtained with osMailCreate.
millisec timeout value or 0 in case of no time-out.
Return values
pointer to memory block that can be filled with mail or NULL in case error.
Note
MUST REMAIN UNCHANGED: osMailCAlloc shall be consistent in every CMSIS-RTOS.
Definition at line 1237 of file cmsis_os.c.
References os_mailQ_def::item_sz, osMailAlloc(), and os_mailQ_cb::queue_def.
osMailCreate()
osMailQId osMailCreate (const osMailQDef_t * queue_def, osThreadId thread_id)
Create and Initialize mail queue.
Parameters
queue_def reference to the mail queue definition obtain with osMailQ
thread_id thread ID (obtained by osThreadCreate or osThreadGetId) or NULL.
Return values
mail queue ID for reference by other functions or NULL in case of error.
Note
MUST REMAIN UNCHANGED: osMailCreate shall be consistent in every CMSIS-RTOS.
Definition at line 1169 of file cmsis_os.c.
References os_mailQ_def::cb, os_mailQ_def::item_sz, osPoolCreate(), pvPortMalloc(), os_mailQ_def::queue_sz, and vPortFree().
osMailFree()
osStatus osMailFree (osMailQId queue_id, void * mail)
Free a memory block from a mail.
Parameters
queue_id mail queue ID obtained with osMailCreate.
mail pointer to the memory block that was obtained with osMailGet.
Return values
status code that indicates the execution status of the function.
Note
MUST REMAIN UNCHANGED: osMailFree shall be consistent in every CMSIS-RTOS.
Definition at line 1347 of file cmsis_os.c.
References osErrorParameter, osPoolFree(), and os_mailQ_cb::pool.
osMailGet()
osEvent osMailGet (osMailQId queue_id, uint32_t millisec)
Get a mail from a queue.
Parameters
queue_id mail queue ID obtained with osMailCreate.
millisec timeout value or 0 in case of no time-out
Return values
event that contains mail information or error code.
Note
MUST REMAIN UNCHANGED: osMailGet shall be consistent in every CMSIS-RTOS.
Definition at line 1291 of file cmsis_os.c.
References osEvent::def, os_mailQ_cb::handle, inHandlerMode(), osEvent::mail_id, osErrorParameter, osEventMail, osEventTimeout, osOK, osWaitForever, osEvent::p, pdFALSE, pdTRUE, portBASE_TYPE, portEND_SWITCHING_ISR, portMAX_DELAY, portTICK_PERIOD_MS, osEvent::value, xQueueReceive(), and xQueueReceiveFromISR().
osMailPut()
osStatus osMailPut (osMailQId queue_id, void * mail)
Put a mail to a queue.
Parameters
queue_id mail queue ID obtained with osMailCreate.
mail memory block previously allocated with osMailAlloc or osMailCAlloc.
Return values
status code that indicates the execution status of the function.
Note
MUST REMAIN UNCHANGED: osMailPut shall be consistent in every CMSIS-RTOS.
Definition at line 1258 of file cmsis_os.c.
References os_mailQ_cb::handle, inHandlerMode(), osErrorOS, osErrorParameter, osOK, pdFALSE, pdTRUE, portBASE_TYPE, portEND_SWITCHING_ISR, xQueueSend, and xQueueSendFromISR.
osMessageAvailableSpace()
uint32_t osMessageAvailableSpace (osMessageQId queue_id)
Get the available space in a message queue.
Parameters
queue_id message queue ID obtained with osMessageCreate.
Return values
available space in a message queue.
Definition at line 1613 of file cmsis_os.c.
References uxQueueSpacesAvailable().
osMessageCreate()
osMessageQId osMessageCreate (const osMessageQDef_t * queue_def, osThreadId thread_id)
Create and Initialize a Message Queue.
Parameters
queue_def queue definition referenced with osMessageQ.
thread_id thread ID (obtained by osThreadCreate or osThreadGetId) or NULL.
Return values
message queue ID for reference by other functions or NULL in case of error.
Note
MUST REMAIN UNCHANGED: osMessageCreate shall be consistent in every CMSIS-RTOS.
Definition at line 1041 of file cmsis_os.c.
References os_messageQ_def::item_sz, and os_messageQ_def::queue_sz.
osMessageDelete()
osStatus osMessageDelete (osMessageQId queue_id)
Delete a Message Queue.
Parameters
queue_id message queue ID obtained with osMessageCreate.
Return values
status code that indicates the execution status of the function.
Definition at line 1623 of file cmsis_os.c.
References inHandlerMode(), osErrorISR, osOK, and vQueueDelete().
osMessageGet()
osEvent osMessageGet (osMessageQId queue_id, uint32_t millisec)
Get a Message or Wait for a Message from a Queue.
Parameters
queue_id message queue ID obtained with osMessageCreate.
millisec timeout value or 0 in case of no time-out.
Return values
event information that includes status code.
Note
MUST REMAIN UNCHANGED: osMessageGet shall be consistent in every CMSIS-RTOS.
Definition at line 1100 of file cmsis_os.c.
References osEvent::def, inHandlerMode(), osEvent::message_id, osErrorParameter, osEventMessage, osEventTimeout, osOK, osWaitForever, pdFALSE, pdTRUE, portBASE_TYPE, portEND_SWITCHING_ISR, portMAX_DELAY, portTICK_PERIOD_MS, osEvent::v, osEvent::value, xQueueReceive(), and xQueueReceiveFromISR().
osMessagePeek()
osEvent osMessagePeek (osMessageQId queue_id, uint32_t millisec)
Receive an item from a queue without removing the item from the queue.
Parameters
queue_id message queue ID obtained with osMessageCreate.
millisec timeout value or 0 in case of no time-out.
Return values
event information that includes status code.
Definition at line 1556 of file cmsis_os.c.
References osEvent::def, osEvent::message_id, osErrorParameter, osEventMessage, osEventTimeout, osOK, osWaitForever, pdTRUE, portMAX_DELAY, portTICK_PERIOD_MS, osEvent::v, osEvent::value, and xQueuePeek().
osMessagePut()
osStatus osMessagePut (osMessageQId queue_id, uint32_t info, uint32_t millisec)
Put a Message to a Queue.
Parameters
queue_id message queue ID obtained with osMessageCreate.
info message information.
millisec timeout value or 0 in case of no time-out.
Return values
status code that indicates the execution status of the function.
Note
MUST REMAIN UNCHANGED: osMessagePut shall be consistent in every CMSIS-RTOS.
Definition at line 1068 of file cmsis_os.c.
References inHandlerMode(), osErrorOS, osOK, pdFALSE, pdTRUE, portBASE_TYPE, portEND_SWITCHING_ISR, portTICK_PERIOD_MS, xQueueSend, and xQueueSendFromISR.
osMessageWaiting()
uint32_t osMessageWaiting (osMessageQId queue_id)
Get the number of messaged stored in a queue.
Parameters
queue_id message queue ID obtained with osMessageCreate.
Return values
number of messages stored in a queue.
Definition at line 1597 of file cmsis_os.c.
References inHandlerMode(), uxQueueMessagesWaiting(), and uxQueueMessagesWaitingFromISR().
osMutexCreate()
osMutexId osMutexCreate (const osMutexDef_t * mutex_def)
Create and Initialize a Mutex object.
Parameters
mutex_def mutex definition referenced with osMutex.
Return values
mutex ID for reference by other functions or NULL in case of error.
Note
MUST REMAIN UNCHANGED: osMutexCreate shall be consistent in every CMSIS-RTOS.
Definition at line 598 of file cmsis_os.c.
osMutexDelete()
osStatus osMutexDelete (osMutexId mutex_id)
Delete a Mutex.
Parameters
mutex_id mutex ID obtained by osMutexCreate.
Return values
status code that indicates the execution status of the function.
Note
MUST REMAIN UNCHANGED: osMutexDelete shall be consistent in every CMSIS-RTOS.
Definition at line 691 of file cmsis_os.c.
References inHandlerMode(), osErrorISR, osOK, and vQueueDelete().
osMutexRelease()
osStatus osMutexRelease (osMutexId mutex_id)
Release a Mutex that was obtained by osMutexWait.
Parameters
mutex_id mutex ID obtained by osMutexCreate.
Return values
status code that indicates the execution status of the function.
Note
MUST REMAIN UNCHANGED: osMutexRelease shall be consistent in every CMSIS-RTOS.
Definition at line 667 of file cmsis_os.c.
References inHandlerMode(), osErrorOS, osOK, pdFALSE, pdTRUE, portBASE_TYPE, portEND_SWITCHING_ISR, xSemaphoreGive, and xSemaphoreGiveFromISR.
osMutexWait()
osStatus osMutexWait (osMutexId mutex_id, uint32_t millisec)
Wait until a Mutex becomes available.
Parameters
mutex_id mutex ID obtained by osMutexCreate.
millisec timeout value or 0 in case of no time-out.
Return values
status code that indicates the execution status of the function.
Note
MUST REMAIN UNCHANGED: osMutexWait shall be consistent in every CMSIS-RTOS.
Definition at line 627 of file cmsis_os.c.
References inHandlerMode(), osErrorOS, osErrorParameter, osOK, osWaitForever, pdFALSE, pdTRUE, portBASE_TYPE, portEND_SWITCHING_ISR, portMAX_DELAY, portTICK_PERIOD_MS, xSemaphoreTake, and xSemaphoreTakeFromISR.
osPoolAlloc()
void * osPoolAlloc (osPoolId pool_id)
Allocate a memory block from a memory pool.
Parameters
pool_id memory pool ID obtain referenced with osPoolCreate.
Return values
address of the allocated memory block or NULL in case of no memory available.
Note
MUST REMAIN UNCHANGED: osPoolAlloc shall be consistent in every CMSIS-RTOS.
Definition at line 937 of file cmsis_os.c.
References os_pool_cb::currentIndex, inHandlerMode(), os_pool_cb::item_sz, os_pool_cb::markers, os_pool_cb::pool, os_pool_cb::pool_sz, portCLEAR_INTERRUPT_MASK_FROM_ISR, portSET_INTERRUPT_MASK_FROM_ISR, vPortEnterCritical(), and vPortExitCritical().
Referenced by osMailAlloc(), and osPoolCAlloc().
osPoolCAlloc()
void * osPoolCAlloc (osPoolId pool_id)
Allocate a memory block from a memory pool and set memory block to zero.
Parameters
pool_id memory pool ID obtain referenced with osPoolCreate.
Return values
address of the allocated memory block or NULL in case of no memory available.
Note
MUST REMAIN UNCHANGED: osPoolCAlloc shall be consistent in every CMSIS-RTOS.
Definition at line 978 of file cmsis_os.c.
References osPoolAlloc(), and os_pool_cb::pool_sz.
osPoolCreate()
osPoolId osPoolCreate (const osPoolDef_t * pool_def)
Create and Initialize a memory pool.
Parameters
pool_def memory pool definition referenced with osPool.
Return values
memory pool ID for reference by other functions or NULL in case of error.
Note
MUST REMAIN UNCHANGED: osPoolCreate shall be consistent in every CMSIS-RTOS.
Definition at line 884 of file cmsis_os.c.
References os_pool_cb::currentIndex, os_pool_cb::item_sz, os_pool_def::item_sz, os_pool_cb::markers, os_pool_cb::pool, os_pool_cb::pool_sz, os_pool_def::pool_sz, pvPortMalloc(), and vPortFree().
Referenced by osMailCreate().
osPoolFree()
osStatus osPoolFree (osPoolId pool_id, void * block)
Return an allocated memory block back to a specific memory pool.
Parameters
pool_id memory pool ID obtain referenced with osPoolCreate.
block address of the allocated memory block that is returned to the memory pool.
Return values
status code that indicates the execution status of the function.
Note
MUST REMAIN UNCHANGED: osPoolFree shall be consistent in every CMSIS-RTOS.
Definition at line 997 of file cmsis_os.c.
References os_pool_cb::item_sz, os_pool_cb::markers, osErrorParameter, osOK, os_pool_cb::pool, and os_pool_cb::pool_sz.
Referenced by osMailFree().
osRecursiveMutexCreate()
osMutexId osRecursiveMutexCreate (const osMutexDef_t * mutex_def)
Create and Initialize a Recursive Mutex.
Parameters
mutex_def mutex definition referenced with osMutex.
Return values
mutex ID for reference by other functions or NULL in case of error..
Definition at line 1639 of file cmsis_os.c.
osRecursiveMutexRelease()
osStatus osRecursiveMutexRelease (osMutexId mutex_id)
Release a Recursive Mutex.
Parameters
mutex_id mutex ID obtained by osRecursiveMutexCreate.
Return values
status code that indicates the execution status of the function.
Definition at line 1665 of file cmsis_os.c.
References osErrorOS, osErrorResource, osOK, and pdTRUE.
osRecursiveMutexWait()
osStatus osRecursiveMutexWait (osMutexId mutex_id, uint32_t millisec)
Release a Recursive Mutex.
Parameters
mutex_id mutex ID obtained by osRecursiveMutexCreate.
millisec timeout value or 0 in case of no time-out.
Return values
status code that indicates the execution status of the function.
Definition at line 1686 of file cmsis_os.c.
References osErrorOS, osErrorParameter, osErrorResource, osOK, osWaitForever, pdTRUE, portMAX_DELAY, and portTICK_PERIOD_MS.
osSemaphoreCreate()
osSemaphoreId osSemaphoreCreate (const osSemaphoreDef_t * semaphore_def, int32_t count)
Create and Initialize a Semaphore object used for managing resources.
Parameters
semaphore_def semaphore definition referenced with osSemaphore.
count number of available resources.
Return values
semaphore ID for reference by other functions or NULL in case of error.
Note
MUST REMAIN UNCHANGED: osSemaphoreCreate shall be consistent in every CMSIS-RTOS.
Definition at line 713 of file cmsis_os.c.
osSemaphoreDelete()
osStatus osSemaphoreDelete (osSemaphoreId semaphore_id)
Delete a Semaphore.
Parameters
semaphore_id semaphore object referenced with osSemaphore.
Return values
status code that indicates the execution status of the function.
Note
MUST REMAIN UNCHANGED: osSemaphoreDelete shall be consistent in every CMSIS-RTOS.
Definition at line 847 of file cmsis_os.c.
References inHandlerMode(), osErrorISR, osOK, and vSemaphoreDelete.
osSemaphoreGetCount()
uint32_t osSemaphoreGetCount (osSemaphoreId semaphore_id)
Returns the current count value of a counting semaphore.
Parameters
semaphore_id semaphore_id ID obtained by osSemaphoreCreate.
Return values
count value
Definition at line 1725 of file cmsis_os.c.
References uxSemaphoreGetCount.
osSemaphoreRelease()
osStatus osSemaphoreRelease (osSemaphoreId semaphore_id)
Release a Semaphore token.
Parameters
semaphore_id semaphore object referenced with osSemaphore.
Return values
status code that indicates the execution status of the function.
Note
MUST REMAIN UNCHANGED: osSemaphoreRelease shall be consistent in every CMSIS-RTOS.
Definition at line 820 of file cmsis_os.c.
References inHandlerMode(), osErrorOS, osOK, pdFALSE, pdTRUE, portBASE_TYPE, portEND_SWITCHING_ISR, xSemaphoreGive, and xSemaphoreGiveFromISR.
osSemaphoreWait()
int32_t osSemaphoreWait (osSemaphoreId semaphore_id, uint32_t millisec)
Wait until a Semaphore token becomes available.
Parameters
semaphore_id semaphore object referenced with osSemaphore.
millisec timeout value or 0 in case of no time-out.
Return values
number of available tokens, or -1 in case of incorrect parameters.
Note
MUST REMAIN UNCHANGED: osSemaphoreWait shall be consistent in every CMSIS-RTOS.
Definition at line 780 of file cmsis_os.c.
References inHandlerMode(), osErrorOS, osErrorParameter, osOK, osWaitForever, pdFALSE, pdTRUE, portBASE_TYPE, portEND_SWITCHING_ISR, portMAX_DELAY, portTICK_PERIOD_MS, xSemaphoreTake, and xSemaphoreTakeFromISR.
osSignalClear()
int32_t osSignalClear (osThreadId thread_id, int32_t signal)
Clear the specified Signal Flags of an active thread.
Parameters
thread_id thread ID obtained by osThreadCreate or osThreadGetId.
signals specifies the signal flags of the thread that shall be cleared.
Return values
previous signal flags of the specified thread or 0x80000000 in case of incorrect parameters.
Note
MUST REMAIN UNCHANGED: osSignalClear shall be consistent in every CMSIS-RTOS.
osSignalSet()
int32_t osSignalSet (osThreadId thread_id, int32_t signal)
Set the specified Signal Flags of an active thread.
Parameters
thread_id thread ID obtained by osThreadCreate or osThreadGetId.
signals specifies the signal flags of the thread that should be set.
Return values
previous signal flags of the specified thread or 0x80000000 in case of incorrect parameters.
Note
MUST REMAIN UNCHANGED: osSignalSet shall be consistent in every CMSIS-RTOS.
Definition at line 503 of file cmsis_os.c.
References eSetBits, inHandlerMode(), pdFALSE, pdPASS, portYIELD_FROM_ISR, xTaskGenericNotify(), and xTaskGenericNotifyFromISR().
osSignalWait()
osEvent osSignalWait (int32_t signals, uint32_t millisec)
Wait for one or more Signal Flags to become signaled for the current RUNNING thread.
Parameters
signals wait until all specified signal flags set or 0 for any single signal flag.
millisec timeout value or 0 in case of no time-out.
Return values
event flag information or error code.
Note
MUST REMAIN UNCHANGED: osSignalWait shall be consistent in every CMSIS-RTOS.
Definition at line 544 of file cmsis_os.c.
References inHandlerMode(), osErrorISR, osErrorOS, osErrorValue, osEventSignal, osEventTimeout, osOK, osWaitForever, pdTRUE, portMAX_DELAY, portTICK_PERIOD_MS, osEvent::signals, osEvent::status, osEvent::value, and xTaskNotifyWait().
osSystickHandler()
void osSystickHandler (void)
Handles the tick increment.
Parameters
none.
Return values
none.
Definition at line 1363 of file cmsis_os.c.
References taskSCHEDULER_NOT_STARTED, xPortSysTickHandler(), and xTaskGetSchedulerState().
osThreadCreate()
osThreadId osThreadCreate (const osThreadDef_t * thread_def, void * argument)
Create a thread and add it to Active Threads and set it to state READY.
Parameters
thread_def thread definition referenced with osThread.
argument pointer that is passed to the thread function as start argument.
Return values
thread ID for reference by other functions or NULL in case of error.
Note
MUST REMAIN UNCHANGED: osThreadCreate shall be consistent in every CMSIS-RTOS.
Definition at line 203 of file cmsis_os.c.
References makeFreeRtosPriority(), os_thread_def::name, pdPASS, portCHAR, os_thread_def::pthread, os_thread_def::stacksize, and os_thread_def::tpriority.
osThreadGetId()
osThreadId osThreadGetId (void)
Return the thread ID of the current running thread.
Return values
thread ID for reference by other functions or NULL in case of error.
Note
MUST REMAIN UNCHANGED: osThreadGetId shall be consistent in every CMSIS-RTOS.
Definition at line 241 of file cmsis_os.c.
References xTaskGetCurrentTaskHandle().
osThreadGetPriority()
osPriority osThreadGetPriority (osThreadId thread_id)
Get current priority of an active thread.
Parameters
thread_id thread ID obtained by osThreadCreate or osThreadGetId.
Return values
current priority value of the thread function.
Note
MUST REMAIN UNCHANGED: osThreadGetPriority shall be consistent in every CMSIS-RTOS.
Definition at line 301 of file cmsis_os.c.
References inHandlerMode(), makeCmsisPriority(), osPriorityError, uxTaskPriorityGet(), and uxTaskPriorityGetFromISR().
osThreadGetState()
osThreadState osThreadGetState (osThreadId thread_id)
Obtain the state of any thread.
Parameters
thread_id thread ID obtained by osThreadCreate or osThreadGetId.
Return values
the stae of the thread, states are encoded by the osThreadState enumerated type.
Definition at line 1382 of file cmsis_os.c.
References eBlocked, eDeleted, eReady, eRunning, eSuspended, and eTaskGetState().
osThreadIsSuspended()
osStatus osThreadIsSuspended (osThreadId thread_id)
Check if a thread is already suspended or not.
Parameters
thread_id thread ID obtained by osThreadCreate or osThreadGetId.
Return values
status code that indicates the execution status of the function.
Definition at line 1420 of file cmsis_os.c.
References eSuspended, eTaskGetState(), osErrorOS, and osOK.
osThreadList()
osStatus osThreadList (uint8_t * buffer)
Lists all the current threads, along with their current state and stack usage high water mark.
Parameters
buffer A buffer into which the above mentioned details will be written
Return values
status code that indicates the execution status of the function.
Definition at line 1542 of file cmsis_os.c.
References osOK, and vTaskList().
osThreadResume()
osStatus osThreadResume (osThreadId thread_id)
Resume execution of a suspended thread.
Parameters
thread_id thread ID obtained by osThreadCreate or osThreadGetId.
Return values
status code that indicates the execution status of the function.
Definition at line 1449 of file cmsis_os.c.
References inHandlerMode(), osErrorResource, osOK, pdTRUE, portYIELD_FROM_ISR, vTaskResume(), and xTaskResumeFromISR().
osThreadResumeAll()
osStatus osThreadResumeAll (void)
Resume execution of a all suspended threads.
Return values
status code that indicates the execution status of the function.
Definition at line 1484 of file cmsis_os.c.
References osErrorOS, osOK, pdTRUE, and xTaskResumeAll().
osThreadSetPriority()
osStatus osThreadSetPriority (osThreadId thread_id, osPriority priority)
Change priority of an active thread.
Parameters
thread_id thread ID obtained by osThreadCreate or osThreadGetId.
priority new priority value for the thread function.
Return values
status code that indicates the execution status of the function.
Note
MUST REMAIN UNCHANGED: osThreadSetPriority shall be consistent in every CMSIS-RTOS.
Definition at line 285 of file cmsis_os.c.
References makeFreeRtosPriority(), osErrorOS, osOK, and vTaskPrioritySet().
osThreadSuspend()
osStatus osThreadSuspend (osThreadId thread_id)
Suspend execution of a thread.
Parameters
thread_id thread ID obtained by osThreadCreate or osThreadGetId.
Return values
status code that indicates the execution status of the function.
Definition at line 1433 of file cmsis_os.c.
References osErrorResource, osOK, and vTaskSuspend().
osThreadSuspendAll()
osStatus osThreadSuspendAll (void)
Suspend execution of a all active threads.
Return values
status code that indicates the execution status of the function.
Definition at line 1473 of file cmsis_os.c.
References osOK, and vTaskSuspendAll().
osThreadTerminate()
osStatus osThreadTerminate (osThreadId thread_id)
Terminate execution of a thread and remove it from Active Threads.
Parameters
thread_id thread ID obtained by osThreadCreate or osThreadGetId.
Return values
status code that indicates the execution status of the function.
Note
MUST REMAIN UNCHANGED: osThreadTerminate shall be consistent in every CMSIS-RTOS.
Definition at line 256 of file cmsis_os.c.
References osErrorOS, osOK, and vTaskDelete().
osThreadYield()
osStatus osThreadYield (void)
Pass control to next thread that is in state READY.
Return values
status code that indicates the execution status of the function.
Note
MUST REMAIN UNCHANGED: osThreadYield shall be consistent in every CMSIS-RTOS.
Definition at line 271 of file cmsis_os.c.
References osOK, and taskYIELD.
osTimerCreate()
osTimerId osTimerCreate (const osTimerDef_t * timer_def, os_timer_type type, void * argument)
Create a timer.
Parameters
timer_def timer object referenced with osTimer.
type osTimerOnce for one-shot or osTimerPeriodic for periodic behavior.
argument argument to the timer call back function.
Return values
timer ID for reference by other functions or NULL in case of error.
Note
MUST REMAIN UNCHANGED: osTimerCreate shall be consistent in every CMSIS-RTOS.
Definition at line 358 of file cmsis_os.c.
References osTimerPeriodic, pdFALSE, pdTRUE, and os_timer_def::ptimer.
osTimerDelete()
osStatus osTimerDelete (osTimerId timer_id)
Delete a timer.
Parameters
timer_id timer ID obtained by osTimerCreate
Return values
status code that indicates the execution status of the function.
Note
MUST REMAIN UNCHANGED: osTimerDelete shall be consistent in every CMSIS-RTOS.
Definition at line 473 of file cmsis_os.c.
References inHandlerMode(), osErrorISR, osErrorOS, osOK, osWaitForever, pdPASS, and xTimerDelete.
osTimerStart()
osStatus osTimerStart (osTimerId timer_id, uint32_t millisec)
Start or restart a timer.
Parameters
timer_id timer ID obtained by osTimerCreate.
millisec time delay value of the timer.
Return values
status code that indicates the execution status of the function
Note
MUST REMAIN UNCHANGED: osTimerStart shall be consistent in every CMSIS-RTOS.
Definition at line 405 of file cmsis_os.c.
References inHandlerMode(), osErrorOS, osOK, pdFALSE, pdPASS, portBASE_TYPE, portEND_SWITCHING_ISR, portTICK_PERIOD_MS, xTimerChangePeriod, and xTimerChangePeriodFromISR.
osTimerStop()
osStatus osTimerStop (osTimerId timer_id)
Stop a timer.
Parameters
timer_id timer ID obtained by osTimerCreate
Return values
status code that indicates the execution status of the function.
Note
MUST REMAIN UNCHANGED: osTimerStop shall be consistent in every CMSIS-RTOS.
Definition at line 444 of file cmsis_os.c.
References inHandlerMode(), osErrorOS, osOK, pdFALSE, pdPASS, portBASE_TYPE, portEND_SWITCHING_ISR, xTimerStop, and xTimerStopFromISR.
xPortSysTickHandler()
void xPortSysTickHandler (void) [extern]
Definition at line 488 of file port.c.
References pdFALSE, portDISABLE_INTERRUPTS, portENABLE_INTERRUPTS, portNVIC_INT_CTRL_REG, portNVIC_PENDSVSET_BIT, and xTaskIncrementTick().
Referenced by osSystickHandler().