Core/Inc/daq.h File Reference
#include "uvfr_utils.h"
#include "rb_tree.h"
Data Structures
struct daq_msg
struct daq_loop_args
This struct holds info of what needs to be logged.
Macros
#define _NUM_LOGGABLE_PARAMS
Typedefs
typedef struct daq_msg daq_msg
typedef struct daq_loop_args daq_loop_args
This struct holds info of what needs to be logged.
Enumerations
enum loggable_params {
VCU_VEHICLE_STATE
, VCU_ERROR_BITFIELD1
, VCU_ERROR_BITFIELD2
, VCU_ERROR_BITFIELD3
,
VCU_ERROR_BITFIELD4
, VCU_CURRENT_UPTIME
, VCU_TOTAL_UPTIME
, OS_AVAILABLE_HEAP
,
OS_LARGEST_FREE_BLOCK
, OS_SMALLEST_FREE_BLOCK
, OS_NUM_FREE_BLOCKS
, OS_MIN_EVER_FREE_BYTES
,
OS_NUM_SUCCESSFUL_ALLOCS
, OS_NUM_SUCCESSFUL_FREES
, VEH_DISTANCE_RUN
, VEH_DISTANCE_TOTAL
,
VEH_LAPNUM
, VEH_SPEED
, MOTOR_RPM
, MOTOR_TEMP
,
MOTOR_CURRENT
, MC_VOLTAGE
, MC_CURRENT
, MC_TEMP
,
MC_ERRORS
, BMS_CURRENT
, BMS_VOLTAGE
, BMS_ERRORS
,
MAX_CELL_TEMP
, MIN_CELL_TEMP
, AVG_CELL_TEMP
, ACCUM_SOC
,
ACCUM_SOH
, ACCUM_POWER
, ACCUM_POWER_LIMIT
, APPS1_ADC_VAL
,
APPS2_ADC_VAL
, BPS1_ADC_VAL
, BPS2_ADC_VAL
, COOLANT_TEMP_ADC
,
MOTOR_TEMP_ADC
, ACCELERATOR_PEDAL_RATIO
, BRAKE_PRESSURE_PA
, POWER_DERATE_FACTOR
,
CURRENT_DRIVING_MODE
, IMD_VOLTAGE
, IMD_STATUS
, IMD_ERRORS
,
SUS_DAMPER_FL
, SUS_DUMPER_FR
, SUS_DAMPER_RL
, SUS_DAMPER_RR
,
WSS_FR
, WSS_FL
, WSS_RL
, WSS_RR
,
WSS_F_AVG
, WSS_R_AVG
, WSS_SLIP
, MAX_LOGGABLE_PARAMS
 }
Functions
uv_status associateDaqParamWithVar (uint16_t paramID, void *var)
uv_status initDaqTask (void *args)
initializes the master DAQ task, all that fun stuff. This task probably manages a while plethora of smaller tasks
void daqMasterTask (void *args)
Controls the Daq.
Macro Definition Documentation
_NUM_LOGGABLE_PARAMS
#define _NUM_LOGGABLE_PARAMS
Definition at line 14 of file daq.h.
Typedef Documentation
daq_loop_args
typedef struct daq_loop_args daq_loop_args
This struct holds info of what needs to be logged.
daq_msg
typedef struct daq_msg daq_msg
Enumeration Type Documentation
loggable_params
enum loggable_params
Enumerator
VCU_VEHICLE_STATE VCU Current Vehicle State
VCU_ERROR_BITFIELD1
VCU_ERROR_BITFIELD2
VCU_ERROR_BITFIELD3
VCU_ERROR_BITFIELD4
VCU_CURRENT_UPTIME
VCU_TOTAL_UPTIME
OS_AVAILABLE_HEAP
OS_LARGEST_FREE_BLOCK
OS_SMALLEST_FREE_BLOCK
OS_NUM_FREE_BLOCKS
OS_MIN_EVER_FREE_BYTES
OS_NUM_SUCCESSFUL_ALLOCS
OS_NUM_SUCCESSFUL_FREES
VEH_DISTANCE_RUN
VEH_DISTANCE_TOTAL
VEH_LAPNUM
VEH_SPEED
MOTOR_RPM RPM as reported by motor controller
MOTOR_TEMP Motor Temp as reported by motor controller
MOTOR_CURRENT Motor Phase currents as reported by motor controller
MC_VOLTAGE Pack voltage as measured by motor_controller
MC_CURRENT Pack current as measured by motor_controller
MC_TEMP Motor controller temperature
MC_ERRORS Motor controller errors bitfield
BMS_CURRENT Pack current measured by BMS
BMS_VOLTAGE Pack voltage as measured by BMS
BMS_ERRORS Error codes in BMS
MAX_CELL_TEMP Max Temperature of a cell from BMS
MIN_CELL_TEMP Min Temperature of a cell
AVG_CELL_TEMP Average Cell Temp
ACCUM_SOC
ACCUM_SOH
ACCUM_POWER
ACCUM_POWER_LIMIT
APPS1_ADC_VAL
APPS2_ADC_VAL
BPS1_ADC_VAL
BPS2_ADC_VAL
COOLANT_TEMP_ADC
MOTOR_TEMP_ADC
ACCELERATOR_PEDAL_RATIO
BRAKE_PRESSURE_PA
POWER_DERATE_FACTOR
CURRENT_DRIVING_MODE
IMD_VOLTAGE Accumulator voltage as measured by IMD
IMD_STATUS
IMD_ERRORS
SUS_DAMPER_FL
SUS_DUMPER_FR
SUS_DAMPER_RL
SUS_DAMPER_RR
WSS_FR
WSS_FL
WSS_RL
WSS_RR
WSS_F_AVG
WSS_R_AVG
WSS_SLIP
MAX_LOGGABLE_PARAMS THIS MUST BE THE FINAL PARAM
Definition at line 18 of file daq.h.
Function Documentation
associateDaqParamWithVar()
uv_status associateDaqParamWithVar (uint16_t paramID, void * var)
Definition at line 87 of file daq.c.
References MAX_LOGGABLE_PARAMS, param_ptrs, UV_ERROR, UV_OK, and uvIsPTRValid().
Referenced by initDaqTask(), initDrivingLoop(), and uvInitStateEngine().
daqMasterTask()
void daqMasterTask (void * args)
Controls the Daq.
These here lines set the delay. This task executes exactly at the period specified, regardless of how long the task execution actually takes
 */
//TickType_t tick_period = pdMS_TO_TICKS(params->task_period); //Convert ms of period to the RTOS ticks
//TickType_t last_time = xTaskGetTickCount(); /**
Definition at line 305 of file daq.c.
References uv_task_info::cmd_data, killSelf(), startDaqSubTasks(), uv_task_info::task_period, UV_KILL_CMD, UV_OK, UV_SUSPEND_CMD, uvTaskDelay, and vTaskDelay().
Referenced by initDaqTask().
initDaqTask()
uv_status initDaqTask (void * args)
initializes the master DAQ task, all that fun stuff. This task probably manages a while plethora of smaller tasks
This is a fairly standard function. Here are the things that it does in order:
Step 1: Get Daq settings.
Step 2: Create and configure DAQ task.
Step 3: Read which parameters we want to read.
Step 4: Generate Subtask Metadata
Step 5: Assign params to subtasks
Definition at line 257 of file daq.c.
References uv_task_info::active_states, associateDaqParamWithVar(), daq_loop_args::can_channel, configureDaqSubTasks(), COOLANT_TEMP_ADC, coolant_temp_adc, curr_daq_settings, current_vehicle_settings, daq_loop_args::daq_child_priority, uv_vehicle_settings::daq_param_list, uv_vehicle_settings::daq_settings, daqMasterTask(), datapoints, uv_task_info::deletion_states, uv_CAN_msg::flags, MOTOR_TEMP_ADC, motor_temp_adc, PROGRAMMING, uv_task_info::stack_size, uv_task_info::suspension_states, uv_task_info::task_args, uv_task_info::task_function, uv_task_info::task_name, uv_task_info::task_period, uv_task_info::task_priority, tmp_daq_msg, UV_DRIVING, UV_ERROR, UV_ERROR_STATE, UV_LAUNCH_CONTROL, UV_OK, UV_READY, and uvCreateTask().
Referenced by uvInitStateEngine().