Core/Src/daq.c File Reference
#include "uvfr_utils.h"
#include "daq.h"
#include "stm32f4xx_hal_conf.h"
#include "stm32f407xx.h"
#include "stm32f4xx_hal.h"
#include "stm32f4xx_hal_adc.h"
#include "stm32f4xx_hal_rcc.h"
Data Structures
struct daq_param_list_node
struct daq_child_task
Macros
#define _SRC_UVFR_DAQ
Typedefs
typedef struct daq_param_list_node daq_param_list_node
typedef struct daq_child_task daq_child_task
Functions
void daqSubTask (void *args)
uv_status associateDaqParamWithVar (uint16_t paramID, void *var)
static void insertParamToParamList (daq_param_list_node *node, daq_param_list_node **list)
uv_status insertParamToRegister (daq_param_list_node *node, daq_datapoint *datapoint)
uv_status configureDaqSubTasks ()
This pre-allocates parameters to one of the daq subtasks.
uv_status startDaqSubTasks ()
Function that starts up all the subtasks.
uv_status stopDaqSubTasks ()
Function that shuts down the subtasks.
uv_status initDaqTask (void *args)
initializes the master DAQ task, all that fun stuff. This task probably manages a while plethora of smaller tasks
void daqMasterTask (void *args)
Controls the Daq.
static void sendDaqMsg (daq_param_list_node *param)
static void sendAllParamsFromList (daq_param_list_node *list)
Variables
volatile uint16_t coolant_temp_adc = 0
volatile uint16_t motor_temp_adc = 0
ADC_HandleTypeDef hadc1
daq_loop_args * curr_daq_settings = NULL
daq_loop_args default_daq_settings
daq_datapoint default_datapoints []
static void * param_ptrs [MAX_LOGGABLE_PARAMS]
static daq_child_task * daq_tlist = NULL
static daq_datapoint * datapoints = NULL
static daq_param_list_node * param_bank = NULL
uv_CAN_msg tmp_daq_msg
Macro Definition Documentation
_SRC_UVFR_DAQ
#define _SRC_UVFR_DAQ
Definition at line 1 of file daq.c.
Typedef Documentation
daq_child_task
typedef struct daq_child_task daq_child_task
daq_param_list_node
typedef struct daq_param_list_node daq_param_list_node
Function Documentation
associateDaqParamWithVar()
uv_status associateDaqParamWithVar (uint16_t paramID, void * var)
Definition at line 125 of file daq.c.
References MAX_LOGGABLE_PARAMS, param_ptrs, UV_ERROR, UV_OK, and uvIsPTRValid().
Referenced by initDaqTask(), initDrivingLoop(), and uvInitStateEngine().
configureDaqSubTasks()
uv_status configureDaqSubTasks ()
This pre-allocates parameters to one of the daq subtasks.
Definition at line 218 of file daq.c.
References curr_daq_settings, current_vehicle_settings, uv_vehicle_settings::daq_param_list, insertParamToRegister(), param_bank, daq_loop_args::total_params_logged, UV_ERROR, and UV_OK.
Referenced by initDaqTask().
daqMasterTask()
void daqMasterTask (void * args)
Controls the Daq.
These here lines set the delay. This task executes exactly at the period specified, regardless of how long the task execution actually takes
 */
TickType_t tick_period = pdMS_TO_TICKS(params->task_period); //Convert ms of period to the RTOS ticks
//TickType_t last_time = xTaskGetTickCount(); /**
Definition at line 336 of file daq.c.
References uv_task_info::cmd_data, killSelf(), pdMS_TO_TICKS, startDaqSubTasks(), uv_task_info::task_period, UV_KILL_CMD, UV_OK, UV_SUSPEND_CMD, uvTaskDelay, and vTaskDelay().
Referenced by initDaqTask().
daqSubTask()
void daqSubTask (void * args)
Definition at line 428 of file daq.c.
References daq_child_task::param_list, pdMS_TO_TICKS, daq_child_task::period, sendAllParamsFromList(), vTaskDelayUntil(), and xTaskGetTickCount().
Referenced by startDaqSubTasks().
initDaqTask()
uv_status initDaqTask (void * args)
initializes the master DAQ task, all that fun stuff. This task probably manages a while plethora of smaller tasks
This is a fairly standard function. Here are the things that it does in order:
Step 1: Get Daq settings.
Step 2: Create and configure DAQ task.
Step 3: Read which parameters we want to read.
Step 4: Generate Subtask Metadata
Step 5: Assign params to subtasks
Definition at line 288 of file daq.c.
References uv_task_info::active_states, associateDaqParamWithVar(), daq_loop_args::can_channel, configureDaqSubTasks(), COOLANT_TEMP_ADC, coolant_temp_adc, curr_daq_settings, current_vehicle_settings, daq_loop_args::daq_child_priority, uv_vehicle_settings::daq_param_list, uv_vehicle_settings::daq_settings, daqMasterTask(), datapoints, uv_task_info::deletion_states, uv_CAN_msg::flags, MOTOR_TEMP_ADC, motor_temp_adc, MX_ADC1_Init(), PROGRAMMING, uv_task_info::stack_size, uv_task_info::suspension_states, uv_task_info::task_args, uv_task_info::task_function, uv_task_info::task_name, uv_task_info::task_period, uv_task_info::task_priority, tmp_daq_msg, UV_DRIVING, UV_ERROR, UV_ERROR_STATE, UV_LAUNCH_CONTROL, UV_OK, UV_READY, and uvCreateTask().
Referenced by uvInitStateEngine().
insertParamToParamList()
static void insertParamToParamList (daq_param_list_node * node, daq_param_list_node ** list) [inline], [static]
Definition at line 142 of file daq.c.
References daq_param_list_node::next.
Referenced by insertParamToRegister().
insertParamToRegister()
uv_status insertParamToRegister (daq_param_list_node * node, daq_datapoint * datapoint)
Definition at line 162 of file daq.c.
References daq_datapoint::can_id, daq_param_list_node::can_id, daq_tlist, data_size, insertParamToParamList(), daq_param_list_node::next, daq_child_task::next_task, daq_datapoint::param, daq_param_list_node::param, daq_child_task::param_list, daq_child_task::period, daq_datapoint::period, daq_param_list_node::size, daq_datapoint::type, and UV_OK.
Referenced by configureDaqSubTasks().
sendAllParamsFromList()
static void sendAllParamsFromList (daq_param_list_node * list) [inline], [static]
Definition at line 413 of file daq.c.
References daq_param_list_node::next, and sendDaqMsg().
Referenced by daqSubTask().
sendDaqMsg()
static void sendDaqMsg (daq_param_list_node * param) [inline], [static]
Definition at line 390 of file daq.c.
References daq_param_list_node::can_id, uv_CAN_msg::data, uv_CAN_msg::dlc, uv_CAN_msg::msg_id, daq_param_list_node::param, param_ptrs, daq_param_list_node::size, tmp_daq_msg, and uvSendCanMSG().
Referenced by sendAllParamsFromList().
startDaqSubTasks()
uv_status startDaqSubTasks ()
Function that starts up all the subtasks.
Definition at line 245 of file daq.c.
References curr_daq_settings, daq_loop_args::daq_child_priority, daq_tlist, daqSubTask(), daq_child_task::meta_task_handle, daq_child_task::next_task, and UV_OK.
Referenced by daqMasterTask().
stopDaqSubTasks()
uv_status stopDaqSubTasks ()
Function that shuts down the subtasks.
Definition at line 262 of file daq.c.
References daq_tlist, daq_child_task::meta_task_handle, UV_ERROR, and vTaskDelete().
Variable Documentation
coolant_temp_adc
volatile uint16_t coolant_temp_adc = 0
Definition at line 15 of file daq.c.
Referenced by initDaqTask().
curr_daq_settings
daq_loop_args* curr_daq_settings = NULL
Definition at line 43 of file daq.c.
Referenced by configureDaqSubTasks(), initDaqTask(), and startDaqSubTasks().
daq_tlist
daq_child_task* daq_tlist = NULL [static]
Definition at line 114 of file daq.c.
Referenced by insertParamToRegister(), startDaqSubTasks(), and stopDaqSubTasks().
datapoints
daq_datapoint* datapoints = NULL [static]
Definition at line 116 of file daq.c.
Referenced by initDaqTask().
default_daq_settings
daq_loop_args default_daq_settings
Initial value:
= {
    .total_params_logged = 8,
    .throttle_daq_to_preserve_performance = 1,
    .minimum_daq_period = 10,
    .can_channel = CAN_BUS_1,
    .daq_child_priority = 1
}
Definition at line 45 of file daq.c.
Referenced by setupDefaultSettings(), and uvResetFlashToDefault().
default_datapoints
daq_datapoint default_datapoints[]
Definition at line 53 of file daq.c.
Referenced by setupDefaultSettings(), and uvResetFlashToDefault().
hadc1
ADC_HandleTypeDef hadc1
Definition at line 19 of file daq.c.
Referenced by ADC_IRQHandler(), HAL_ADC_ConvCpltCallback(), and HAL_ADC_LevelOutOfWindowCallback().
motor_temp_adc
volatile uint16_t motor_temp_adc = 0
Definition at line 16 of file daq.c.
Referenced by initDaqTask().
param_bank
daq_param_list_node* param_bank = NULL [static]
Definition at line 118 of file daq.c.
Referenced by configureDaqSubTasks().
param_ptrs
void* param_ptrs[MAX_LOGGABLE_PARAMS] [static]
Definition at line 112 of file daq.c.
Referenced by associateDaqParamWithVar(), and sendDaqMsg().
tmp_daq_msg
uv_CAN_msg tmp_daq_msg
Definition at line 271 of file daq.c.
Referenced by initDaqTask(), and sendDaqMsg().