Core/Src/dash.c File Reference
#include "dash.h"
#include "can.h"
#include "main.h"
Functions
void Update_RPM (int16_t value)
void Update_Batt_Temp (uint8_t value)
void Update_State_Of_Charge (uint8_t value)
Function Documentation
Update_Batt_Temp()
void Update_Batt_Temp (uint8_t value)
Definition at line 29 of file dash.c.
References Dash_Battery_Temperature, Error_Handler(), hcan2, TxData, TxHeader, and TxMailbox.
Update_RPM()
void Update_RPM (int16_t value)
Definition at line 9 of file dash.c.
References Dash_RPM, Error_Handler(), hcan2, TxData, TxHeader, and TxMailbox.
Referenced by main().
Update_State_Of_Charge()
void Update_State_Of_Charge (uint8_t value)
Definition at line 48 of file dash.c.
References Dash_State_of_Charge, Error_Handler(), hcan2, TxData, TxHeader, and TxMailbox.