Core/Src/driving_loop.c File Reference
File containing the meat and potatoes driving loop thread, and all supporting functions.
#include "main.h"
#include "uvfr_utils.h"
#include "can.h"
#include "motor_controller.h"
#include <stdlib.h>
#include <stdio.h>
#include <math.h>
#include "driving_loop.h"
#include "../FreeRTOS/Source/CMSIS_RTOS/cmsis_os.h"
#include "../FreeRTOS/Source/include/FreeRTOS.h"
#include "../FreeRTOS/Source/include/task.h"
Macros
#define INPUT_TIMEOUT_MS 500
#define THROTTLE_CHANGE_THRESHOLD 5
#define BRAKE_CHANGE_THRESHOLD 5
#define TORQUE_DECAY_STEP 2.5f
#define THROTTLE_ZERO_THRESHOLD 0.01f
#define ACCELERATION 0
#define AUTOCROSS 1
#define ENDURANCE 2
Functions
float calculateThrottlePercentage (uint16_t apps1, uint16_t apps2)
float calculateBrakePercentage (uint16_t bps1)
bool performSafetyChecks (driving_loop_args *dl_params, uint16_t apps1_value, uint16_t apps2_value, uint16_t bps1_value, uint16_t bps2_value, enum DL_internal_state *dl_status)
Performs safety checks on APPS (Throttle) and BPS (Brake) sensors.
static float getKValue (int raceMode)
enum uv_status_t initDrivingLoop (void *argument)
static float mapThrottleToTorque (float throttle_percent)
static float applyTorqueFilter (float T_req, float T_prev, bool is_accelearting)
Applies filtering to smooth torque transitions.
void StartDrivingLoop (void *argument)
Sends the filtered torque value to the motor controller.
Variables
uint16_t adc1_APPS1
uint16_t adc1_APPS2
uint16_t adc1_BPS1
uint16_t adc1_BPS2
driving_loop_args default_dl_settings
driving_loop_args * driving_args = NULL
bool is_accelerating = false
float T_PREV = 0
float T_REQ = 0
static bool torque_inhibit_active = false
static TickType_t last_input_change_time = 0
static float last_throttle_percent = 0.0f
static float last_brake_percent = 0.0f
static bool sent_zero_torque = false
Detailed Description
File containing the meat and potatoes driving loop thread, and all supporting functions.
Definition in file driving_loop.c.
Macro Definition Documentation
ACCELERATION
#define ACCELERATION 0
Definition at line 156 of file driving_loop.c.
Referenced by getKValue().
AUTOCROSS
#define AUTOCROSS 1
Definition at line 157 of file driving_loop.c.
Referenced by getKValue().
BRAKE_CHANGE_THRESHOLD
#define BRAKE_CHANGE_THRESHOLD 5
Definition at line 45 of file driving_loop.c.
Referenced by StartDrivingLoop().
ENDURANCE
#define ENDURANCE 2
Definition at line 158 of file driving_loop.c.
Referenced by getKValue().
INPUT_TIMEOUT_MS
#define INPUT_TIMEOUT_MS 500
Definition at line 43 of file driving_loop.c.
Referenced by StartDrivingLoop().
THROTTLE_CHANGE_THRESHOLD
#define THROTTLE_CHANGE_THRESHOLD 5
Definition at line 44 of file driving_loop.c.
Referenced by StartDrivingLoop().
THROTTLE_ZERO_THRESHOLD
#define THROTTLE_ZERO_THRESHOLD 0.01f
Definition at line 53 of file driving_loop.c.
TORQUE_DECAY_STEP
#define TORQUE_DECAY_STEP 2.5f
Definition at line 52 of file driving_loop.c.
Function Documentation
applyTorqueFilter()
static float applyTorqueFilter (float T_req, float T_prev, bool is_accelearting) [inline], [static]
Applies filtering to smooth torque transitions.
Parameters
T_req Requested torque before filtering.
T_prev Previous filtered torque value.
Returns
Smoothed torque value.
Definition at line 222 of file driving_loop.c.
References getKValue(), and is_accelerating.
Referenced by StartDrivingLoop().
calculateBrakePercentage()
float calculateBrakePercentage (uint16_t bps1)
Definition at line 203 of file driving_loop.c.
References driving_args, driving_loop_args::max_BPS_value, and driving_loop_args::min_BPS_value.
Referenced by performSafetyChecks(), and StartDrivingLoop().
calculateThrottlePercentage()
float calculateThrottlePercentage (uint16_t apps1, uint16_t apps2)
Definition at line 174 of file driving_loop.c.
References driving_loop_args::apps1_bottom, driving_loop_args::apps1_top, and driving_args.
Referenced by performSafetyChecks(), and StartDrivingLoop().
getKValue()
float getKValue (int raceMode) [inline], [static]
Definition at line 161 of file driving_loop.c.
References ACCELERATION, AUTOCROSS, and ENDURANCE.
Referenced by applyTorqueFilter().
initDrivingLoop()
enum uv_status_t initDrivingLoop (void * argument)
Definition at line 108 of file driving_loop.c.
References uv_task_info::active_states, adc1_APPS1, adc1_APPS2, adc1_BPS1, adc1_BPS2, APPS1_ADC_VAL, APPS2_ADC_VAL, associateDaqParamWithVar(), BPS1_ADC_VAL, BPS2_ADC_VAL, current_vehicle_settings, uv_task_info::deletion_states, driving_args, uv_vehicle_settings::driving_loop_settings, osPriorityHigh, PROGRAMMING, uv_task_info::stack_size, StartDrivingLoop(), uv_task_info::suspension_states, uv_task_info::task_args, uv_task_info::task_function, uv_task_info::task_name, uv_task_info::task_period, uv_task_info::task_priority, UV_DRIVING, UV_ERROR, UV_ERROR_STATE, UV_INIT, UV_LAUNCH_CONTROL, UV_OK, UV_READY, UV_SUSPENDED, and uvCreateTask().
Referenced by uvInitStateEngine().
mapThrottleToTorque()
static float mapThrottleToTorque (float throttle_percent) [inline], [static]
Definition at line 142 of file driving_loop.c.
References driving_loop_args::absolute_max_motor_torque, and driving_args.
Referenced by StartDrivingLoop().
performSafetyChecks()
bool performSafetyChecks (driving_loop_args * dl_params, uint16_t apps1_value, uint16_t apps2_value, uint16_t bps1_value, uint16_t bps2_value, enum DL_internal_state * dl_status)
Performs safety checks on APPS (Throttle) and BPS (Brake) sensors.
This function ensures that:
Throttle position sensors (APPS1 & APPS2) are within 10% of each other.
Brake pressure sensors (BPS1 & BPS2) are within 5% of each other.
Sensors are within their expected min/max ranges.
Brake and throttle are not pressed at the same time.
If a fatal error is detected (e.g., sensor out of range), the function:
Stops the motor.
Kills the task execution (killSelf()).
If a non-fatal error occurs (e.g., sensor mismatch exceeding the limit):
Stops the motor.
Suspends the task temporarily (suspendSelf()).
If safety conditions return to normal, the function:
Restarts the motor.
Parameters
dl_params Pointer to the driving loop parameters.
apps1_value Raw sensor reading from APPS1.
apps2_value Raw sensor reading from APPS2.
bps1_value Raw sensor reading from BPS1.
bps2_value Raw sensor reading from BPS2.
params Pointer to the current task information.
dl_status Pointer to the driving loop internal state.
Return values
true All safety checks passed.
false One or more safety checks failed.
Definition at line 432 of file driving_loop.c.
References driving_loop_args::apps1_abs_max_val, driving_loop_args::apps1_bottom, driving_loop_args::apps1_top, driving_loop_args::apps2_abs_max_val, driving_loop_args::apps2_bottom, driving_loop_args::apps2_top, driving_loop_args::apps_plausibility_check_threshold, calculateBrakePercentage(), calculateThrottlePercentage(), driving_loop_args::max_BPS_value, MC_Shutdown(), and torque_inhibit_active.
Referenced by StartDrivingLoop().
StartDrivingLoop()
void StartDrivingLoop (void * argument)
Sends the filtered torque value to the motor controller.
Rachan
Parameters
T_filtered Final torque value after filtering.
This line extracts the specific driving loop parameters as specified in the vehicle settings
 */
driving_loop_args* dl_params = current_vehicle_settings->driving_loop_settings;
//Timeout values
//static TickType_t last_input_change_time = 0;
//static float last_throttle_percent = 0.0f;
//static float last_brake_percent = 0.0f;
TickType_t tick_period = pdMS_TO_TICKS(params->task_period); //Convert ms of period to the RTOS ticks
TickType_t last_time = xTaskGetTickCount();
last_input_change_time = last_time;
/**
Definition at line 254 of file driving_loop.c.
References adc1_APPS1, adc1_APPS2, adc1_BPS1, adc1_BPS2, applyTorqueFilter(), BRAKE_CHANGE_THRESHOLD, calculateBrakePercentage(), calculateThrottlePercentage(), uv_task_info::cmd_data, current_vehicle_settings, uv_vehicle_settings::driving_loop_settings, INPUT_TIMEOUT_MS, is_accelerating, killSelf(), last_brake_percent, last_driver_input_time, last_input_change_time, last_throttle_percent, mapThrottleToTorque(), pdMS_TO_TICKS, performSafetyChecks(), Plausible, sendTorqueToMotorController(), sent_zero_torque, suspendSelf(), T_PREV, T_REQ, uv_task_info::task_period, THROTTLE_CHANGE_THRESHOLD, torque_inhibit_active, UV_DRIVING, UV_KILL_CMD, UV_SUSPEND_CMD, vehicle_state, vTaskDelayUntil(), and xTaskGetTickCount().
Referenced by initDrivingLoop().
Variable Documentation
adc1_APPS1
uint16_t adc1_APPS1 [extern]
Definition at line 67 of file main.c.
Referenced by HAL_ADC_LevelOutOfWindowCallback(), initDrivingLoop(), main(), and StartDrivingLoop().
adc1_APPS2
uint16_t adc1_APPS2 [extern]
Definition at line 68 of file main.c.
Referenced by HAL_ADC_LevelOutOfWindowCallback(), initDrivingLoop(), main(), and StartDrivingLoop().
adc1_BPS1
uint16_t adc1_BPS1 [extern]
Definition at line 69 of file main.c.
Referenced by initDrivingLoop(), and StartDrivingLoop().
adc1_BPS2
uint16_t adc1_BPS2 [extern]
Definition at line 70 of file main.c.
Referenced by initDrivingLoop(), and StartDrivingLoop().
default_dl_settings
driving_loop_args default_dl_settings
Definition at line 29 of file driving_loop.c.
Referenced by setupDefaultSettings(), and uvResetFlashToDefault().
driving_args
driving_loop_args* driving_args = NULL
Definition at line 31 of file driving_loop.c.
Referenced by calculateBrakePercentage(), calculateThrottlePercentage(), initDrivingLoop(), and mapThrottleToTorque().
is_accelerating
bool is_accelerating = false
Definition at line 33 of file driving_loop.c.
Referenced by applyTorqueFilter(), and StartDrivingLoop().
last_brake_percent
float last_brake_percent = 0.0f [static]
Definition at line 50 of file driving_loop.c.
Referenced by StartDrivingLoop().
last_input_change_time
TickType_t last_input_change_time = 0 [static]
Definition at line 48 of file driving_loop.c.
Referenced by StartDrivingLoop().
last_throttle_percent
float last_throttle_percent = 0.0f [static]
Definition at line 49 of file driving_loop.c.
Referenced by StartDrivingLoop().
sent_zero_torque
bool sent_zero_torque = false [static]
Definition at line 54 of file driving_loop.c.
Referenced by StartDrivingLoop().
T_PREV
float T_PREV = 0
Definition at line 34 of file driving_loop.c.
Referenced by StartDrivingLoop().
T_REQ
float T_REQ = 0
Definition at line 35 of file driving_loop.c.
Referenced by StartDrivingLoop().
torque_inhibit_active
bool torque_inhibit_active = false [static]
Definition at line 37 of file driving_loop.c.
Referenced by performSafetyChecks(), and StartDrivingLoop().