UVFR CANbus API
This is an api that simplifies usage of CANbus transmitting and receiving.
Functions
void insertCANMessageHandler (uint32_t id, void *handlerfunc, int can_num)
Function to insert an id and function into the lookup table of callback functions.
uv_status uvSendCanMSG (uv_CAN_msg *tx_msg)
Function to send CAN message.
Detailed Description
This is an api that simplifies usage of CANbus transmitting and receiving.
Function Documentation
insertCANMessageHandler()
void insertCANMessageHandler (uint32_t id, void * handlerfunc, int can_num)
Function to insert an id and function into the lookup table of callback functions.
Checks if specific hash id already exists in the hash table If not, insert the message If it already exists, check to see if the actual CAN id matches. If yes, then previous entries are overwritten If it does not exist, then each node in the hash table functions as it's own linked list
Definition at line 652 of file can.c.
References callback_table_1_mutex, callback_table_2_mutex, CAN_BUS_1, CAN_callback_table_1, CAN_callback_table_2, CAN_Callback::CAN_id, CAN_Callback::function, generateHash(), CAN_Callback::next, pdTRUE, UV_ERROR, xSemaphoreGive, and xSemaphoreTake.
Referenced by BMS_Init(), MC_Startup(), tempMonitorTask(), and uvSettingsInit().
uvSendCanMSG()
uv_status uvSendCanMSG (uv_CAN_msg * tx_msg)
Function to send CAN message.
This function is the canonical team method of sending a CAN message. It invokes the canTxDaemon, to avoid any conflicts due to a context switch mid transmission Is it a little bit convoluted? Yes. Is that worth it? Still yes.
Definition at line 864 of file can.c.
References __uvCANtxCritSection(), is_can_ok, pdPASS, Tx_msg_queue, UV_ERROR, UV_OK, xQueueSendToBack, and xQueueSendToBackFromISR.
Referenced by flushLogsToCAN(), handleIncomingLaptopMsg(), MC_EnableCyclicSpeedTransmission(), MC_Request_Data(), MC_Set_Param(), sendDaqMsg(), sendTorqueToMotorController(), tempMonitorTask(), testfunc2(), testfunc3(), u19updatePduChannel(), uvSendSpecificParam(), uvSettingsInit(), and uvSettingsProgrammerTask().