State Engine API
Provides publically available API for controlling vehicle state and error handling.
Data Structures
struct uv_scd_response
struct task_management_info
Struct to contain data about a parent task.
struct task_status_block
Information about the task.
struct uv_os_settings
Settings that dictate state engine behavior.
struct uv_task_info
This struct is designed to hold neccessary information about an RTOS task that will be managed by uvfr_state_engine.
Macros
#define UV_TASK_VEHICLE_APPLICATION 0x0001U<<(0)
#define UV_TASK_PERIODIC_SVC 0x0001U<<(1)
#define UV_TASK_DORMANT_SVC 0b0000000000000011
#define UV_TASK_GENERIC_SVC 0x0001U<<(2)
#define UV_TASK_MANAGER_MASK 0b0000000000000011
#define UV_TASK_LOG_START_STOP_TIME 0x0001U<<(2)
#define UV_TASK_LOG_MEM_USAGE 0x0001U<<(3)
#define UV_TASK_SCD_IGNORE 0x0001U<<(4)
#define UV_TASK_IS_PARENT 0x0001U<<(5)
#define UV_TASK_IS_CHILD 0x0001U<<(6)
#define UV_TASK_IS_ORPHAN 0x0001U<<(7)
#define UV_TASK_ERR_IN_CHILD 0x0001U<<(8)
#define UV_TASK_AWAITING_DELETION 0x0001U<<(9)
#define UV_TASK_DEFER_DELETION 0x0001U<<(10)
#define UV_TASK_DEADLINE_NOT_ENFORCED 0x00
#define UV_TASK_PRIO_INCREMENTATION 0x0001U<<(11)
#define UV_TASK_DEADLINE_FIRM 0x0001U<<(12)
#define UV_TASK_DEADLINE_HARD (0x0001U<<(11)|0x0001U<<(12))
#define UV_TASK_DEADLINE_MASK (0x0001U<<(11)|0x0001U<<(12))
#define UV_TASK_MISSION_CRITICAL 0x0001U<<(13)
#define UV_TASK_DELAYING 0x0001U<<(14)
#define uvTaskSetDeletionBit(t)
#define uvTaskResetDeletionBit(t)
#define uvTaskSetDelayBit(t)
#define uvTaskResetDelayBit(t)
#define uvTaskIsDelaying(t)
#define uvTaskDelay(x, t)
State engine aware vTaskDelay wrapper.
#define uvTaskDelayUntil(x, lasttim, per)
State engine aware vTaskDelayUntil wrapper.
Typedefs
typedef enum uv_vehicle_state_t uv_vehicle_state
Type representing the overall state and operating mode of the vehicle.
typedef enum uv_task_cmd_e uv_task_cmd
Special commands used to start and shutdown tasks.
typedef struct uv_scd_response uv_scd_response
typedef enum uv_task_state_t uv_task_status
Enum representing the state of a managed task.
typedef enum task_priority task_priority
Priority of a managed task. Maps directly to OS priority.
typedef struct task_management_info task_management_info
Struct to contain data about a parent task.
typedef struct task_status_block task_status_block
Information about the task.
typedef struct uv_os_settings uv_os_settings
Settings that dictate state engine behavior.
typedef struct uv_task_info uv_task_info
This struct is designed to hold neccessary information about an RTOS task that will be managed by uvfr_state_engine.
Enumerations
enum uv_vehicle_state_t {
UV_INIT = 0x0001
, UV_READY = 0x0002
, PROGRAMMING = 0x0004
, UV_DRIVING = 0x0008
,
UV_SUSPENDED = 0x0010
, UV_LAUNCH_CONTROL = 0x0020
, UV_ERROR_STATE = 0x0040
, UV_BOOT = 0x0080
,
UV_HALT = 0x0100
 }
Type representing the overall state and operating mode of the vehicle.
enum uv_task_cmd_e { UV_NO_CMD
, UV_KILL_CMD
, UV_SUSPEND_CMD
, UV_TASK_START_CMD
 }
Special commands used to start and shutdown tasks.
enum uv_scd_response_e {
UV_SUCCESSFUL_DELETION
, UV_SUCCESSFUL_SUSPENSION
, UV_COULDNT_DELETE
, UV_COULDNT_SUSPEND
,
UV_UNSAFE_STATE
 }
Response from a task confirming it has been either deleted or suspended.
enum uv_task_state_t { UV_TASK_NOT_STARTED
, UV_TASK_DELETED
, UV_TASK_RUNNING
, UV_TASK_SUSPENDED
 }
Enum representing the state of a managed task.
enum task_priority {
IDLE_TASK_PRIORITY
, LOW_PRIORITY
, BELOW_NORMAL
, MEDIUM_PRIORITY
,
ABOVE_NORMAL
, HIGH_PRIORITY
, REALTIME_PRIORITY
 }
Priority of a managed task. Maps directly to OS priority.
enum os_flag { UV_OS_LOG_MEM = 0x01
, UV_OS_LOG_TASK_END_TIME = 0x02
, UV_OS_ATTEMPT_RESTART_NC_TASK = 0x04
, UV_OS_ENABLE_NONCRIT_TASK_THROTTLE = 0x08
 }
Functions
void uvTaskPeriodEnd (uv_task_info *t)
Function called at the end of the task period.
uv_status changeVehicleState (uint16_t state)
Function for changing the state of the vehicle, as well as the list of active + inactive tasks.
uv_status initRTDtask (void *args)
uv_status uvInitStateEngine ()
Function that prepares the state engine to do its thing.
void uvCrashIntoWall ()
uv_status uvStartStateMachine ()
Actually starts up the state engine to do state engine things.
uv_status uvDeInitStateEngine ()
Stops and frees all resources used by uvfr_state_engine.
uv_task_info * uvCreateTask ()
This function gets called when you want to create a task, and register it with the task register. Theres some gnarlyness here, but not unacceptable levels. Pray this thing doesn't hang itself.
Detailed Description
Provides publically available API for controlling vehicle state and error handling.
The functions defined in this group are publicly accessible and can be called from either application or service tasks. These are not neccessarily interrupt safe, and therefore should not be called from them, unless they end with FromISR
Macro Definition Documentation
UV_TASK_AWAITING_DELETION
#define UV_TASK_AWAITING_DELETION 0x0001U<<(9)
Definition at line 211 of file uvfr_state_engine.h.
Referenced by _stateChangeDaemon(), and uvScheduleTaskDeletion().
UV_TASK_DEADLINE_FIRM
#define UV_TASK_DEADLINE_FIRM 0x0001U<<(12)
Definition at line 215 of file uvfr_state_engine.h.
UV_TASK_DEADLINE_HARD
#define UV_TASK_DEADLINE_HARD (0x0001U<<(11)|0x0001U<<(12))
Definition at line 216 of file uvfr_state_engine.h.
UV_TASK_DEADLINE_MASK
#define UV_TASK_DEADLINE_MASK (0x0001U<<(11)|0x0001U<<(12))
Definition at line 217 of file uvfr_state_engine.h.
UV_TASK_DEADLINE_NOT_ENFORCED
#define UV_TASK_DEADLINE_NOT_ENFORCED 0x00
Definition at line 213 of file uvfr_state_engine.h.
UV_TASK_DEFER_DELETION
#define UV_TASK_DEFER_DELETION 0x0001U<<(10)
Definition at line 212 of file uvfr_state_engine.h.
Referenced by _stateChangeDaemon().
UV_TASK_DELAYING
#define UV_TASK_DELAYING 0x0001U<<(14)
Definition at line 219 of file uvfr_state_engine.h.
UV_TASK_DORMANT_SVC
#define UV_TASK_DORMANT_SVC 0b0000000000000011
Definition at line 201 of file uvfr_state_engine.h.
UV_TASK_ERR_IN_CHILD
#define UV_TASK_ERR_IN_CHILD 0x0001U<<(8)
Definition at line 210 of file uvfr_state_engine.h.
UV_TASK_GENERIC_SVC
#define UV_TASK_GENERIC_SVC 0x0001U<<(2)
Definition at line 202 of file uvfr_state_engine.h.
Referenced by uvCreateServiceTask(), and uvStartSVCTask().
UV_TASK_IS_CHILD
#define UV_TASK_IS_CHILD 0x0001U<<(6)
Definition at line 208 of file uvfr_state_engine.h.
UV_TASK_IS_ORPHAN
#define UV_TASK_IS_ORPHAN 0x0001U<<(7)
Definition at line 209 of file uvfr_state_engine.h.
UV_TASK_IS_PARENT
#define UV_TASK_IS_PARENT 0x0001U<<(5)
Definition at line 207 of file uvfr_state_engine.h.
UV_TASK_LOG_MEM_USAGE
#define UV_TASK_LOG_MEM_USAGE 0x0001U<<(3)
Definition at line 205 of file uvfr_state_engine.h.
UV_TASK_LOG_START_STOP_TIME
#define UV_TASK_LOG_START_STOP_TIME 0x0001U<<(2)
Definition at line 204 of file uvfr_state_engine.h.
UV_TASK_MANAGER_MASK
#define UV_TASK_MANAGER_MASK 0b0000000000000011
Definition at line 203 of file uvfr_state_engine.h.
Referenced by uvTaskManager().
UV_TASK_MISSION_CRITICAL
#define UV_TASK_MISSION_CRITICAL 0x0001U<<(13)
Definition at line 218 of file uvfr_state_engine.h.
Referenced by uvLateTaskHandler(), uvStartStateMachine(), uvTaskCrashHandler(), and uvTaskManager().
UV_TASK_PERIODIC_SVC
#define UV_TASK_PERIODIC_SVC 0x0001U<<(1)
Definition at line 200 of file uvfr_state_engine.h.
UV_TASK_PRIO_INCREMENTATION
#define UV_TASK_PRIO_INCREMENTATION 0x0001U<<(11)
Definition at line 214 of file uvfr_state_engine.h.
UV_TASK_SCD_IGNORE
#define UV_TASK_SCD_IGNORE 0x0001U<<(4)
Definition at line 206 of file uvfr_state_engine.h.
Referenced by uvCreateServiceTask(), and uvStartStateMachine().
UV_TASK_VEHICLE_APPLICATION
#define UV_TASK_VEHICLE_APPLICATION 0x0001U<<(0)
Definition at line 199 of file uvfr_state_engine.h.
Referenced by uvCreateTask(), and uvTaskManager().
uvTaskDelay
#define uvTaskDelay(x, t)
Value:
    uvTaskSetDelayBit(x);\
    vTaskDelay(t);\
    uvTaskResetDelayBit(x)
State engine aware vTaskDelay wrapper.
Parameters
x
t is how long to delay in ticks
Definition at line 295 of file uvfr_state_engine.h.
Referenced by daqMasterTask().
uvTaskDelayUntil
#define uvTaskDelayUntil(x, lasttim, per)
Value:
    uvTaskSetDelayBit(x);\
    vTaskDelayUntil(&lasttim,per);\
    uvTaskResetDelayBit(x)
State engine aware vTaskDelayUntil wrapper.
Parameters
x
lasttim is the variable storing the last delay time.
per is the period.
This will cause the task to wait until the last time + the period.
Definition at line 316 of file uvfr_state_engine.h.
Referenced by tempMonitorTask().
uvTaskIsDelaying
#define uvTaskIsDelaying(t)
Value:
((t->task_flags&UV_TASK_DELAYING)==UV_TASK_DELAYING)
Definition at line 288 of file uvfr_state_engine.h.
Referenced by uvDeleteTask(), and uvSuspendTask().
uvTaskResetDelayBit
#define uvTaskResetDelayBit(t)
Value:
(t->task_flags&=(~UV_TASK_DELAYING))
Definition at line 286 of file uvfr_state_engine.h.
Referenced by uvTaskPeriodEnd().
uvTaskResetDeletionBit
#define uvTaskResetDeletionBit(t)
Value:
(t->task_flags &=(~UV_TASK_AWAITING_DELETION))
Definition at line 282 of file uvfr_state_engine.h.
uvTaskSetDelayBit
#define uvTaskSetDelayBit(t)
Value:
(t->task_flags|=UV_TASK_DELAYING)
Definition at line 284 of file uvfr_state_engine.h.
Referenced by uvTaskPeriodEnd().
uvTaskSetDeletionBit
#define uvTaskSetDeletionBit(t)
Value:
(t->task_flags|=UV_TASK_AWAITING_DELETION)
Definition at line 281 of file uvfr_state_engine.h.
Typedef Documentation
task_management_info
typedef struct task_management_info task_management_info
Struct to contain data about a parent task.
This contains the information required for the child task to communicate with it's parent.
This will be a queue, since one parent task can in theory have several child tasks
task_priority
typedef enum task_priority task_priority
Priority of a managed task. Maps directly to OS priority.
task_status_block
typedef struct task_status_block task_status_block
Information about the task.
uv_os_settings
typedef struct uv_os_settings uv_os_settings
Settings that dictate state engine behavior.
uv_scd_response
typedef struct uv_scd_response uv_scd_response
uv_task_cmd
typedef enum uv_task_cmd_e uv_task_cmd
Special commands used to start and shutdown tasks.
Definition at line 141 of file uvfr_utils.h.
uv_task_info
typedef struct uv_task_info uv_task_info
This struct is designed to hold neccessary information about an RTOS task that will be managed by uvfr_state_engine.
Pay close attention, because this is one of the most cursed structs in the project, as well as one of the most important
uv_task_status
typedef enum uv_task_state_t uv_task_status
Enum representing the state of a managed task.
This is used as a flag to indicate whether or not the state_engine is aware of a task is running or not.
uv_vehicle_state
typedef enum uv_vehicle_state_t uv_vehicle_state
Type representing the overall state and operating mode of the vehicle.
Type made to represent the state of the vehicle, and the location in the state machine The states are powers of two to make it easier to discern tasks that need to happen in multiple states
Enumeration Type Documentation
os_flag
enum os_flag
Enumerator
UV_OS_LOG_MEM
UV_OS_LOG_TASK_END_TIME
UV_OS_ATTEMPT_RESTART_NC_TASK
UV_OS_ENABLE_NONCRIT_TASK_THROTTLE
Definition at line 174 of file uvfr_state_engine.h.
task_priority
enum task_priority
Priority of a managed task. Maps directly to OS priority.
Enumerator
IDLE_TASK_PRIORITY
LOW_PRIORITY
BELOW_NORMAL
MEDIUM_PRIORITY
ABOVE_NORMAL
HIGH_PRIORITY
REALTIME_PRIORITY
Definition at line 142 of file uvfr_state_engine.h.
uv_scd_response_e
enum uv_scd_response_e
Response from a task confirming it has been either deleted or suspended.
Enumerator
UV_SUCCESSFUL_DELETION Returned when a task was successfully deleted
UV_SUCCESSFUL_SUSPENSION Returned when a task is successfully suspended
UV_COULDNT_DELETE Task was not successfully deleted
UV_COULDNT_SUSPEND Task was not successfully suspended
UV_UNSAFE_STATE Task has ended up in a fucked middle ground state
Definition at line 113 of file uvfr_state_engine.h.
uv_task_cmd_e
enum uv_task_cmd_e
Special commands used to start and shutdown tasks.
Enumerator
UV_NO_CMD The SCD has issued no command, and therefore no action is required
UV_KILL_CMD The SCD has decreed that this task must be deleted
UV_SUSPEND_CMD The SCD has decreed that this task must be suspended
UV_TASK_START_CMD OK for task to begin execution
Definition at line 103 of file uvfr_state_engine.h.
uv_task_state_t
enum uv_task_state_t
Enum representing the state of a managed task.
This is used as a flag to indicate whether or not the state_engine is aware of a task is running or not.
Enumerator
UV_TASK_NOT_STARTED
UV_TASK_DELETED
UV_TASK_RUNNING
UV_TASK_SUSPENDED
Definition at line 131 of file uvfr_state_engine.h.
uv_vehicle_state_t
enum uv_vehicle_state_t
Type representing the overall state and operating mode of the vehicle.
Type made to represent the state of the vehicle, and the location in the state machine The states are powers of two to make it easier to discern tasks that need to happen in multiple states
Enumerator
UV_INIT Vehicle is in the process of initializing
UV_READY Vehicle has initialized and is ready to drive
PROGRAMMING The settings of the vehicle are being edited now
UV_DRIVING The vehicle is actively driving
UV_SUSPENDED The vehicle is not allowed to produce any torque, but not full shutdown
UV_LAUNCH_CONTROL The vehicle is presently in launch control mode
UV_ERROR_STATE Some error has occurred here
UV_BOOT Pre-init, when the boot loader is going
UV_HALT Stop literally everything, except for what is needed to reset vehicle
Definition at line 88 of file uvfr_state_engine.h.
Function Documentation
changeVehicleState()
uv_status changeVehicleState (uint16_t state)
Function for changing the state of the vehicle, as well as the list of active + inactive tasks.
This function also changes out the tasks that are executing, by invoking the legendary _state_change_daemon
Parameters
state is a member of uv_status, and therefore a power of two
Return values
returns a memeber of uv_status depending on whether execution is successful
Example usage:
if((brakepedal_pressed == true) && (start_button_pressed == true)){
    changeVehicleState(UV_DRIVING);
}
As you can see, all you need to do is specify the new state. Naturally, the task should be ready to get deleted by the state_change_daemon, but that is neither here nor there. If the state we wish to change to is the same as the state we're in, then no need to be executing any of this fancy code
Transition from UV_INIT to UV_READY states
Transition from UV_INIT to UV_ERROR states
Definition at line 92 of file uvfr_state_engine.c.
References _stateChangeDaemon(), isPowerOfTwo, state_change_daemon_args::meta_task_handle, previous_state, UV_ABORTED, UV_ERROR, UV_ERROR_STATE, UV_INIT, UV_OK, UV_READY, and vehicle_state.
Referenced by __uvPanic(), handleDiagnosticMsg(), handleIncomingLaptopMsg(), rtdTask(), testfunc(), uvInit(), and uvSettingsProgrammerTask().
initRTDtask()
uv_status initRTDtask (void * args)
Definition at line 12 of file ready_to_drive.c.
References uv_task_info::active_states, uv_task_info::deletion_states, PROGRAMMING, rtdTask(), uv_task_info::stack_size, uv_task_info::suspension_states, uv_task_info::task_args, uv_task_info::task_function, uv_task_info::task_name, uv_task_info::task_period, uv_task_info::task_priority, UV_DRIVING, UV_ERROR, UV_ERROR_STATE, UV_OK, UV_READY, and uvCreateTask().
Referenced by uvInitStateEngine().
uvCrashIntoWall()
void uvCrashIntoWall ()
Definition at line 204 of file uvfr_state_engine.c.
uvCreateTask()
uv_task_info * uvCreateTask ()
This function gets called when you want to create a task, and register it with the task register. Theres some gnarlyness here, but not unacceptable levels. Pray this thing doesn't hang itself.
Do not exceed the number of tasks available
Acquire the pointer to the spot in the array, we are doing this since we need to return the pointer anyways, and it cleans up the syntax a little.
Definition at line 285 of file uvfr_state_engine.c.
References _UV_DEFAULT_TASK_STACK_SIZE, uv_task_info::active_states, uv_task_info::deletion_states, MAX_NUM_MANAGED_TASKS, uv_task_info::parent, uv_task_info::stack_size, uv_task_info::suspension_states, uv_task_info::task_flags, uv_task_info::task_function, uv_task_info::task_handle, uv_task_info::task_id, uv_task_info::task_name, uv_task_info::task_priority, uv_task_info::task_state, UV_TASK_NOT_STARTED, and UV_TASK_VEHICLE_APPLICATION.
Referenced by initDaqTask(), initDrivingLoop(), initOdometer(), initRTDtask(), initTempMonitor(), and uvConfigSettingTask().
uvDeInitStateEngine()
uv_status uvDeInitStateEngine ()
Stops and frees all resources used by uvfr_state_engine.
If we need to initialize the state engine, gotta de-initialize as well. This is the opposite of uvInitStateEngine
Definition at line 275 of file uvfr_state_engine.c.
References killEmAll().
uvInitStateEngine()
uv_status uvInitStateEngine ()
Function that prepares the state engine to do its thing.
This is called when the system is first starting up.
Definition at line 168 of file uvfr_state_engine.c.
References __uvInitPanic(), associateDaqParamWithVar(), initDaqTask(), initDrivingLoop(), initOdometer(), initRTDtask(), initTempMonitor(), MAX_NUM_MANAGED_TASKS, OS_AVAILABLE_HEAP, OS_LARGEST_FREE_BLOCK, OS_MIN_EVER_FREE_BYTES, OS_NUM_FREE_BLOCKS, OS_NUM_SUCCESSFUL_ALLOCS, OS_NUM_SUCCESSFUL_FREES, OS_SMALLEST_FREE_BLOCK, svc_task_manager, task_manager, UV_OK, uvConfigSettingTask(), uvCreateServiceTask(), VCU_VEHICLE_STATE, vehicle_state, and xHeapStats.
Referenced by uvInit().
uvStartStateMachine()
uv_status uvStartStateMachine ()
Actually starts up the state engine to do state engine things.
This function ensures that all of the managed tasks are setup in a legal way, and then it allocates resources for, and starts the state engine and the background tasks. This unlocks the ability for the vehicle to do basically anything.
Definition at line 213 of file uvfr_state_engine.c.
References current_vehicle_settings, os_settings, uv_vehicle_settings::os_settings, previous_state, uv_task_info::stack_size, svc_task_manager, uv_task_info::task_flags, uv_task_info::task_function, task_manager, uv_task_info::task_name, uv_task_info::task_period, UV_ERROR, UV_INIT, UV_OK, UV_TASK_MISSION_CRITICAL, UV_TASK_SCD_IGNORE, uvSVCTaskManager(), uvTaskManager(), uvValidateManagedTasks(), and vehicle_state.
Referenced by uvInit().
uvTaskPeriodEnd()
void uvTaskPeriodEnd (uv_task_info * t)
Function called at the end of the task period.
@
Definition at line 1469 of file uvfr_state_engine.c.
References uv_task_info::last_execution_time, uv_task_info::task_id, uv_task_info::task_period, task_tardiness, uvTaskResetDelayBit, and uvTaskSetDelayBit.
Referenced by uvTaskManager().