Core/Src/imd.c File Reference
#include "imd.h"
#include "can.h"
#include "main.h"
#include "constants.h"
#include "uvfr_utils.h"
#include "pdu.h"
Functions
void IMD_Parse_Message (int DLC, uint8_t Data[])
void IMD_Request_Status (uint8_t Status)
void IMD_Check_Status_Bits (uint8_t Data)
void IMD_Check_Error_Flags (uint8_t Data[])
void IMD_Check_Isolation_State (uint8_t Data[])
void IMD_Check_Isolation_Resistances (uint8_t Data[])
void IMD_Check_Isolation_Capacitances (uint8_t Data[])
void IMD_Check_Voltages_Vp_and_Vn (uint8_t Data[])
void IMD_Check_Battery_Voltage (uint8_t Data[])
void IMD_Check_Temperature (uint8_t Data[])
void IMD_Check_Safety_Touch_Energy (uint8_t Data[])
void IMD_Check_Safety_Touch_Current (uint8_t Data[])
void IMD_Check_Max_Battery_Working_Voltage (uint8_t Data[])
void IMD_Check_Part_Name (uint8_t Data[])
void IMD_Check_Version (uint8_t Data[])
void IMD_Check_Serial_Number (uint8_t Data[])
void IMD_Check_Uptime (uint8_t Data[])
void IMD_Startup ()
void initIMD (void *args)
Variables
uint8_t IMD_status_bits = 0
uint8_t IMD_High_Uncertainty = 0
uint32_t IMD_Read_Part_Name [4]
const uint32_t IMD_Expected_Part_Name [4]
uint8_t IMD_Part_Name_0_Set = 0
uint8_t IMD_Part_Name_1_Set = 0
uint8_t IMD_Part_Name_2_Set = 0
uint8_t IMD_Part_Name_3_Set = 0
uint8_t IMD_Part_Name_Set = 0
uint32_t IMD_Read_Version [3]
const uint32_t IMD_Expected_Version [3]
uint8_t IMD_Version_0_Set = 0
uint8_t IMD_Version_1_Set = 0
uint8_t IMD_Version_2_Set = 0
uint8_t IMD_Version_Set = 0
uint32_t IMD_Read_Serial_Number [4]
const uint32_t IMD_Expected_Serial_Number [4]
uint8_t IMD_Serial_Number_0_Set = 0
uint8_t IMD_Serial_Number_1_Set = 0
uint8_t IMD_Serial_Number_2_Set = 0
uint8_t IMD_Serial_Number_3_Set = 0
uint8_t IMD_Serial_Number_Set = 0
int32_t IMD_Temperature
uint8_t IMD_error_flags_requested = 0
uv_imd_settings default_imd_settings
Function Documentation
IMD_Check_Battery_Voltage()
void IMD_Check_Battery_Voltage (uint8_t Data[])
Definition at line 356 of file imd.c.
Referenced by IMD_Parse_Message().
IMD_Check_Error_Flags()
void IMD_Check_Error_Flags (uint8_t Data[])
Definition at line 262 of file imd.c.
References Err_CH, Err_clock, Err_temp, Err_Vexi, Err_Vpwr, Err_Vx1, Err_Vx2, Err_VxR, and Err_Watchdog.
Referenced by IMD_Parse_Message().
IMD_Check_Isolation_Capacitances()
void IMD_Check_Isolation_Capacitances (uint8_t Data[])
Definition at line 342 of file imd.c.
Referenced by IMD_Parse_Message().
IMD_Check_Isolation_Resistances()
void IMD_Check_Isolation_Resistances (uint8_t Data[])
Definition at line 317 of file imd.c.
References IMD_High_Uncertainty.
Referenced by IMD_Parse_Message().
IMD_Check_Isolation_State()
void IMD_Check_Isolation_State (uint8_t Data[])
Definition at line 301 of file imd.c.
References IMD_High_Uncertainty.
Referenced by IMD_Parse_Message().
IMD_Check_Max_Battery_Working_Voltage()
void IMD_Check_Max_Battery_Working_Voltage (uint8_t Data[])
Definition at line 393 of file imd.c.
Referenced by IMD_Parse_Message().
IMD_Check_Part_Name()
void IMD_Check_Part_Name (uint8_t Data[])
Definition at line 406 of file imd.c.
References IMD_Expected_Part_Name, IMD_Part_Name_0_Set, IMD_Part_Name_1_Set, IMD_Part_Name_2_Set, IMD_Part_Name_3_Set, IMD_Part_Name_Set, IMD_Read_Part_Name, Part_name_0, Part_name_1, Part_name_2, and Part_name_3.
Referenced by IMD_Parse_Message().
IMD_Check_Safety_Touch_Current()
void IMD_Check_Safety_Touch_Current (uint8_t Data[])
Definition at line 381 of file imd.c.
Referenced by IMD_Parse_Message().
IMD_Check_Safety_Touch_Energy()
void IMD_Check_Safety_Touch_Energy (uint8_t Data[])
Definition at line 374 of file imd.c.
Referenced by IMD_Parse_Message().
IMD_Check_Serial_Number()
void IMD_Check_Serial_Number (uint8_t Data[])
Definition at line 488 of file imd.c.
References IMD_Expected_Serial_Number, IMD_Read_Serial_Number, IMD_Serial_Number_0_Set, IMD_Serial_Number_1_Set, IMD_Serial_Number_2_Set, IMD_Serial_Number_3_Set, IMD_Serial_Number_Set, Serial_number_0, Serial_number_1, Serial_number_2, and Serial_number_3.
Referenced by IMD_Parse_Message().
IMD_Check_Status_Bits()
void IMD_Check_Status_Bits (uint8_t Data)
Definition at line 218 of file imd.c.
References Error_flags, Hardware_Error, High_Battery_Voltage, High_Uncertainty, IMD_error_flags_requested, IMD_High_Uncertainty, IMD_Request_Status(), Isolation_status_bit0, Isolation_status_bit1, and Low_Battery_Voltage.
Referenced by IMD_Parse_Message().
IMD_Check_Temperature()
void IMD_Check_Temperature (uint8_t Data[])
Definition at line 363 of file imd.c.
References IMD_Temperature.
Referenced by IMD_Parse_Message().
IMD_Check_Uptime()
void IMD_Check_Uptime (uint8_t Data[])
Definition at line 529 of file imd.c.
IMD_Check_Version()
void IMD_Check_Version (uint8_t Data[])
Definition at line 448 of file imd.c.
References IMD_Expected_Version, IMD_Read_Version, IMD_Version_0_Set, IMD_Version_1_Set, IMD_Version_2_Set, IMD_Version_Set, Version_0, Version_1, and Version_2.
Referenced by IMD_Parse_Message().
IMD_Check_Voltages_Vp_and_Vn()
void IMD_Check_Voltages_Vp_and_Vn (uint8_t Data[])
Definition at line 349 of file imd.c.
Referenced by IMD_Parse_Message().
IMD_Parse_Message()
void IMD_Parse_Message (int DLC, uint8_t Data[])
Definition at line 73 of file imd.c.
References battery_voltage, Error_flags, Error_Handler(), IMD_Check_Battery_Voltage(), IMD_Check_Error_Flags(), IMD_Check_Isolation_Capacitances(), IMD_Check_Isolation_Resistances(), IMD_Check_Isolation_State(), IMD_Check_Max_Battery_Working_Voltage(), IMD_Check_Part_Name(), IMD_Check_Safety_Touch_Current(), IMD_Check_Safety_Touch_Energy(), IMD_Check_Serial_Number(), IMD_Check_Status_Bits(), IMD_Check_Temperature(), IMD_Check_Version(), IMD_Check_Voltages_Vp_and_Vn(), isolation_capacitances, isolation_resistances, isolation_state, Max_battery_working_voltage, Part_name_0, Part_name_1, Part_name_2, Part_name_3, safety_touch_current, safety_touch_energy, Serial_number_0, Serial_number_1, Serial_number_2, Serial_number_3, Temperature, Uptime_counter, Vb_hi_res, Version_0, Version_1, Version_2, Vexc_hi_res, Vn_hi_res, voltages_Vp_and_Vn, Vp_hi_res, and Vpwr_hi_res.
IMD_Request_Status()
void IMD_Request_Status (uint8_t Status)
Definition at line 185 of file imd.c.
References Error_Handler(), hcan2, IMD_CAN_ID_Tx, TxData, TxHeader, and TxMailbox.
Referenced by IMD_Check_Status_Bits(), and IMD_Startup().
IMD_Startup()
void IMD_Startup ()
Definition at line 533 of file imd.c.
References IMD_Request_Status(), isolation_state, Max_battery_working_voltage, Part_name_0, Part_name_1, Part_name_2, Part_name_3, Serial_number_0, Serial_number_1, Serial_number_2, Serial_number_3, Version_0, Version_1, and Version_2.
initIMD()
void initIMD (void * args)
Definition at line 559 of file imd.c.
References IMD, uv_init_task_args::init_info_queue, uv_init_task_args::meta_task_handle, pdPASS, UV_OK, vTaskDelay(), vTaskSuspend(), and xQueueSendToBack.
Referenced by uvInit().
Variable Documentation
default_imd_settings
uv_imd_settings default_imd_settings
Initial value:
= {
    .min_isolation_resistances = 10000,
    .expected_isolation_capacitances = 100,
    .max_imd_temperature = 60
}
Definition at line 65 of file imd.c.
Referenced by uvResetFlashToDefault().
IMD_error_flags_requested
uint8_t IMD_error_flags_requested = 0
Definition at line 62 of file imd.c.
Referenced by IMD_Check_Status_Bits().
IMD_Expected_Part_Name
const uint32_t IMD_Expected_Part_Name[4]
Definition at line 26 of file imd.c.
Referenced by IMD_Check_Part_Name().
IMD_Expected_Serial_Number
const uint32_t IMD_Expected_Serial_Number[4]
Initial value:
= {0xB8DD9AF9,
                                                0x6094F48B,
                                                0x1F1C3794,
                                                0xFCF9A95B}
Definition at line 46 of file imd.c.
Referenced by IMD_Check_Serial_Number().
IMD_Expected_Version
const uint32_t IMD_Expected_Version[3]
Definition at line 36 of file imd.c.
Referenced by IMD_Check_Version().
IMD_High_Uncertainty
uint8_t IMD_High_Uncertainty = 0
Definition at line 20 of file imd.c.
Referenced by IMD_Check_Isolation_Resistances(), IMD_Check_Isolation_State(), and IMD_Check_Status_Bits().
IMD_Part_Name_0_Set
uint8_t IMD_Part_Name_0_Set = 0
Definition at line 28 of file imd.c.
Referenced by IMD_Check_Part_Name().
IMD_Part_Name_1_Set
uint8_t IMD_Part_Name_1_Set = 0
Definition at line 29 of file imd.c.
Referenced by IMD_Check_Part_Name().
IMD_Part_Name_2_Set
uint8_t IMD_Part_Name_2_Set = 0
Definition at line 30 of file imd.c.
Referenced by IMD_Check_Part_Name().
IMD_Part_Name_3_Set
uint8_t IMD_Part_Name_3_Set = 0
Definition at line 31 of file imd.c.
Referenced by IMD_Check_Part_Name().
IMD_Part_Name_Set
uint8_t IMD_Part_Name_Set = 0
Definition at line 32 of file imd.c.
Referenced by IMD_Check_Part_Name().
IMD_Read_Part_Name
uint32_t IMD_Read_Part_Name[4]
Definition at line 25 of file imd.c.
Referenced by IMD_Check_Part_Name().
IMD_Read_Serial_Number
uint32_t IMD_Read_Serial_Number[4]
Definition at line 45 of file imd.c.
Referenced by IMD_Check_Serial_Number().
IMD_Read_Version
uint32_t IMD_Read_Version[3]
Definition at line 35 of file imd.c.
Referenced by IMD_Check_Version().
IMD_Serial_Number_0_Set
uint8_t IMD_Serial_Number_0_Set = 0
Definition at line 50 of file imd.c.
Referenced by IMD_Check_Serial_Number().
IMD_Serial_Number_1_Set
uint8_t IMD_Serial_Number_1_Set = 0
Definition at line 51 of file imd.c.
Referenced by IMD_Check_Serial_Number().
IMD_Serial_Number_2_Set
uint8_t IMD_Serial_Number_2_Set = 0
Definition at line 52 of file imd.c.
Referenced by IMD_Check_Serial_Number().
IMD_Serial_Number_3_Set
uint8_t IMD_Serial_Number_3_Set = 0
Definition at line 53 of file imd.c.
Referenced by IMD_Check_Serial_Number().
IMD_Serial_Number_Set
uint8_t IMD_Serial_Number_Set = 0
Definition at line 54 of file imd.c.
Referenced by IMD_Check_Serial_Number().
IMD_status_bits
uint8_t IMD_status_bits = 0
Definition at line 19 of file imd.c.
IMD_Temperature
int32_t IMD_Temperature
Definition at line 57 of file imd.c.
Referenced by IMD_Check_Temperature().
IMD_Version_0_Set
uint8_t IMD_Version_0_Set = 0
Definition at line 38 of file imd.c.
Referenced by IMD_Check_Version().
IMD_Version_1_Set
uint8_t IMD_Version_1_Set = 0
Definition at line 39 of file imd.c.
Referenced by IMD_Check_Version().
IMD_Version_2_Set
uint8_t IMD_Version_2_Set = 0
Definition at line 40 of file imd.c.
Referenced by IMD_Check_Version().
IMD_Version_Set
uint8_t IMD_Version_Set = 0
Definition at line 41 of file imd.c.
Referenced by IMD_Check_Version().