Core/Inc/imd.h File Reference
#include "main.h"
Data Structures
struct uv_imd_settings
Typedefs
typedef struct uv_imd_settings uv_imd_settings
Enumerations
enum imd_status_bits {
Isolation_status_bit0 = 0b00000001
, Isolation_status_bit1 = 0b00000010
, Low_Battery_Voltage = 0b00000100
, High_Battery_Voltage = 0b00001000
,
Exc_off = 0b00010000
, High_Uncertainty = 0b00100000
, Touch_energy_fault = 0b01000000
, Hardware_Error = 0b10000000
 }
enum imd_status_requests {
isolation_state = 0xE0
, isolation_resistances = 0xE1
, isolation_capacitances = 0xE2
, voltages_Vp_and_Vn = 0xE3
,
battery_voltage = 0xE4
, Error_flags = 0xE5
, safety_touch_energy = 0xE6
, safety_touch_current = 0xE7
,
Max_battery_working_voltage = 0xF0
, Temperature = 0x80
 }
enum imd_error_flags {
Err_temp = 0x0080
, Err_clock = 0x0100
, Err_Watchdog = 0x0200
, Err_Vpwr = 0x0400
,
Err_Vexi = 0x0800
, Err_VxR = 0x1000
, Err_CH = 0x2000
, Err_Vx1 = 0x4000
,
Err_Vx2 = 0x8000
 }
enum imd_manufacturer_requests {
Part_name_0 = 0x01
, Part_name_1 = 0x02
, Part_name_2 = 0x03
, Part_name_3 = 0x04
,
Version_0 = 0x05
, Version_1 = 0x06
, Version_2 = 0x07
, Serial_number_0 = 0x08
,
Serial_number_1 = 0x09
, Serial_number_2 = 0x0A
, Serial_number_3 = 0x0B
, Uptime_counter = 0x0C
 }
enum imd_high_resolution_measurements {
Vn_hi_res = 0x60
, Vp_hi_res = 0x61
, Vexc_hi_res = 0x62
, Vb_hi_res = 0x63
,
Vpwr_hi_res = 0x65
 }
Functions
void IMD_Parse_Message (int DLC, uint8_t Data[])
void IMD_Check_Status_Bits (uint8_t Data)
void IMD_Check_Error_Flags (uint8_t Data[])
void IMD_Check_Isolation_State (uint8_t Data[])
void IMD_Check_Isolation_Resistances (uint8_t Data[])
void IMD_Check_Isolation_Capacitances (uint8_t Data[])
void IMD_Check_Voltages_Vp_and_Vn (uint8_t Data[])
void IMD_Check_Battery_Voltage (uint8_t Data[])
void IMD_Check_Safety_Touch_Energy (uint8_t Data[])
void IMD_Check_Safety_Touch_Current (uint8_t Data[])
void IMD_Check_Temperature (uint8_t Data[])
void IMD_Check_Max_Battery_Working_Voltage (uint8_t Data[])
void IMD_Check_Part_Name (uint8_t Data[])
void IMD_Check_Version (uint8_t Data[])
void IMD_Check_Serial_Number (uint8_t Data[])
void IMD_Check_Uptime (uint8_t Data[])
void IMD_Request_Status (uint8_t Status)
void IMD_Startup ()
void initIMD (void *args)
Typedef Documentation
uv_imd_settings
typedef struct uv_imd_settings uv_imd_settings
Enumeration Type Documentation
imd_error_flags
enum imd_error_flags
Enumerator
Err_temp
Err_clock
Err_Watchdog
Err_Vpwr
Err_Vexi
Err_VxR
Err_CH
Err_Vx1
Err_Vx2
Definition at line 75 of file imd.h.
imd_high_resolution_measurements
enum imd_high_resolution_measurements
Enumerator
Vn_hi_res
Vp_hi_res
Vexc_hi_res
Vb_hi_res
Vpwr_hi_res
Definition at line 105 of file imd.h.
imd_manufacturer_requests
enum imd_manufacturer_requests
Enumerator
Part_name_0
Part_name_1
Part_name_2
Part_name_3
Version_0
Version_1
Version_2
Serial_number_0
Serial_number_1
Serial_number_2
Serial_number_3
Uptime_counter
Definition at line 89 of file imd.h.
imd_status_bits
enum imd_status_bits
Enumerator
Isolation_status_bit0
Isolation_status_bit1
Low_Battery_Voltage
High_Battery_Voltage
Exc_off
High_Uncertainty
Touch_energy_fault
Hardware_Error
Definition at line 16 of file imd.h.
imd_status_requests
enum imd_status_requests
Enumerator
isolation_state
isolation_resistances
isolation_capacitances
voltages_Vp_and_Vn
battery_voltage
Error_flags
safety_touch_energy
safety_touch_current
Max_battery_working_voltage
Temperature
Definition at line 39 of file imd.h.
Function Documentation
IMD_Check_Battery_Voltage()
void IMD_Check_Battery_Voltage (uint8_t Data[])
Definition at line 356 of file imd.c.
Referenced by IMD_Parse_Message().
IMD_Check_Error_Flags()
void IMD_Check_Error_Flags (uint8_t Data[])
Definition at line 262 of file imd.c.
References Err_CH, Err_clock, Err_temp, Err_Vexi, Err_Vpwr, Err_Vx1, Err_Vx2, Err_VxR, and Err_Watchdog.
Referenced by IMD_Parse_Message().
IMD_Check_Isolation_Capacitances()
void IMD_Check_Isolation_Capacitances (uint8_t Data[])
Definition at line 342 of file imd.c.
Referenced by IMD_Parse_Message().
IMD_Check_Isolation_Resistances()
void IMD_Check_Isolation_Resistances (uint8_t Data[])
Definition at line 317 of file imd.c.
References IMD_High_Uncertainty.
Referenced by IMD_Parse_Message().
IMD_Check_Isolation_State()
void IMD_Check_Isolation_State (uint8_t Data[])
Definition at line 301 of file imd.c.
References IMD_High_Uncertainty.
Referenced by IMD_Parse_Message().
IMD_Check_Max_Battery_Working_Voltage()
void IMD_Check_Max_Battery_Working_Voltage (uint8_t Data[])
Definition at line 393 of file imd.c.
Referenced by IMD_Parse_Message().
IMD_Check_Part_Name()
void IMD_Check_Part_Name (uint8_t Data[])
Definition at line 406 of file imd.c.
References IMD_Expected_Part_Name, IMD_Part_Name_0_Set, IMD_Part_Name_1_Set, IMD_Part_Name_2_Set, IMD_Part_Name_3_Set, IMD_Part_Name_Set, IMD_Read_Part_Name, Part_name_0, Part_name_1, Part_name_2, and Part_name_3.
Referenced by IMD_Parse_Message().
IMD_Check_Safety_Touch_Current()
void IMD_Check_Safety_Touch_Current (uint8_t Data[])
Definition at line 381 of file imd.c.
Referenced by IMD_Parse_Message().
IMD_Check_Safety_Touch_Energy()
void IMD_Check_Safety_Touch_Energy (uint8_t Data[])
Definition at line 374 of file imd.c.
Referenced by IMD_Parse_Message().
IMD_Check_Serial_Number()
void IMD_Check_Serial_Number (uint8_t Data[])
Definition at line 488 of file imd.c.
References IMD_Expected_Serial_Number, IMD_Read_Serial_Number, IMD_Serial_Number_0_Set, IMD_Serial_Number_1_Set, IMD_Serial_Number_2_Set, IMD_Serial_Number_3_Set, IMD_Serial_Number_Set, Serial_number_0, Serial_number_1, Serial_number_2, and Serial_number_3.
Referenced by IMD_Parse_Message().
IMD_Check_Status_Bits()
void IMD_Check_Status_Bits (uint8_t Data)
Definition at line 218 of file imd.c.
References Error_flags, Hardware_Error, High_Battery_Voltage, High_Uncertainty, IMD_error_flags_requested, IMD_High_Uncertainty, IMD_Request_Status(), Isolation_status_bit0, Isolation_status_bit1, and Low_Battery_Voltage.
Referenced by IMD_Parse_Message().
IMD_Check_Temperature()
void IMD_Check_Temperature (uint8_t Data[])
Definition at line 363 of file imd.c.
References IMD_Temperature.
Referenced by IMD_Parse_Message().
IMD_Check_Uptime()
void IMD_Check_Uptime (uint8_t Data[])
Definition at line 529 of file imd.c.
IMD_Check_Version()
void IMD_Check_Version (uint8_t Data[])
Definition at line 448 of file imd.c.
References IMD_Expected_Version, IMD_Read_Version, IMD_Version_0_Set, IMD_Version_1_Set, IMD_Version_2_Set, IMD_Version_Set, Version_0, Version_1, and Version_2.
Referenced by IMD_Parse_Message().
IMD_Check_Voltages_Vp_and_Vn()
void IMD_Check_Voltages_Vp_and_Vn (uint8_t Data[])
Definition at line 349 of file imd.c.
Referenced by IMD_Parse_Message().
IMD_Parse_Message()
void IMD_Parse_Message (int DLC, uint8_t Data[])
Definition at line 73 of file imd.c.
References battery_voltage, Error_flags, Error_Handler(), IMD_Check_Battery_Voltage(), IMD_Check_Error_Flags(), IMD_Check_Isolation_Capacitances(), IMD_Check_Isolation_Resistances(), IMD_Check_Isolation_State(), IMD_Check_Max_Battery_Working_Voltage(), IMD_Check_Part_Name(), IMD_Check_Safety_Touch_Current(), IMD_Check_Safety_Touch_Energy(), IMD_Check_Serial_Number(), IMD_Check_Status_Bits(), IMD_Check_Temperature(), IMD_Check_Version(), IMD_Check_Voltages_Vp_and_Vn(), isolation_capacitances, isolation_resistances, isolation_state, Max_battery_working_voltage, Part_name_0, Part_name_1, Part_name_2, Part_name_3, safety_touch_current, safety_touch_energy, Serial_number_0, Serial_number_1, Serial_number_2, Serial_number_3, Temperature, Uptime_counter, Vb_hi_res, Version_0, Version_1, Version_2, Vexc_hi_res, Vn_hi_res, voltages_Vp_and_Vn, Vp_hi_res, and Vpwr_hi_res.
IMD_Request_Status()
void IMD_Request_Status (uint8_t Status)
Definition at line 185 of file imd.c.
References Error_Handler(), hcan2, IMD_CAN_ID_Tx, TxData, TxHeader, and TxMailbox.
Referenced by IMD_Check_Status_Bits(), and IMD_Startup().
IMD_Startup()
void IMD_Startup ()
Definition at line 533 of file imd.c.
References IMD_Request_Status(), isolation_state, Max_battery_working_voltage, Part_name_0, Part_name_1, Part_name_2, Part_name_3, Serial_number_0, Serial_number_1, Serial_number_2, Serial_number_3, Version_0, Version_1, and Version_2.
initIMD()
void initIMD (void * args)
Definition at line 559 of file imd.c.
References IMD, uv_init_task_args::init_info_queue, uv_init_task_args::meta_task_handle, pdPASS, UV_OK, vTaskDelay(), vTaskSuspend(), and xQueueSendToBack.
Referenced by uvInit().