Core/Src/main.c File Reference
: Main program body
#include "main.h"
#include "adc.h"
#include "can.h"
#include "dma.h"
#include "tim.h"
#include "gpio.h"
#include "constants.h"
#include "bms.h"
#include "dash.h"
#include "imd.h"
#include "motor_controller.h"
#include "pdu.h"
#include "../FreeRTOS/Source/CMSIS_RTOS/cmsis_os.h"
Macros
#define __UV_FILENAME__ "main.c"
#define MAIN_C
#define DEBUG_CAN_IN_MAIN 0
Functions
void SystemClock_Config (void)
System Clock Configuration.
int main (void)
The application entry point.
void HAL_ADC_ConvCpltCallback (ADC_HandleTypeDef *hadc)
void HAL_GPIO_EXTI_Callback (uint16_t GPIO_Pin)
void HAL_ADC_LevelOutOfWindowCallback (ADC_HandleTypeDef *hadc)
void HAL_TIM_PeriodElapsedCallback (TIM_HandleTypeDef *htim)
Period elapsed callback in non blocking mode.
void Error_Handler (void)
This function is executed in case of error occurrence.
Variables
volatile uint32_t adc_buf1 [5]
uint16_t adc1_APPS1
uint16_t adc1_APPS2
uint16_t adc1_BPS1
uint16_t adc1_BPS2
uint16_t adc1_pack_curr
volatile uint32_t adc_buf2 [7]
uint16_t adc2_CoolantTemp1
uint16_t adc2_CoolantTemp2
uint16_t adc2_CoolantFlow
uint16_t adc2_steering_pos
volatile uint32_t adc_buf3 [4]
uint16_t adc3_damper_FL
uint16_t adc3_damper_FR
uint16_t adc3_damper_RL
uint16_t adc3_damper_RR
TaskHandle_t init_task_handle
uv_init_struct init_settings
Detailed Description
: Main program body
Attention
Copyright (c) 2023 STMicroelectronics. All rights reserved.
This software is licensed under terms that can be found in the LICENSE file in the root directory of this software component. If no LICENSE file comes with this software, it is provided AS-IS.
Definition in file main.c.
Macro Definition Documentation
__UV_FILENAME__
#define __UV_FILENAME__ "main.c"
Definition at line 19 of file main.c.
DEBUG_CAN_IN_MAIN
#define DEBUG_CAN_IN_MAIN 0
Definition at line 54 of file main.c.
MAIN_C
#define MAIN_C
Definition at line 20 of file main.c.
Function Documentation
Error_Handler()
void Error_Handler (void)
This function is executed in case of error occurrence.
Return values
None
Definition at line 365 of file main.c.
Referenced by HAL_ADC_MspInit(), HAL_CAN_RxFifo0MsgPendingCallback(), HAL_CAN_RxFifo1MsgPendingCallback(), IMD_Parse_Message(), IMD_Request_Status(), initADCTask(), MX_ADC1_Init(), MX_ADC2_Init(), MX_ADC3_Init(), MX_CAN1_Init(), MX_CAN2_Init(), MX_TIM11_Init(), MX_TIM3_Init(), SystemClock_Config(), Update_Batt_Temp(), Update_RPM(), and Update_State_Of_Charge().
HAL_ADC_ConvCpltCallback()
void HAL_ADC_ConvCpltCallback (ADC_HandleTypeDef * hadc)
Definition at line 295 of file main.c.
References hadc1, hadc2, hadc3, and processADCBuffer().
HAL_ADC_LevelOutOfWindowCallback()
void HAL_ADC_LevelOutOfWindowCallback (ADC_HandleTypeDef * hadc)
Definition at line 317 of file main.c.
References adc1_APPS1, adc1_APPS2, and hadc1.
HAL_GPIO_EXTI_Callback()
void HAL_GPIO_EXTI_Callback (uint16_t GPIO_Pin)
Definition at line 308 of file main.c.
HAL_TIM_PeriodElapsedCallback()
void HAL_TIM_PeriodElapsedCallback (TIM_HandleTypeDef * htim)
Period elapsed callback in non blocking mode.
Note
This function is called when TIM1 interrupt took place, inside HAL_TIM_IRQHandler(). It makes a direct call to HAL_IncTick() to increment a global variable "uwTick" used as application time base.
Parameters
htim : TIM handle
Return values
None
Definition at line 341 of file main.c.
References htim3.
main()
int main (void)
The application entry point.
Return values
int
Definition at line 111 of file main.c.
References adc1_APPS1, adc1_APPS2, handleCANbusError(), hcan2, init_settings, init_task_handle, MX_ADC1_Init(), MX_ADC2_Init(), MX_ADC3_Init(), MX_CAN1_Init(), MX_CAN2_Init(), MX_DMA_Init(), MX_GPIO_Init(), MX_TIM11_Init(), MX_TIM3_Init(), SystemClock_Config(), SystemCoreClock, TxData, TxHeader, TxMailbox, Update_RPM(), uvAssert, and uvInit().
SystemClock_Config()
void SystemClock_Config (void)
System Clock Configuration.
Configure the main internal regulator output voltage
Initializes the RCC Oscillators according to the specified parameters in the RCC_OscInitTypeDef structure.
Initializes the CPU, AHB and APB buses clocks
Definition at line 236 of file main.c.
References Error_Handler().
Referenced by main().
Variable Documentation
adc1_APPS1
uint16_t adc1_APPS1
Definition at line 67 of file main.c.
Referenced by HAL_ADC_LevelOutOfWindowCallback(), initDrivingLoop(), main(), processADCBuffer(), and StartDrivingLoop().
adc1_APPS2
uint16_t adc1_APPS2
Definition at line 68 of file main.c.
Referenced by HAL_ADC_LevelOutOfWindowCallback(), initDrivingLoop(), main(), processADCBuffer(), and StartDrivingLoop().
adc1_BPS1
uint16_t adc1_BPS1
Definition at line 69 of file main.c.
Referenced by initDrivingLoop(), processADCBuffer(), and StartDrivingLoop().
adc1_BPS2
uint16_t adc1_BPS2
Definition at line 70 of file main.c.
Referenced by initDrivingLoop(), processADCBuffer(), and StartDrivingLoop().
adc1_pack_curr
uint16_t adc1_pack_curr
Definition at line 71 of file main.c.
Referenced by processADCBuffer().
adc2_CoolantFlow
uint16_t adc2_CoolantFlow
Definition at line 76 of file main.c.
Referenced by processADCBuffer().
adc2_CoolantTemp1
uint16_t adc2_CoolantTemp1
Definition at line 74 of file main.c.
Referenced by processADCBuffer().
adc2_CoolantTemp2
uint16_t adc2_CoolantTemp2
Definition at line 75 of file main.c.
Referenced by processADCBuffer().
adc2_steering_pos
uint16_t adc2_steering_pos
Definition at line 77 of file main.c.
Referenced by processADCBuffer().
adc3_damper_FL
uint16_t adc3_damper_FL
Definition at line 80 of file main.c.
Referenced by processADCBuffer().
adc3_damper_FR
uint16_t adc3_damper_FR
Definition at line 81 of file main.c.
Referenced by processADCBuffer().
adc3_damper_RL
uint16_t adc3_damper_RL
Definition at line 82 of file main.c.
Referenced by processADCBuffer().
adc3_damper_RR
uint16_t adc3_damper_RR
Definition at line 83 of file main.c.
Referenced by processADCBuffer().
adc_buf1
volatile uint32_t adc_buf1[5]
Definition at line 65 of file main.c.
Referenced by processADCBuffer(), and StartADCTask().
adc_buf2
volatile uint32_t adc_buf2[7]
Definition at line 73 of file main.c.
Referenced by processADCBuffer(), and StartADCTask().
adc_buf3
volatile uint32_t adc_buf3[4]
Definition at line 79 of file main.c.
Referenced by processADCBuffer(), and StartADCTask().
init_settings
uv_init_struct init_settings
Definition at line 86 of file main.c.
Referenced by main().
init_task_handle
TaskHandle_t init_task_handle
Definition at line 85 of file main.c.
Referenced by main(), and uvInit().