Core/Inc/motor_controller.h File Reference
#include "main.h"
#include "freeRTOS.h"
#include "uvfr_utils.h"
#include "uvfr_settings.h"
#include "can.h"
Macros
#define SERIAL_NUMBER_REGISTER 0x62
#define FIRMWARE_VERSION_REGISTER 0x1B
#define N_set_cmd N_set
Typedefs
typedef struct motor_controller_settings motor_controller_settings
Enumerations
enum motor_controller_speed_parameters {
N_actual = 0x30
, N_set = 0x31
, M_set = 0x90
, N_cmd = 0x32
,
N_error = 0x33
, M_out = 0xA0
 }
enum motor_controller_status { LOGIMAP_ERRORS = 0x82
, LOGIMAP_IO = 0x83
, POS_ACTUAL = 0x86
 }
enum motor_controller_current_parameters { CURRENT_ACTUAL = 0x69
 }
enum motor_controller_motor_constants {
nominal_motor_frequency = 0x05
, nominal_motor_voltage = 0x06
, power_factor = 0x0E
, motor_max_current = 0x4D
,
motor_continuous_current = 0x4E
, motor_pole_number = 0x4F
, motor_kt_constant = 0x87
, motor_ke_constant = 0x87
,
rated_motor_speed = 0x59
, motor_temperature_switch_off_point = 0xA3
, stator_leakage_inductance = 0xB1
, nominal_magnitizing_current = 0xB2
,
motor_magnetising_inductance = 0xB3
, rotor_resistance = 0xB4
, minimum_magnetising_current = 0xB5
, time_constant_rotor = 0xB6
,
leakage_inductance_ph_ph = 0xBB
, stator_resistance_ph_ph = 0xBC
, time_constant_stator = 0xBD
 }
enum motor_controller_temperatures {
igbt_temperature = 0x4A
, max_motor_temp = 0xA3
, warning_motor_temp = 0xA2
, motor_temperature = 0x49
,
air_temperature = 0x4B
, current_derate_temperature = 0x4C
, temp_sensor_pt1 = 0x9C
, temp_sensor_pt2 = 0x9D
,
temp_sensor_pt3 = 0x9E
, temp_sensor_pt4 = 0x9F
 }
enum motor_controller_measurements { DC_bus_voltage = 0xEB
 }
enum motor_controller_status_information_errors_warnings {
motor_controller_errors_warnings = 0x8F
, eprom_read_error = 1 << 8
, hardware_fault = 1 << 9
, rotate_field_enable_not_present_run = 1 << 10
,
CAN_timeout_error = 1 << 11
, feedback_signal_error = 1 << 12
, mains_voltage_min_limit = 1 << 13
, motor_temp_max_limit = 1 << 14
,
IGBT_temp_max_limit = 1 << 15
, mains_voltage_max_limit = 1
, critical_AC_current = 1 << 1
, race_away_detected = 1 << 2
,
ecode_timeout_error = 1 << 3
, watchdog_reset = 1 << 4
, AC_current_offset_fault = 1 << 5
, internal_hardware_voltage_problem = 1 << 6
,
bleed_resistor_overload = 1 << 7
, parameter_conflict_detected = 1 << 8
, special_CPU_fault = 1 << 9
, rotate_field_enable_not_present_norun = 1 << 10
,
auxiliary_voltage_min_limit = 1 << 11
, feedback_signal_problem = 1 << 12
, warning_5 = 1 << 13
, motor_temperature_warning = 1 << 14
,
IGBT_temperature_warning = 1 << 15
, Vout_saturation_max_limit = 1
, warning_9 = 1 << 1
, speed_actual_resolution_limit = 1 << 2
,
check_ecode_ID = 1 << 3
, tripzone_glitch_detected = 1 << 4
, ADC_sequencer_problem = 1 << 5
, ADC_measurement_problem = 1 << 6
,
bleeder_resistor_warning = 1 << 7
 }
enum motor_controller_io { todo6969 = 6969
 }
enum motor_controller_PI_values {
accelerate_ramp = 0x35
, dismantling_ramp = 0xED
, recuperation_ramp = 0xC7
, proportional_gain = 0x1C
,
integral_time_constant = 0x1D
, integral_memory_max = 0x2B
, proportional_gain_2 = 0xC9
, current_feed_forward = 0xCB
,
ramp_set_current = 0x25
 }
enum motor_controller_repeating_time { none = 0
, one_hundred_ms = 0x64
 }
enum motor_controller_limp_mode { N_lim = 0x34
, N_lim_plus = 0x3F
, N_lim_minus = 0x3E
 }
enum motor_controller_startup { clear_errors = 0x8E
, firmware_version = 0x1B
 }
Functions
void MC_Startup (void *args)
Initializes the motor controller.
uint16_t sendTorqueToMotorController (float T_filtered)
Sends a filtered torque command to the motor controller over CAN.
void MC_Request_Data (uint8_t RegID)
Sends a CAN request to retrieve a specific register from the motor controller.
void ProcessMotorControllerResponse (uv_CAN_msg *msg)
Processes a CAN response from the motor controller.
void Parse_Bamocar_Response (uv_CAN_msg *msg)
Parses a 32-bit value from a CAN message in little-endian format.
void MC_Shutdown (void)
Safely shuts down the motor controller.
Variables
int16_t mc_speed_rpm
int16_t mc_current
int16_t mc_torque_cmd
int16_t mc_motor_temp
int16_t mc_igbt_temp
TickType_t last_driver_input_time
motor_controller_settings mc_default_settings
Macro Definition Documentation
FIRMWARE_VERSION_REGISTER
#define FIRMWARE_VERSION_REGISTER 0x1B
Definition at line 177 of file motor_controller.h.
Referenced by MC_Startup().
N_set_cmd
#define N_set_cmd N_set
Definition at line 181 of file motor_controller.h.
SERIAL_NUMBER_REGISTER
#define SERIAL_NUMBER_REGISTER 0x62
Definition at line 176 of file motor_controller.h.
Referenced by MC_Startup().
Typedef Documentation
motor_controller_settings
typedef struct motor_controller_settings motor_controller_settings
Definition at line 10 of file motor_controller.h.
Enumeration Type Documentation
motor_controller_current_parameters
enum motor_controller_current_parameters
Enumerator
CURRENT_ACTUAL
Definition at line 45 of file motor_controller.h.
motor_controller_io
enum motor_controller_io
Enumerator
todo6969
Definition at line 136 of file motor_controller.h.
motor_controller_limp_mode
enum motor_controller_limp_mode
Enumerator
N_lim
N_lim_plus
N_lim_minus
Definition at line 160 of file motor_controller.h.
motor_controller_measurements
enum motor_controller_measurements
Enumerator
DC_bus_voltage
Definition at line 89 of file motor_controller.h.
motor_controller_motor_constants
enum motor_controller_motor_constants
Enumerator
nominal_motor_frequency
nominal_motor_voltage
power_factor
motor_max_current
motor_continuous_current
motor_pole_number
motor_kt_constant
motor_ke_constant
rated_motor_speed
motor_temperature_switch_off_point
stator_leakage_inductance
nominal_magnitizing_current
motor_magnetising_inductance
rotor_resistance
minimum_magnetising_current
time_constant_rotor
leakage_inductance_ph_ph
stator_resistance_ph_ph
time_constant_stator
Definition at line 50 of file motor_controller.h.
motor_controller_PI_values
enum motor_controller_PI_values
Enumerator
accelerate_ramp
dismantling_ramp
recuperation_ramp
proportional_gain
integral_time_constant
integral_memory_max
proportional_gain_2
current_feed_forward
ramp_set_current
Definition at line 141 of file motor_controller.h.
motor_controller_repeating_time
enum motor_controller_repeating_time
Enumerator
none
one_hundred_ms
Definition at line 154 of file motor_controller.h.
motor_controller_speed_parameters
enum motor_controller_speed_parameters
Enumerator
N_actual
N_set
M_set
N_cmd
N_error
M_out
Definition at line 26 of file motor_controller.h.
motor_controller_startup
enum motor_controller_startup
Enumerator
clear_errors
firmware_version
Definition at line 167 of file motor_controller.h.
motor_controller_status
enum motor_controller_status
Enumerator
LOGIMAP_ERRORS
LOGIMAP_IO
POS_ACTUAL
Definition at line 37 of file motor_controller.h.
motor_controller_status_information_errors_warnings
enum motor_controller_status_information_errors_warnings
Enumerator
motor_controller_errors_warnings
eprom_read_error
hardware_fault
rotate_field_enable_not_present_run
CAN_timeout_error
feedback_signal_error
mains_voltage_min_limit
motor_temp_max_limit
IGBT_temp_max_limit
mains_voltage_max_limit
critical_AC_current
race_away_detected
ecode_timeout_error
watchdog_reset
AC_current_offset_fault
internal_hardware_voltage_problem
bleed_resistor_overload
parameter_conflict_detected
special_CPU_fault
rotate_field_enable_not_present_norun
auxiliary_voltage_min_limit
feedback_signal_problem
warning_5
motor_temperature_warning
IGBT_temperature_warning
Vout_saturation_max_limit
warning_9
speed_actual_resolution_limit
check_ecode_ID
tripzone_glitch_detected
ADC_sequencer_problem
ADC_measurement_problem
bleeder_resistor_warning
Definition at line 94 of file motor_controller.h.
motor_controller_temperatures
enum motor_controller_temperatures
Enumerator
igbt_temperature
max_motor_temp
warning_motor_temp
motor_temperature
air_temperature
current_derate_temperature
temp_sensor_pt1
temp_sensor_pt2
temp_sensor_pt3
temp_sensor_pt4
Definition at line 73 of file motor_controller.h.
Function Documentation
MC_Request_Data()
void MC_Request_Data (uint8_t RegID)
Sends a CAN request to retrieve a specific register from the motor controller.
The request message is formatted as: [0x3D, RegID, 0], which should trigger an immediate reply.
Definition at line 110 of file motor_controller.c.
References uv_CAN_msg::data, uv_CAN_msg::dlc, uv_CAN_msg::flags, mc_settings, uv_CAN_msg::msg_id, UV_OK, and uvSendCanMSG().
Referenced by MC_SetAndVerify_Param(), MC_Shutdown(), and MC_Startup().
MC_Shutdown()
void MC_Shutdown (void)
Safely shuts down the motor controller.
This function stops all periodic CAN feedback, zeroes the torque or speed command (depending on control mode), disables the motor controller, and optionally requests the error/warning register for post-shutdown diagnostics.
It ensures the controller is left in a known, safe state after driving stops. Use this before powering down or transitioning to an inactive state.
Definition at line 548 of file motor_controller.c.
References MC_EnableCyclicSpeedTransmission(), MC_Request_Data(), MC_Set_Param(), and motor_controller_errors_warnings.
Referenced by performSafetyChecks(), and uvSecureVehicle().
MC_Startup()
void MC_Startup (void * args)
Initializes the motor controller.
This function performs all necessary startup steps to prepare the Bamocar motor controller for operation. It is typically called during system initialization from uvfr_utils.c.
The routine performs the following actions:
Toggles a GPIO pin for debug indication
Registers a CAN RX handler for controller responses
Enables cyclic transmission of critical feedback parameters
Sends initialization commands (based on Bamocar Example 11)
Requests metadata (serial number, firmware version)
Optionally sets and verifies controller parameters
Sends status to the system init queue
Suspends itself after completion
Parameters
args Pointer to uv_init_task_args, used to send back init status.
Definition at line 458 of file motor_controller.c.
References uv_init_task_response::device, FIRMWARE_VERSION_REGISTER, uv_init_task_args::init_info_queue, insertCANMessageHandler(), MC_EnableCyclicSpeedTransmission(), MC_Request_Data(), MC_Set_Param(), mc_settings, MOTOR_CONTROLLER, ProcessMotorControllerResponse(), SERIAL_NUMBER_REGISTER, uv_init_task_response::status, and UV_OK.
Referenced by uvInit().
Parse_Bamocar_Response()
void Parse_Bamocar_Response (uv_CAN_msg * msg)
Parses a 32-bit value from a CAN message in little-endian format.
This example assumes that the data bytes are stored as: data[0] = LSB, data[3] = MSB.
Definition at line 221 of file motor_controller.c.
References uv_CAN_msg::data, and uv_CAN_msg::dlc.
ProcessMotorControllerResponse()
void ProcessMotorControllerResponse (uv_CAN_msg * msg)
Processes a CAN response from the motor controller.
This function decodes a received CAN message by examining the register ID in the first byte (data[0]) and handling the response accordingly.
It performs little-endian parsing to extract values for speed, current, torque, temperatures, and error flags. Critical errors will trigger uvPanic() via the error handler.
The full message is also stored in a global buffer (last_mc_response) for later access and verification routines.
Parameters
msg Pointer to the received CAN message from the motor controller.
Definition at line 324 of file motor_controller.c.
References CURRENT_ACTUAL, uv_CAN_msg::data, uv_CAN_msg::dlc, igbt_temperature, last_mc_response, LOGIMAP_ERRORS, LOGIMAP_IO, M_out, mc_current, mc_igbt_temp, mc_motor_temp, mc_speed_rpm, mc_torque_cmd, motor_controller_errors_warnings, motor_temperature, N_actual, and POS_ACTUAL.
Referenced by MC_Startup().
sendTorqueToMotorController()
uint16_t sendTorqueToMotorController (float T_filtered)
Sends a filtered torque command to the motor controller over CAN.
This function scales the input torque (in Nm) to the Bamocar's expected format, clamps it within the valid operating range, and transmits it as a direct torque command using the N_set register. The final 16-bit value is sent via CAN using the configured transmit ID.
Parameters
T_filtered The final torque value in Nm after filtering (typically 0230 Nm).
Returns
0 if successful, 1 if transmission failed.
Definition at line 69 of file motor_controller.c.
References uv_CAN_msg::data, uv_CAN_msg::dlc, uv_CAN_msg::flags, mc_settings, uv_CAN_msg::msg_id, N_set, UV_OK, and uvSendCanMSG().
Referenced by StartDrivingLoop().
Variable Documentation
last_driver_input_time
TickType_t last_driver_input_time [extern]
Definition at line 24 of file motor_controller.c.
Referenced by StartDrivingLoop().
mc_current
int16_t mc_current [extern]
Definition at line 28 of file motor_controller.c.
Referenced by ProcessMotorControllerResponse().
mc_default_settings
motor_controller_settings mc_default_settings [extern]
Definition at line 38 of file motor_controller.c.
mc_igbt_temp
int16_t mc_igbt_temp [extern]
Definition at line 31 of file motor_controller.c.
mc_motor_temp
int16_t mc_motor_temp [extern]
Definition at line 30 of file motor_controller.c.
mc_speed_rpm
int16_t mc_speed_rpm [extern]
Definition at line 27 of file motor_controller.c.
Referenced by ProcessMotorControllerResponse().
mc_torque_cmd
int16_t mc_torque_cmd [extern]
Definition at line 29 of file motor_controller.c.
Referenced by ProcessMotorControllerResponse().