Core/Src/motor_controller.c File Reference
#include "motor_controller.h"
#include "can.h"
#include "uvfr_utils.h"
#include <stdlib.h>
#include <string.h>
#include <stdio.h>
#include "uvfr_settings.h"
#include "cmsis_os.h"
Macros
#define mc_settings (current_vehicle_settings->mc_settings)
Functions
uint16_t sendTorqueToMotorController (float T_filtered)
Sends a filtered torque command to the motor controller over CAN.
void MC_Request_Data (uint8_t RegID)
Sends a CAN request to retrieve a specific register from the motor controller.
uv_status MC_Set_Param (uint8_t RegID, uint16_t d)
Sends a parameter write command to the motor controller.
uv_status MC_SetAndVerify_Param (uint8_t reg_id, uint16_t set_val)
Writes a value to a motor controller register and verifies the write.
void Parse_Bamocar_Response (uv_CAN_msg *msg)
Parses a 32-bit value from a CAN message in little-endian format.
void ProcessMotorControllerResponse (uv_CAN_msg *msg)
Processes a CAN response from the motor controller.
void MC_EnableCyclicSpeedTransmission (uint8_t interval_ms)
Enables or disables cyclic transmission of selected motor controller parameters.
void MC_Startup (void *args)
Initializes the motor controller.
void MC_Shutdown (void)
Safely shuts down the motor controller.
Variables
uv_vehicle_settings * current_vehicle_settings
QueueHandle_t CAN_Rx_Queue
uv_CAN_msg last_mc_response
TickType_t last_driver_input_time = 0
int16_t mc_speed_rpm = 0
int16_t mc_current = 0
int16_t mc_torque_cmd = 0
int16_t mc_motor_temp = 0
int16_t mc_igbt_temp = 0
motor_controller_settings mc_default_settings
Macro Definition Documentation
mc_settings
#define mc_settings (current_vehicle_settings->mc_settings)
Definition at line 16 of file motor_controller.c.
Referenced by MC_EnableCyclicSpeedTransmission(), MC_Request_Data(), MC_Set_Param(), MC_Startup(), and sendTorqueToMotorController().
Function Documentation
MC_EnableCyclicSpeedTransmission()
void MC_EnableCyclicSpeedTransmission (uint8_t interval_ms)
Enables or disables cyclic transmission of selected motor controller parameters.
Sends a series of CAN messages to configure the Bamocar controller to periodically transmit values such as speed, current, torque, temperatures, and error flags.
The message format is: [0x3D, RegID, interval_ms] Where interval_ms is the repeat interval in milliseconds (1–254). Passing 0xFF disables transmission for that register.
Parameters
interval_ms Transmission interval in milliseconds (1–254). Use 0xFF to disable.
Definition at line 407 of file motor_controller.c.
References CURRENT_ACTUAL, uv_CAN_msg::data, uv_CAN_msg::dlc, uv_CAN_msg::flags, igbt_temperature, LOGIMAP_ERRORS, M_out, max_motor_temp, mc_settings, motor_temperature, uv_CAN_msg::msg_id, N_actual, uvSendCanMSG(), and warning_motor_temp.
Referenced by MC_Shutdown(), and MC_Startup().
MC_Request_Data()
void MC_Request_Data (uint8_t RegID)
Sends a CAN request to retrieve a specific register from the motor controller.
The request message is formatted as: [0x3D, RegID, 0], which should trigger an immediate reply.
Definition at line 110 of file motor_controller.c.
References uv_CAN_msg::data, uv_CAN_msg::dlc, uv_CAN_msg::flags, mc_settings, uv_CAN_msg::msg_id, UV_OK, and uvSendCanMSG().
Referenced by MC_SetAndVerify_Param(), MC_Shutdown(), and MC_Startup().
MC_Set_Param()
uv_status MC_Set_Param (uint8_t RegID, uint16_t d)
Sends a parameter write command to the motor controller.
Constructs a 3-byte CAN message to set the value of a specific register on the motor controller. The message format is: [RegID, LSB(data), MSB(data), 0x00]
This function does not verify the result—use MC_SetAndVerify_Param() for value confirmation.
Parameters
RegID The register address to be written.
d The 16-bit value to write to the register.
Returns
UV_OK on success, UV_ERROR if the CAN transmission fails.
Definition at line 141 of file motor_controller.c.
References uv_CAN_msg::data, uv_CAN_msg::dlc, uv_CAN_msg::flags, mc_settings, uv_CAN_msg::msg_id, UV_ERROR, UV_OK, and uvSendCanMSG().
Referenced by MC_SetAndVerify_Param(), MC_Shutdown(), and MC_Startup().
MC_SetAndVerify_Param()
uv_status MC_SetAndVerify_Param (uint8_t reg_id, uint16_t set_val)
Writes a value to a motor controller register and verifies the write.
Sends a parameter set command to the specified register, then requests the value back and compares the response to ensure the write succeeded. Uses little-endian 16-bit parsing for verification.
This is a safer alternative to MC_Set_Param() when reliability is critical.
Parameters
reg_id The target register address to write.
set_val The 16-bit value to write to the register.
Returns
UV_OK if the write and verification succeeded, otherwise UV_ERROR.
Definition at line 175 of file motor_controller.c.
References uv_CAN_msg::data, last_mc_response, MC_Request_Data(), MC_Set_Param(), UV_ERROR, and UV_OK.
MC_Shutdown()
void MC_Shutdown (void)
Safely shuts down the motor controller.
This function stops all periodic CAN feedback, zeroes the torque or speed command (depending on control mode), disables the motor controller, and optionally requests the error/warning register for post-shutdown diagnostics.
It ensures the controller is left in a known, safe state after driving stops. Use this before powering down or transitioning to an inactive state.
Definition at line 548 of file motor_controller.c.
References MC_EnableCyclicSpeedTransmission(), MC_Request_Data(), MC_Set_Param(), and motor_controller_errors_warnings.
Referenced by performSafetyChecks(), and uvSecureVehicle().
MC_Startup()
void MC_Startup (void * args)
Initializes the motor controller.
This function performs all necessary startup steps to prepare the Bamocar motor controller for operation. It is typically called during system initialization from uvfr_utils.c.
The routine performs the following actions:
Toggles a GPIO pin for debug indication
Registers a CAN RX handler for controller responses
Enables cyclic transmission of critical feedback parameters
Sends initialization commands (based on Bamocar Example 11)
Requests metadata (serial number, firmware version)
Optionally sets and verifies controller parameters
Sends status to the system init queue
Suspends itself after completion
Parameters
args Pointer to uv_init_task_args, used to send back init status.
Definition at line 458 of file motor_controller.c.
References uv_init_task_response::device, FIRMWARE_VERSION_REGISTER, uv_init_task_args::init_info_queue, insertCANMessageHandler(), MC_EnableCyclicSpeedTransmission(), MC_Request_Data(), MC_Set_Param(), mc_settings, MOTOR_CONTROLLER, ProcessMotorControllerResponse(), SERIAL_NUMBER_REGISTER, uv_init_task_response::status, and UV_OK.
Referenced by uvInit().
Parse_Bamocar_Response()
void Parse_Bamocar_Response (uv_CAN_msg * msg)
Parses a 32-bit value from a CAN message in little-endian format.
This example assumes that the data bytes are stored as: data[0] = LSB, data[3] = MSB.
Definition at line 221 of file motor_controller.c.
References uv_CAN_msg::data, and uv_CAN_msg::dlc.
ProcessMotorControllerResponse()
void ProcessMotorControllerResponse (uv_CAN_msg * msg)
Processes a CAN response from the motor controller.
This function decodes a received CAN message by examining the register ID in the first byte (data[0]) and handling the response accordingly.
It performs little-endian parsing to extract values for speed, current, torque, temperatures, and error flags. Critical errors will trigger uvPanic() via the error handler.
The full message is also stored in a global buffer (last_mc_response) for later access and verification routines.
Parameters
msg Pointer to the received CAN message from the motor controller.
Definition at line 324 of file motor_controller.c.
References CURRENT_ACTUAL, uv_CAN_msg::data, uv_CAN_msg::dlc, igbt_temperature, last_mc_response, LOGIMAP_ERRORS, LOGIMAP_IO, M_out, mc_current, mc_igbt_temp, mc_motor_temp, mc_speed_rpm, mc_torque_cmd, motor_controller_errors_warnings, motor_temperature, N_actual, and POS_ACTUAL.
Referenced by MC_Startup().
sendTorqueToMotorController()
uint16_t sendTorqueToMotorController (float T_filtered)
Sends a filtered torque command to the motor controller over CAN.
This function scales the input torque (in Nm) to the Bamocar's expected format, clamps it within the valid operating range, and transmits it as a direct torque command using the N_set register. The final 16-bit value is sent via CAN using the configured transmit ID.
Parameters
T_filtered The final torque value in Nm after filtering (typically 0–230 Nm).
Returns
0 if successful, 1 if transmission failed.
Definition at line 69 of file motor_controller.c.
References uv_CAN_msg::data, uv_CAN_msg::dlc, uv_CAN_msg::flags, mc_settings, uv_CAN_msg::msg_id, N_set, UV_OK, and uvSendCanMSG().
Referenced by StartDrivingLoop().
Variable Documentation
CAN_Rx_Queue
QueueHandle_t CAN_Rx_Queue [extern]
current_vehicle_settings
uv_vehicle_settings* current_vehicle_settings [extern]
Definition at line 25 of file uvfr_settings.c.
Referenced by setupDefaultSettings(), uvLoadSettingsFromFlash(), and uvSettingsInit().
last_driver_input_time
TickType_t last_driver_input_time = 0
Definition at line 24 of file motor_controller.c.
Referenced by StartDrivingLoop().
last_mc_response
uv_CAN_msg last_mc_response
Definition at line 22 of file motor_controller.c.
Referenced by MC_SetAndVerify_Param(), and ProcessMotorControllerResponse().
mc_current
int16_t mc_current = 0
Definition at line 28 of file motor_controller.c.
Referenced by ProcessMotorControllerResponse().
mc_default_settings
motor_controller_settings mc_default_settings
Initial value:
= {
    .can_id_tx = 0x201,
    .can_id_rx = 0x181,
    .mc_CAN_timeout = 2,
    .proportional_gain = 10,
    .integral_time_constant = 400,
    .integral_memory_max = 60,
    
    .max_speed = 12357,
    .max_current = 13107,
    .cont_current = 7864,
    .max_torque = 32767,
    .max_motor_temp = 32767,
    .warning_motor_temp = 32767,
    .mc_bus = CAN_BUS_1
}
Definition at line 38 of file motor_controller.c.
Referenced by setupDefaultSettings(), and uvResetFlashToDefault().
mc_igbt_temp
int16_t mc_igbt_temp = 0
Definition at line 31 of file motor_controller.c.
Referenced by ProcessMotorControllerResponse().
mc_motor_temp
int16_t mc_motor_temp = 0
Definition at line 30 of file motor_controller.c.
Referenced by ProcessMotorControllerResponse().
mc_speed_rpm
int16_t mc_speed_rpm = 0
Definition at line 27 of file motor_controller.c.
Referenced by ProcessMotorControllerResponse().
mc_torque_cmd
int16_t mc_torque_cmd = 0
Definition at line 29 of file motor_controller.c.
Referenced by ProcessMotorControllerResponse().