Core/Inc/odometer.h File Reference
#include "uvfr_utils.h"
Data Structures
struct uv_persistant_data_frame
Typedefs
typedef struct uv_persistant_data_frame uv_persistant_data_frame
Functions
uv_status initOdometer (void *args)
void odometerTask (void *args)
, gotta know what the distance travelled is fam
Typedef Documentation
uv_persistant_data_frame
typedef struct uv_persistant_data_frame uv_persistant_data_frame
Function Documentation
initOdometer()
uv_status initOdometer (void * args)
Definition at line 11 of file odometer.c.
References _UV_DEFAULT_TASK_STACK_SIZE, uv_task_info::active_states, uv_task_info::deletion_states, odometerTask(), osPriorityNormal, PROGRAMMING, uv_task_info::stack_size, uv_task_info::suspension_states, uv_task_info::task_args, uv_task_info::task_function, uv_task_info::task_name, uv_task_info::task_period, uv_task_info::task_priority, UV_DRIVING, UV_ERROR, UV_ERROR_STATE, UV_LAUNCH_CONTROL, UV_OK, UV_READY, and uvCreateTask().
Referenced by uvInitStateEngine().
odometerTask()
void odometerTask (void * args)
, gotta know what the distance travelled is fam
These here lines set the delay. This task executes exactly at the period specified, regardless of how long the task execution actually takes
 */
TickType_t tick_period = pdMS_TO_TICKS(params->task_period); //Convert ms of period to the RTOS ticks
TickType_t last_time = xTaskGetTickCount();
    /**
Definition at line 46 of file odometer.c.
References uv_task_info::cmd_data, killSelf(), pdMS_TO_TICKS, suspendSelf(), uv_task_info::task_period, UV_KILL_CMD, UV_SUSPEND_CMD, vTaskDelayUntil(), and xTaskGetTickCount().
Referenced by initOdometer().