Core/Inc/pdu.h File Reference
#include "main.h"
#include "uvfr_utils.h"
Data Structures
struct uv19_pdu_settings
Typedefs
typedef struct abstract_conifer_channel abstract_conifer_channel
typedef struct uv19_pdu_settings uv19_pdu_settings
typedef enum u19_PDU_ch u19_PDU_ch
Enumerations
enum u19_PDU_ch {
U19_PDU_5A_1 = 0x00
, U19_PDU_5A_2 = 0x01
, U19_PDU_5A_3 = 0x02
, U19_PDU_5A_4 = 0x03
,
U19_PDU_5A_5 = 0x07
, U19_PDU_5A_6 = 0x06
, U19_PDU_5A_7 = 0x05
, U19_PDU_5A_8 = 0x04
,
U19_PDU_5A_9 = 0x0B
, U19_PDU_5A_10 = 0x0A
, U19_PDU_5A_11 = 0x09
, U19_PDU_5A_12 = 0x08
,
U19_PDU_5A_13 = 0x0C
, U19_PDU_5A_14 = 0x0D
, U19_PDU_5A_15 = 0x0E
, U19_PDU_5A_16 = 0x0F
,
U19_PDU_20A_1 = 0x23
, U19_PDU_20A_2 = 0x24
, U19_PDU_20A_3 = 0x21
, U19_PDU_20A_4 = 0x22
,
U19_PDU_20A_5 = 0x27
, U19_PDU_20A_6 = 0x28
, U19_PDU_20A_7 = 0x25
, U19_PDU_20A_8 = 0x26
 }
Functions
uv_status u19updatePduChannel (abstract_conifer_channel *ch_ptr, uint32_t *ecode)
uv_status initPDU (uint32_t *ecode)
Typedef Documentation
abstract_conifer_channel
typedef struct abstract_conifer_channel abstract_conifer_channel
Definition at line 9 of file pdu.h.
u19_PDU_ch
typedef enum u19_PDU_ch u19_PDU_ch
uv19_pdu_settings
typedef struct uv19_pdu_settings uv19_pdu_settings
Enumeration Type Documentation
u19_PDU_ch
enum u19_PDU_ch
Enumerator
U19_PDU_5A_1
U19_PDU_5A_2
U19_PDU_5A_3
U19_PDU_5A_4
U19_PDU_5A_5
U19_PDU_5A_6
U19_PDU_5A_7
U19_PDU_5A_8
U19_PDU_5A_9
U19_PDU_5A_10
U19_PDU_5A_11
U19_PDU_5A_12
U19_PDU_5A_13
U19_PDU_5A_14
U19_PDU_5A_15
U19_PDU_5A_16
U19_PDU_20A_1
U19_PDU_20A_2
U19_PDU_20A_3
U19_PDU_20A_4
U19_PDU_20A_5
U19_PDU_20A_6
U19_PDU_20A_7
U19_PDU_20A_8
Definition at line 22 of file pdu.h.
Function Documentation
initPDU()
uv_status initPDU (uint32_t * ecode)
Definition at line 100 of file pdu.c.
References CONIFER_DRV_INIT_ERR, conifer_params, uv_CAN_msg::flags, msg_to_PDU, pdu_tx_mutex, UV_ERROR, UV_OK, and vTaskDelay().
Referenced by coniferInit().
u19updatePduChannel()
uv_status u19updatePduChannel (abstract_conifer_channel * ch_ptr, uint32_t * ecode)
Definition at line 37 of file pdu.c.
References CONIFER_CH_EN_BIT, CONIFER_CH_FLT_BIT, CONIFER_CH_LS_ACTIVE, CONIFER_DRV_INVALID_HW_CH_ID, uv_CAN_msg::data, FIRST_20A_CH, abstract_conifer_channel::hardware_mapping, HIGHEST_CH, msg_to_PDU, pdTRUE, pdu_tx_mutex, set_20A_vals, set_5A_vals, abstract_conifer_channel::status_control_reg, U19_PDU_20A_BIT, U19_PDU_EN_BIT, UV_OK, uvSendCanMSG(), xSemaphoreGive, and xSemaphoreTake.
Referenced by coniferInit().