Core/Src/pdu.c File Reference
#include "pdu.h"
#include "uvfr_utils.h"
#include "can.h"
#include "main.h"
#include "constants.h"
Macros
#define U19_PDU_20A_BIT 0b00100000
#define U19_PDU_EN_BIT 0b00010000
Functions
uv_status u19updatePduChannel (struct abstract_conifer_channel *ch_ptr, uint32_t *ecode)
uv_status initPDU (uint32_t *ecode)
Variables
uint16_t read_5A_vals
uint16_t set_5A_vals
uint16_t read_20A_vals
uint16_t set_20A_vals
TickType_t pdu_last_Rx_time
uv_CAN_msg last_received_from_PDU
SemaphoreHandle_t pdu_tx_mutex = NULL
uv_CAN_msg msg_to_PDU
Macro Definition Documentation
U19_PDU_20A_BIT
#define U19_PDU_20A_BIT 0b00100000
Definition at line 31 of file pdu.c.
Referenced by u19updatePduChannel().
U19_PDU_EN_BIT
#define U19_PDU_EN_BIT 0b00010000
Definition at line 32 of file pdu.c.
Referenced by u19updatePduChannel().
Function Documentation
initPDU()
uv_status initPDU (uint32_t * ecode)
Definition at line 87 of file pdu.c.
References CONIFER_DRV_INIT_ERR, conifer_params, uv_CAN_msg::flags, msg_to_PDU, pdu_tx_mutex, UV_ERROR, UV_OK, and vTaskDelay().
Referenced by coniferInit().
u19updatePduChannel()
uv_status u19updatePduChannel (struct abstract_conifer_channel * ch_ptr, uint32_t * ecode)
Definition at line 35 of file pdu.c.
References CONIFER_CH_EN_BIT, CONIFER_DRV_INVALID_HW_CH_ID, uv_CAN_msg::data, abstract_conifer_channel::hardware_mapping, msg_to_PDU, pdTRUE, pdu_tx_mutex, set_20A_vals, set_5A_vals, abstract_conifer_channel::status_control_reg, U19_PDU_20A_1, U19_PDU_20A_8, U19_PDU_20A_BIT, U19_PDU_5A_16, U19_PDU_EN_BIT, UV_OK, uvSendCanMSG(), xSemaphoreGive, and xSemaphoreTake.
Referenced by coniferInit().
Variable Documentation
last_received_from_PDU
uv_CAN_msg last_received_from_PDU
Definition at line 19 of file pdu.c.
msg_to_PDU
uv_CAN_msg msg_to_PDU
Initial value:
= {
    .flags = 0x00,
    .dlc = 1,
    .msg_id = 0x710,
    .data = {0,0,0,0,0,0,0,0}
}
Definition at line 23 of file pdu.c.
Referenced by initPDU(), and u19updatePduChannel().
pdu_last_Rx_time
TickType_t pdu_last_Rx_time
Definition at line 18 of file pdu.c.
pdu_tx_mutex
SemaphoreHandle_t pdu_tx_mutex = NULL
Definition at line 21 of file pdu.c.
Referenced by initPDU(), and u19updatePduChannel().
read_20A_vals
uint16_t read_20A_vals
Definition at line 15 of file pdu.c.
read_5A_vals
uint16_t read_5A_vals
Definition at line 12 of file pdu.c.
set_20A_vals
uint16_t set_20A_vals
Definition at line 16 of file pdu.c.
Referenced by u19updatePduChannel().
set_5A_vals
uint16_t set_5A_vals
Definition at line 13 of file pdu.c.
Referenced by u19updatePduChannel().