Core/FreeRTOS/Source/include/portable.h File Reference
#include "deprecated_definitions.h"
#include "portmacro.h"
#include "mpu_wrappers.h"
Data Structures
struct HeapRegion
struct xHeapStats
Macros
#define portNUM_CONFIGURABLE_REGIONS 1
#define portHAS_STACK_OVERFLOW_CHECKING 0
#define portARCH_NAME NULL
Typedefs
typedef struct HeapRegion HeapRegion_t
typedef struct xHeapStats HeapStats_t
Functions
StackType_t * pxPortInitialiseStack (StackType_t *pxTopOfStack, TaskFunction_t pxCode, void *pvParameters) PRIVILEGED_FUNCTION
void vPortDefineHeapRegions (const HeapRegion_t *const pxHeapRegions) PRIVILEGED_FUNCTION
void vPortGetHeapStats (HeapStats_t *pxHeapStats)
void * pvPortMalloc (size_t xSize) PRIVILEGED_FUNCTION
void vPortFree (void *pv) PRIVILEGED_FUNCTION
void vPortInitialiseBlocks (void) PRIVILEGED_FUNCTION
size_t xPortGetFreeHeapSize (void) PRIVILEGED_FUNCTION
size_t xPortGetMinimumEverFreeHeapSize (void) PRIVILEGED_FUNCTION
BaseType_t xPortStartScheduler (void) PRIVILEGED_FUNCTION
void vPortEndScheduler (void) PRIVILEGED_FUNCTION
Macro Definition Documentation
portARCH_NAME
#define portARCH_NAME NULL
Definition at line 92 of file portable.h.
portHAS_STACK_OVERFLOW_CHECKING
#define portHAS_STACK_OVERFLOW_CHECKING 0
Definition at line 88 of file portable.h.
portNUM_CONFIGURABLE_REGIONS
#define portNUM_CONFIGURABLE_REGIONS 1
Definition at line 84 of file portable.h.
Typedef Documentation
HeapRegion_t
typedef struct HeapRegion HeapRegion_t
HeapStats_t
typedef struct xHeapStats HeapStats_t
Function Documentation
pvPortMalloc()
void * pvPortMalloc (size_t xSize)
Definition at line 115 of file heap_4.c.
References configASSERT, heapMINIMUM_BLOCK_SIZE, mtCOVERAGE_TEST_MARKER, portBYTE_ALIGNMENT, prvHeapInit(), prvInsertBlockIntoFreeList(), pxEnd, A_BLOCK_LINK::pxNextFreeBlock, traceMALLOC, vApplicationMallocFailedHook(), vTaskSuspendAll(), xBlockAllocatedBit, A_BLOCK_LINK::xBlockSize, xFreeBytesRemaining, xHeapStructSize, xMinimumEverFreeBytesRemaining, xNumberOfSuccessfulAllocations, xStart, and xTaskResumeAll().
Referenced by __uvMallocOS(), osMailCreate(), and osPoolCreate().
pxPortInitialiseStack()
StackType_t * pxPortInitialiseStack (StackType_t * pxTopOfStack, TaskFunction_t pxCode, void * pvParameters)
vPortDefineHeapRegions()
void vPortDefineHeapRegions (const HeapRegion_t *const pxHeapRegions)
vPortEndScheduler()
void vPortEndScheduler (void)
Definition at line 395 of file port.c.
References configASSERT.
Referenced by vTaskEndScheduler().
vPortFree()
void vPortFree (void * pv)
Definition at line 266 of file heap_4.c.
References configASSERT, mtCOVERAGE_TEST_MARKER, prvInsertBlockIntoFreeList(), A_BLOCK_LINK::pxNextFreeBlock, traceFREE, vTaskSuspendAll(), xBlockAllocatedBit, A_BLOCK_LINK::xBlockSize, xFreeBytesRemaining, xHeapStructSize, xNumberOfSuccessfulFrees, and xTaskResumeAll().
Referenced by __uvFreeOS(), osMailCreate(), osPoolCreate(), vEventGroupDelete(), vQueueDelete(), and vStreamBufferDelete().
vPortGetHeapStats()
void vPortGetHeapStats (HeapStats_t * pxHeapStats)
Definition at line 442 of file heap_4.c.
References portMAX_DELAY, pxEnd, A_BLOCK_LINK::pxNextFreeBlock, taskENTER_CRITICAL, taskEXIT_CRITICAL, vTaskSuspendAll(), xHeapStats::xAvailableHeapSpaceInBytes, A_BLOCK_LINK::xBlockSize, xFreeBytesRemaining, xHeapStats::xMinimumEverFreeBytesRemaining, xMinimumEverFreeBytesRemaining, xHeapStats::xNumberOfFreeBlocks, xHeapStats::xNumberOfSuccessfulAllocations, xNumberOfSuccessfulAllocations, xHeapStats::xNumberOfSuccessfulFrees, xNumberOfSuccessfulFrees, xHeapStats::xSizeOfLargestFreeBlockInBytes, xHeapStats::xSizeOfSmallestFreeBlockInBytes, xStart, and xTaskResumeAll().
vPortInitialiseBlocks()
void vPortInitialiseBlocks (void)
Definition at line 327 of file heap_4.c.
xPortGetFreeHeapSize()
size_t xPortGetFreeHeapSize (void)
Definition at line 315 of file heap_4.c.
References xFreeBytesRemaining.
xPortGetMinimumEverFreeHeapSize()
size_t xPortGetMinimumEverFreeHeapSize (void)
Definition at line 321 of file heap_4.c.
References xMinimumEverFreeBytesRemaining.
xPortStartScheduler()
BaseType_t xPortStartScheduler (void)
Definition at line 287 of file port.c.
References configASSERT, configMAX_SYSCALL_INTERRUPT_PRIORITY, configPRIO_BITS, portASPEN_AND_LSPEN_BITS, portCORTEX_M7_r0p0_ID, portCORTEX_M7_r0p1_ID, portCPUID, portFIRST_USER_INTERRUPT_NUMBER, portFPCCR, portMAX_8_BIT_VALUE, portMAX_PRIGROUP_BITS, portNVIC_IP_REGISTERS_OFFSET_16, portNVIC_PENDSV_PRI, portNVIC_SYSPRI2_REG, portNVIC_SYSTICK_PRI, portPRIGROUP_SHIFT, portPRIORITY_GROUP_MASK, portTOP_BIT_OF_BYTE, prvPortStartFirstTask(), prvTaskExitError(), vPortEnableVFP(), vPortSetupTimerInterrupt(), and vTaskSwitchContext().
Referenced by vTaskStartScheduler().