Core/Src/rb_tree.c File Reference
#include "rb_tree.h"
#include <stdio.h>
#include <stdlib.h>
#include "uvfr_utils.h"
Functions
static void insertRepair (rbtree *rbt, rbnode *current)
static void deleteRepair (rbtree *rbt, rbnode *current)
static void rotateLeft (rbtree *, rbnode *)
static void rotateRight (rbtree *, rbnode *)
static int checkOrder (rbtree *rbt, rbnode *n, void *min, void *max)
static int checkBlackHeight (rbtree *rbt, rbnode *node)
static void print (rbtree *rbt, rbnode *node, void(*print_func)(void *), int depth, char *label)
static void destroyAllNodes (rbtree *rbt, rbnode *node)
rbtree * rbCreate (int(*compare)(const void *, const void *), void(*destroy)(void *))
Create and initialize a binary search tree.
void rbDestroy (rbtree *rbt)
Destroy the tree, and de-allocate it's elements.
rbnode * rbFind (rbtree *rbt, void *data)
Find a node of the tree based off the data you provide the tree.
rbnode * rbSuccessor (rbtree *rbt, rbnode *node)
int rbApplyNode (rbtree *rbt, rbnode *node, int(*func)(void *, void *), void *cookie, enum rbtraversal order)
rbnode * rbInsert (rbtree *rbt, void *data)
Function that inserts data into the tree, and creates a new node.
void * rbDelete (rbtree *rbt, rbnode *node, int keep)
Deletes a node from the tree.
int rbCheckOrder (rbtree *rbt, void *min, void *max)
Function that validates that the order of the nodes in the tree is correct.
int rbCheckBlackHeight (rbtree *rbt)
Function that Checks the height of black nodes.
void rbPrint (rbtree *rbt, void(*print_func)(void *))
Function used to print the contents of the tree.
Function Documentation
checkBlackHeight()
int checkBlackHeight (rbtree * rbt, rbnode * node) [static]
Definition at line 582 of file rb_tree.c.
References BLACK, checkBlackHeight(), rbnode::color, rbnode::left, rbnode::parent, RB_NIL, RED, and rbnode::right.
Referenced by checkBlackHeight(), and rbCheckBlackHeight().
checkOrder()
int checkOrder (rbtree * rbt, rbnode * n, void * min, void * max) [static]
Definition at line 553 of file rb_tree.c.
References checkOrder(), rbtree::compare, rbnode::data, rbnode::left, RB_NIL, and rbnode::right.
Referenced by checkOrder(), and rbCheckOrder().
deleteRepair()
void deleteRepair (rbtree * rbt, rbnode * current) [static]
Definition at line 454 of file rb_tree.c.
References BLACK, rbnode::color, rbnode::left, rbnode::parent, RB_FIRST, RED, rbnode::right, rotateLeft(), and rotateRight().
Referenced by rbDelete().
destroyAllNodes()
void destroyAllNodes (rbtree * rbt, rbnode * node) [static]
Definition at line 649 of file rb_tree.c.
References rbtree::count, rbnode::data, rbtree::destroy, rbnode::left, rbnode::parent, RB_NIL, and rbnode::right.
Referenced by rbDestroy().
insertRepair()
void insertRepair (rbtree * rbt, rbnode * current) [static]
Definition at line 293 of file rb_tree.c.
References BLACK, rbnode::color, rbnode::left, rbnode::parent, RED, rbnode::right, rotateLeft(), and rotateRight().
Referenced by rbInsert().
print()
void print (rbtree * rbt, rbnode * node, void(* print_func)(void *), int depth, char * label) [static]
Definition at line 617 of file rb_tree.c.
References rbnode::color, rbnode::data, rbnode::left, print(), RB_NIL, RED, and rbnode::right.
Referenced by print(), and rbPrint().
rbApplyNode()
int rbApplyNode (rbtree * rbt, rbnode * node, int(* func)(void *, void *), void * cookie, enum rbtraversal order)
Definition at line 116 of file rb_tree.c.
References rbnode::data, INORDER, rbnode::left, POSTORDER, PREORDER, RB_NIL, rbApplyNode(), and rbnode::right.
Referenced by rbApplyNode().
rbCheckBlackHeight()
int rbCheckBlackHeight (rbtree * rbt)
Function that Checks the height of black nodes.
Attention
DANGER!! THIS FUNCTION IS RECURSIVE. This is intended to be used in a laptop debugging context. The VCU simply does not have enough memory to deal with recursion of this manner.
Deprecated
Deprecated Leftovers from laptop unit tests.
Definition at line 571 of file rb_tree.c.
References checkBlackHeight(), RB_FIRST, RB_NIL, RB_ROOT, and RED.
Referenced by rbPrint().
rbCheckOrder()
int rbCheckOrder (rbtree * rbt, void * min, void * max)
Function that validates that the order of the nodes in the tree is correct.
Attention
DANGER!! THIS FUNCTION IS RECURSIVE. This is intended to be used in a laptop debugging context. The VCU simply does not have enough memory to deal with recursion of this manner.
Deprecated
Deprecated Leftovers from laptop unit tests.
Definition at line 545 of file rb_tree.c.
References checkOrder(), and RB_FIRST.
rbCreate()
rbtree * rbCreate (int(* compare_func)(const void *, const void *), void(* destroy_func)(void *))
Create and initialize a binary search tree.
Parameters
compare_func A function that compares the data of two nodes. Accepts pointers to the data as parameters
destroy_func The destructor function for the data, for safe disposal of dynamically allocated data
Definition at line 28 of file rb_tree.c.
References BLACK, rbnode::color, rbtree::compare, rbtree::count, rbnode::data, rbtree::destroy, rbnode::left, rbtree::min, rbtree::nil, rbnode::parent, RB_NIL, rbnode::right, and rbtree::root.
rbDelete()
void * rbDelete (rbtree * rbt, rbnode * node, int keep)
Deletes a node from the tree.
Parameters
rbt Instance of a rbtree that we are removing the node from.
node Pointer to the node that we would like to remove
keep If keep is a truthy value, a pointer to the data of the node will be returned. Otherwise, the node and it's data will be destroyed.
Return values
If keep is "true", this will return a pointer to the data held by the deleted node. Otherwise it will return NULL.
Definition at line 360 of file rb_tree.c.
References BLACK, rbnode::color, rbtree::count, rbnode::data, deleteRepair(), rbtree::destroy, rbnode::left, rbtree::min, rbnode::parent, RB_FIRST, RB_NIL, rbSuccessor(), RED, and rbnode::right.
rbDestroy()
void rbDestroy (rbtree * rbt)
Destroy the tree, and de-allocate it's elements.
Definition at line 61 of file rb_tree.c.
References destroyAllNodes(), and RB_FIRST.
rbFind()
rbnode * rbFind (rbtree * rbt, void * data)
Find a node of the tree based off the data you provide the tree.
Parameters
rbt Pointer to the tree in which we would like to find the node.
Return values
Returns a pointer to the node if the node is present in the tree. Otherwise, it will return NULL to indicate the node could not be found.
Definition at line 71 of file rb_tree.c.
References rbtree::compare, rbnode::data, rbnode::left, RB_FIRST, RB_NIL, and rbnode::right.
rbInsert()
rbnode * rbInsert (rbtree * rbt, void * data)
Function that inserts data into the tree, and creates a new node.
Parameters
rbt Instance of a rbtree that we would like to insert data into
data Pointer to the data we wish to insert
Return values
This function returns a pointer to the rbnode that was added. The function will return NULL if the system is out of memory, or is otherwise unable to insert the node.
Definition at line 207 of file rb_tree.c.
References BLACK, rbnode::color, rbtree::compare, rbtree::count, rbnode::data, rbtree::destroy, insertRepair(), rbnode::left, rbtree::min, rbnode::parent, RB_FIRST, RB_NIL, RB_ROOT, RED, and rbnode::right.
rbPrint()
void rbPrint (rbtree * rbt, void(* print_func)(void *))
Function used to print the contents of the tree.
Parameters
rbt a pointer to the rbtree you wish to print.
print_func A pointer to a print function specific to the data.
Attention
DANGER!! RECURSION!!
Deprecated
Deprecated Leftovers from laptop unit tests. Sorta useless, cause like what are we gonna print to?
Definition at line 607 of file rb_tree.c.
References print(), RB_FIRST, and rbCheckBlackHeight().
rbSuccessor()
rbnode * rbSuccessor (rbtree * rbt, rbnode * node)
Definition at line 92 of file rb_tree.c.
References rbnode::left, rbnode::parent, RB_NIL, RB_ROOT, and rbnode::right.
Referenced by rbDelete().
rotateLeft()
void rotateLeft (rbtree * rbt, rbnode * x) [static]
Definition at line 153 of file rb_tree.c.
References rbnode::left, rbnode::parent, RB_NIL, and rbnode::right.
Referenced by deleteRepair(), and insertRepair().
rotateRight()
void rotateRight (rbtree * rbt, rbnode * x) [static]
Definition at line 179 of file rb_tree.c.
References rbnode::left, rbnode::parent, RB_NIL, and rbnode::right.
Referenced by deleteRepair(), and insertRepair().