Core/Src/ready_to_drive.c File Reference
#include "uvfr_utils.h"
Functions
void rtdTask (void *args)
uv_status initRTDtask (void *args)
Function Documentation
rtdTask()
void rtdTask (void * args)
Definition at line 41 of file ready_to_drive.c.
References changeVehicleState(), uv_task_info::cmd_data, killSelf(), suspendSelf(), UV_DRIVING, UV_KILL_CMD, and UV_SUSPEND_CMD.
Referenced by initRTDtask().