Core/FreeRTOS/Source/stream_buffer.c File Reference
#include <stdint.h>
#include <string.h>
#include "../../../../Core/FreeRTOS/Source/include/FreeRTOS.h"
#include "../../../../Core/FreeRTOS/Source/include/task.h"
#include "../../../../Core/FreeRTOS/Source/include/stream_buffer.h"
Data Structures
struct StreamBufferDef_t
Macros
#define MPU_WRAPPERS_INCLUDED_FROM_API_FILE
#define sbRECEIVE_COMPLETED(pxStreamBuffer)
#define sbRECEIVE_COMPLETED_FROM_ISR(pxStreamBuffer, pxHigherPriorityTaskWoken)
#define sbSEND_COMPLETED(pxStreamBuffer)
#define sbSEND_COMPLETE_FROM_ISR(pxStreamBuffer, pxHigherPriorityTaskWoken)
#define sbBYTES_TO_STORE_MESSAGE_LENGTH (sizeof(configMESSAGE_BUFFER_LENGTH_TYPE))
#define sbFLAGS_IS_MESSAGE_BUFFER ((uint8_t) 1) /* Set if the stream buffer was created as a message buffer, in which case it holds discrete messages rather than a stream. */
#define sbFLAGS_IS_STATICALLY_ALLOCATED ((uint8_t) 2) /* Set if the stream buffer was created using statically allocated memory. */
Typedefs
typedef struct StreamBufferDef_t StreamBuffer_t
Functions
static size_t prvBytesInBuffer (const StreamBuffer_t *const pxStreamBuffer) PRIVILEGED_FUNCTION
static size_t prvWriteBytesToBuffer (StreamBuffer_t *const pxStreamBuffer, const uint8_t *pucData, size_t xCount) PRIVILEGED_FUNCTION
static size_t prvReadMessageFromBuffer (StreamBuffer_t *pxStreamBuffer, void *pvRxData, size_t xBufferLengthBytes, size_t xBytesAvailable, size_t xBytesToStoreMessageLength) PRIVILEGED_FUNCTION
static size_t prvWriteMessageToBuffer (StreamBuffer_t *const pxStreamBuffer, const void *pvTxData, size_t xDataLengthBytes, size_t xSpace, size_t xRequiredSpace) PRIVILEGED_FUNCTION
static size_t prvReadBytesFromBuffer (StreamBuffer_t *pxStreamBuffer, uint8_t *pucData, size_t xMaxCount, size_t xBytesAvailable) PRIVILEGED_FUNCTION
static void prvInitialiseNewStreamBuffer (StreamBuffer_t *const pxStreamBuffer, uint8_t *const pucBuffer, size_t xBufferSizeBytes, size_t xTriggerLevelBytes, uint8_t ucFlags) PRIVILEGED_FUNCTION
void vStreamBufferDelete (StreamBufferHandle_t xStreamBuffer)
BaseType_t xStreamBufferReset (StreamBufferHandle_t xStreamBuffer)
BaseType_t xStreamBufferSetTriggerLevel (StreamBufferHandle_t xStreamBuffer, size_t xTriggerLevel)
size_t xStreamBufferSpacesAvailable (StreamBufferHandle_t xStreamBuffer)
size_t xStreamBufferBytesAvailable (StreamBufferHandle_t xStreamBuffer)
size_t xStreamBufferSend (StreamBufferHandle_t xStreamBuffer, const void *pvTxData, size_t xDataLengthBytes, TickType_t xTicksToWait)
size_t xStreamBufferSendFromISR (StreamBufferHandle_t xStreamBuffer, const void *pvTxData, size_t xDataLengthBytes, BaseType_t *const pxHigherPriorityTaskWoken)
size_t xStreamBufferReceive (StreamBufferHandle_t xStreamBuffer, void *pvRxData, size_t xBufferLengthBytes, TickType_t xTicksToWait)
size_t xStreamBufferNextMessageLengthBytes (StreamBufferHandle_t xStreamBuffer)
size_t xStreamBufferReceiveFromISR (StreamBufferHandle_t xStreamBuffer, void *pvRxData, size_t xBufferLengthBytes, BaseType_t *const pxHigherPriorityTaskWoken)
BaseType_t xStreamBufferIsEmpty (StreamBufferHandle_t xStreamBuffer)
BaseType_t xStreamBufferIsFull (StreamBufferHandle_t xStreamBuffer)
BaseType_t xStreamBufferSendCompletedFromISR (StreamBufferHandle_t xStreamBuffer, BaseType_t *pxHigherPriorityTaskWoken)
BaseType_t xStreamBufferReceiveCompletedFromISR (StreamBufferHandle_t xStreamBuffer, BaseType_t *pxHigherPriorityTaskWoken)
Macro Definition Documentation
MPU_WRAPPERS_INCLUDED_FROM_API_FILE
#define MPU_WRAPPERS_INCLUDED_FROM_API_FILE
Definition at line 35 of file stream_buffer.c.
sbBYTES_TO_STORE_MESSAGE_LENGTH
#define sbBYTES_TO_STORE_MESSAGE_LENGTH (sizeof(configMESSAGE_BUFFER_LENGTH_TYPE))
Definition at line 132 of file stream_buffer.c.
Referenced by prvWriteMessageToBuffer(), xStreamBufferIsFull(), xStreamBufferNextMessageLengthBytes(), xStreamBufferReceive(), xStreamBufferReceiveFromISR(), xStreamBufferSend(), and xStreamBufferSendFromISR().
sbFLAGS_IS_MESSAGE_BUFFER
#define sbFLAGS_IS_MESSAGE_BUFFER ((uint8_t) 1) /* Set if the stream buffer was created as a message buffer, in which case it holds discrete messages rather than a stream. */
Definition at line 135 of file stream_buffer.c.
Referenced by prvWriteMessageToBuffer(), xStreamBufferIsFull(), xStreamBufferNextMessageLengthBytes(), xStreamBufferReceive(), xStreamBufferReceiveFromISR(), xStreamBufferSend(), and xStreamBufferSendFromISR().
sbFLAGS_IS_STATICALLY_ALLOCATED
#define sbFLAGS_IS_STATICALLY_ALLOCATED ((uint8_t) 2) /* Set if the stream buffer was created using statically allocated memory. */
Definition at line 136 of file stream_buffer.c.
Referenced by vStreamBufferDelete().
sbRECEIVE_COMPLETED
#define sbRECEIVE_COMPLETED(pxStreamBuffer)
Value:
        vTaskSuspendAll(); \
        { \
            if((pxStreamBuffer)->xTaskWaitingToSend != NULL) \
            { \
                (void) xTaskNotify((pxStreamBuffer)->xTaskWaitingToSend, \
                                      (uint32_t) 0, \
                                      eNoAction); \
                (pxStreamBuffer)->xTaskWaitingToSend = NULL; \
            } \
        } \
        (void) xTaskResumeAll();
Definition at line 57 of file stream_buffer.c.
Referenced by xStreamBufferReceive().
sbRECEIVE_COMPLETED_FROM_ISR
#define sbRECEIVE_COMPLETED_FROM_ISR(pxStreamBuffer, pxHigherPriorityTaskWoken)
Value:
    { \
    UBaseType_t uxSavedInterruptStatus; \
                                                                                        \
        uxSavedInterruptStatus = (UBaseType_t) portSET_INTERRUPT_MASK_FROM_ISR(); \
        { \
            if((pxStreamBuffer)->xTaskWaitingToSend != NULL) \
            { \
                (void) xTaskNotifyFromISR((pxStreamBuffer)->xTaskWaitingToSend, \
                                             (uint32_t) 0, \
                                             eNoAction, \
                                             pxHigherPriorityTaskWoken); \
                (pxStreamBuffer)->xTaskWaitingToSend = NULL; \
            } \
        } \
        portCLEAR_INTERRUPT_MASK_FROM_ISR(uxSavedInterruptStatus); \
    }
Definition at line 72 of file stream_buffer.c.
Referenced by xStreamBufferReceiveFromISR().
sbSEND_COMPLETE_FROM_ISR
#define sbSEND_COMPLETE_FROM_ISR(pxStreamBuffer, pxHigherPriorityTaskWoken)
Value:
    { \
    UBaseType_t uxSavedInterruptStatus; \
                                                                                        \
        uxSavedInterruptStatus = (UBaseType_t) portSET_INTERRUPT_MASK_FROM_ISR(); \
        { \
            if((pxStreamBuffer)->xTaskWaitingToReceive != NULL) \
            { \
                (void) xTaskNotifyFromISR((pxStreamBuffer)->xTaskWaitingToReceive, \
                                             (uint32_t) 0, \
                                             eNoAction, \
                                             pxHigherPriorityTaskWoken); \
                (pxStreamBuffer)->xTaskWaitingToReceive = NULL; \
            } \
        } \
        portCLEAR_INTERRUPT_MASK_FROM_ISR(uxSavedInterruptStatus); \
    }
Definition at line 111 of file stream_buffer.c.
Referenced by xStreamBufferSendFromISR().
sbSEND_COMPLETED
#define sbSEND_COMPLETED(pxStreamBuffer)
Value:
        vTaskSuspendAll(); \
        { \
            if((pxStreamBuffer)->xTaskWaitingToReceive != NULL) \
            { \
                (void) xTaskNotify((pxStreamBuffer)->xTaskWaitingToReceive, \
                                      (uint32_t) 0, \
                                      eNoAction); \
                (pxStreamBuffer)->xTaskWaitingToReceive = NULL; \
            } \
        } \
        (void) xTaskResumeAll();
Definition at line 96 of file stream_buffer.c.
Referenced by xStreamBufferSend().
Typedef Documentation
StreamBuffer_t
typedef struct StreamBufferDef_t StreamBuffer_t
Function Documentation
prvBytesInBuffer()
static size_t prvBytesInBuffer (const StreamBuffer_t *const pxStreamBuffer) [static]
Definition at line 1189 of file stream_buffer.c.
References mtCOVERAGE_TEST_MARKER, StreamBufferDef_t::xHead, StreamBufferDef_t::xLength, and StreamBufferDef_t::xTail.
Referenced by xStreamBufferBytesAvailable(), xStreamBufferNextMessageLengthBytes(), xStreamBufferReceive(), xStreamBufferReceiveFromISR(), xStreamBufferSend(), and xStreamBufferSendFromISR().
prvInitialiseNewStreamBuffer()
static void prvInitialiseNewStreamBuffer (StreamBuffer_t *const pxStreamBuffer, uint8_t *const pucBuffer, size_t xBufferSizeBytes, size_t xTriggerLevelBytes, uint8_t ucFlags) [static]
Definition at line 1209 of file stream_buffer.c.
References configASSERT, StreamBufferDef_t::pucBuffer, StreamBufferDef_t::ucFlags, StreamBufferDef_t::xLength, and StreamBufferDef_t::xTriggerLevelBytes.
Referenced by xStreamBufferReset().
prvReadBytesFromBuffer()
static size_t prvReadBytesFromBuffer (StreamBuffer_t * pxStreamBuffer, uint8_t * pucData, size_t xMaxCount, size_t xBytesAvailable) [static]
Definition at line 1134 of file stream_buffer.c.
References configASSERT, configMIN, mtCOVERAGE_TEST_MARKER, StreamBufferDef_t::pucBuffer, StreamBufferDef_t::xLength, and StreamBufferDef_t::xTail.
Referenced by prvReadMessageFromBuffer(), and xStreamBufferNextMessageLengthBytes().
prvReadMessageFromBuffer()
static size_t prvReadMessageFromBuffer (StreamBuffer_t * pxStreamBuffer, void * pvRxData, size_t xBufferLengthBytes, size_t xBytesAvailable, size_t xBytesToStoreMessageLength) [static]
Definition at line 918 of file stream_buffer.c.
References configMESSAGE_BUFFER_LENGTH_TYPE, mtCOVERAGE_TEST_MARKER, prvReadBytesFromBuffer(), and StreamBufferDef_t::xTail.
Referenced by xStreamBufferReceive(), and xStreamBufferReceiveFromISR().
prvWriteBytesToBuffer()
static size_t prvWriteBytesToBuffer (StreamBuffer_t *const pxStreamBuffer, const uint8_t * pucData, size_t xCount) [static]
Definition at line 1088 of file stream_buffer.c.
References configASSERT, configMIN, mtCOVERAGE_TEST_MARKER, StreamBufferDef_t::pucBuffer, StreamBufferDef_t::xHead, and StreamBufferDef_t::xLength.
Referenced by prvWriteMessageToBuffer().
prvWriteMessageToBuffer()
static size_t prvWriteMessageToBuffer (StreamBuffer_t *const pxStreamBuffer, const void * pvTxData, size_t xDataLengthBytes, size_t xSpace, size_t xRequiredSpace) [static]
Definition at line 661 of file stream_buffer.c.
References configMIN, pdFALSE, pdTRUE, prvWriteBytesToBuffer(), sbBYTES_TO_STORE_MESSAGE_LENGTH, sbFLAGS_IS_MESSAGE_BUFFER, and StreamBufferDef_t::ucFlags.
Referenced by xStreamBufferSend(), and xStreamBufferSendFromISR().
vStreamBufferDelete()
void vStreamBufferDelete (StreamBufferHandle_t xStreamBuffer)
Definition at line 359 of file stream_buffer.c.
References configASSERT, pdFALSE, sbFLAGS_IS_STATICALLY_ALLOCATED, traceSTREAM_BUFFER_DELETE, StreamBufferDef_t::ucFlags, and vPortFree().
xStreamBufferBytesAvailable()
size_t xStreamBufferBytesAvailable (StreamBufferHandle_t xStreamBuffer)
Definition at line 494 of file stream_buffer.c.
References configASSERT, and prvBytesInBuffer().
xStreamBufferIsEmpty()
BaseType_t xStreamBufferIsEmpty (StreamBufferHandle_t xStreamBuffer)
Definition at line 970 of file stream_buffer.c.
References configASSERT, pdFALSE, pdTRUE, StreamBufferDef_t::xHead, and StreamBufferDef_t::xTail.
xStreamBufferIsFull()
BaseType_t xStreamBufferIsFull (StreamBufferHandle_t xStreamBuffer)
Definition at line 993 of file stream_buffer.c.
References configASSERT, pdFALSE, pdTRUE, sbBYTES_TO_STORE_MESSAGE_LENGTH, sbFLAGS_IS_MESSAGE_BUFFER, StreamBufferDef_t::ucFlags, and xStreamBufferSpacesAvailable().
xStreamBufferNextMessageLengthBytes()
size_t xStreamBufferNextMessageLengthBytes (StreamBufferHandle_t xStreamBuffer)
Definition at line 817 of file stream_buffer.c.
References configASSERT, configMESSAGE_BUFFER_LENGTH_TYPE, prvBytesInBuffer(), prvReadBytesFromBuffer(), sbBYTES_TO_STORE_MESSAGE_LENGTH, sbFLAGS_IS_MESSAGE_BUFFER, StreamBufferDef_t::ucFlags, and StreamBufferDef_t::xTail.
xStreamBufferReceive()
size_t xStreamBufferReceive (StreamBufferHandle_t xStreamBuffer, void * pvRxData, size_t xBufferLengthBytes, TickType_t xTicksToWait)
Definition at line 713 of file stream_buffer.c.
References configASSERT, mtCOVERAGE_TEST_MARKER, prvBytesInBuffer(), prvReadMessageFromBuffer(), sbBYTES_TO_STORE_MESSAGE_LENGTH, sbFLAGS_IS_MESSAGE_BUFFER, sbRECEIVE_COMPLETED, taskENTER_CRITICAL, taskEXIT_CRITICAL, traceBLOCKING_ON_STREAM_BUFFER_RECEIVE, traceSTREAM_BUFFER_RECEIVE, traceSTREAM_BUFFER_RECEIVE_FAILED, StreamBufferDef_t::ucFlags, xTaskGetCurrentTaskHandle(), xTaskNotifyStateClear(), xTaskNotifyWait(), and StreamBufferDef_t::xTaskWaitingToReceive.
xStreamBufferReceiveCompletedFromISR()
BaseType_t xStreamBufferReceiveCompletedFromISR (StreamBufferHandle_t xStreamBuffer, BaseType_t * pxHigherPriorityTaskWoken)
Definition at line 1058 of file stream_buffer.c.
References configASSERT, eNoAction, pdFALSE, pdTRUE, portCLEAR_INTERRUPT_MASK_FROM_ISR, portSET_INTERRUPT_MASK_FROM_ISR, and xTaskNotifyFromISR.
xStreamBufferReceiveFromISR()
size_t xStreamBufferReceiveFromISR (StreamBufferHandle_t xStreamBuffer, void * pvRxData, size_t xBufferLengthBytes, BaseType_t *const pxHigherPriorityTaskWoken)
Definition at line 861 of file stream_buffer.c.
References configASSERT, mtCOVERAGE_TEST_MARKER, prvBytesInBuffer(), prvReadMessageFromBuffer(), sbBYTES_TO_STORE_MESSAGE_LENGTH, sbFLAGS_IS_MESSAGE_BUFFER, sbRECEIVE_COMPLETED_FROM_ISR, traceSTREAM_BUFFER_RECEIVE_FROM_ISR, and StreamBufferDef_t::ucFlags.
xStreamBufferReset()
BaseType_t xStreamBufferReset (StreamBufferHandle_t xStreamBuffer)
Definition at line 392 of file stream_buffer.c.
References configASSERT, pdFAIL, pdPASS, prvInitialiseNewStreamBuffer(), StreamBufferDef_t::pucBuffer, taskENTER_CRITICAL, taskEXIT_CRITICAL, traceSTREAM_BUFFER_RESET, StreamBufferDef_t::ucFlags, StreamBufferDef_t::xLength, StreamBufferDef_t::xTaskWaitingToReceive, StreamBufferDef_t::xTaskWaitingToSend, and StreamBufferDef_t::xTriggerLevelBytes.
xStreamBufferSend()
size_t xStreamBufferSend (StreamBufferHandle_t xStreamBuffer, const void * pvTxData, size_t xDataLengthBytes, TickType_t xTicksToWait)
Definition at line 506 of file stream_buffer.c.
References configASSERT, mtCOVERAGE_TEST_MARKER, pdFALSE, prvBytesInBuffer(), prvWriteMessageToBuffer(), sbBYTES_TO_STORE_MESSAGE_LENGTH, sbFLAGS_IS_MESSAGE_BUFFER, sbSEND_COMPLETED, taskENTER_CRITICAL, taskEXIT_CRITICAL, traceBLOCKING_ON_STREAM_BUFFER_SEND, traceSTREAM_BUFFER_SEND, traceSTREAM_BUFFER_SEND_FAILED, StreamBufferDef_t::ucFlags, vTaskSetTimeOutState(), xStreamBufferSpacesAvailable(), xTaskCheckForTimeOut(), xTaskGetCurrentTaskHandle(), xTaskNotifyStateClear(), xTaskNotifyWait(), StreamBufferDef_t::xTaskWaitingToSend, and StreamBufferDef_t::xTriggerLevelBytes.
xStreamBufferSendCompletedFromISR()
BaseType_t xStreamBufferSendCompletedFromISR (StreamBufferHandle_t xStreamBuffer, BaseType_t * pxHigherPriorityTaskWoken)
Definition at line 1028 of file stream_buffer.c.
References configASSERT, eNoAction, pdFALSE, pdTRUE, portCLEAR_INTERRUPT_MASK_FROM_ISR, portSET_INTERRUPT_MASK_FROM_ISR, and xTaskNotifyFromISR.
xStreamBufferSendFromISR()
size_t xStreamBufferSendFromISR (StreamBufferHandle_t xStreamBuffer, const void * pvTxData, size_t xDataLengthBytes, BaseType_t *const pxHigherPriorityTaskWoken)
Definition at line 610 of file stream_buffer.c.
References configASSERT, mtCOVERAGE_TEST_MARKER, prvBytesInBuffer(), prvWriteMessageToBuffer(), sbBYTES_TO_STORE_MESSAGE_LENGTH, sbFLAGS_IS_MESSAGE_BUFFER, sbSEND_COMPLETE_FROM_ISR, traceSTREAM_BUFFER_SEND_FROM_ISR, StreamBufferDef_t::ucFlags, xStreamBufferSpacesAvailable(), and StreamBufferDef_t::xTriggerLevelBytes.
xStreamBufferSetTriggerLevel()
BaseType_t xStreamBufferSetTriggerLevel (StreamBufferHandle_t xStreamBuffer, size_t xTriggerLevel)
Definition at line 441 of file stream_buffer.c.
References configASSERT, pdFALSE, pdPASS, and StreamBufferDef_t::xTriggerLevelBytes.
xStreamBufferSpacesAvailable()
size_t xStreamBufferSpacesAvailable (StreamBufferHandle_t xStreamBuffer)
Definition at line 470 of file stream_buffer.c.
References configASSERT, mtCOVERAGE_TEST_MARKER, StreamBufferDef_t::xHead, StreamBufferDef_t::xLength, and StreamBufferDef_t::xTail.
Referenced by xStreamBufferIsFull(), xStreamBufferSend(), and xStreamBufferSendFromISR().