Core/Src/temp_monitoring.c File Reference
#include "can.h"
#include "uvfr_utils.h"
#include "gpio.h"
Functions
uv_status initTempMonitor (void *arguments)
void testfunc (uv_CAN_msg *msg)
void testfunc2 (uv_CAN_msg *msg)
void testfunc3 (uv_CAN_msg *msg)
void CAN_1_TEST_msg (uv_CAN_msg *msg)
Monitors the temperatures of various points in the tractive system, and activates various cooling systems and such accordingly.
void CAN_2_TEST_msg2 (uv_CAN_msg *msg)
void tempMonitorTask (void *args)
Variables
uint16_t adc_coolant_temp1 = 0
uint16_t adc_coolant_temp2 = 0
int16_t mc_motor_temp
int16_t mc_igbt_temp
Function Documentation
CAN_1_TEST_msg()
void CAN_1_TEST_msg (uv_CAN_msg * msg)
Monitors the temperatures of various points in the tractive system, and activates various cooling systems and such accordingly.
Atm, this is mostly serving as an example of a task
Definition at line 90 of file temp_monitoring.c.
CAN_2_TEST_msg2()
void CAN_2_TEST_msg2 (uv_CAN_msg * msg)
Definition at line 99 of file temp_monitoring.c.
initTempMonitor()
uv_status initTempMonitor (void * arguments)
Definition at line 17 of file temp_monitoring.c.
References _UV_DEFAULT_TASK_STACK_SIZE, uv_task_info::active_states, uv_task_info::deletion_states, PROGRAMMING, uv_task_info::stack_size, uv_task_info::suspension_states, uv_task_info::task_args, uv_task_info::task_function, uv_task_info::task_name, uv_task_info::task_period, uv_task_info::task_priority, tempMonitorTask(), UV_DRIVING, UV_ERROR, UV_ERROR_STATE, UV_LAUNCH_CONTROL, UV_OK, UV_READY, and uvCreateTask().
Referenced by uvInitStateEngine().
tempMonitorTask()
void tempMonitorTask (void * args)
These here lines set the delay. This task executes exactly at the period specified, regardless of how long the task execution actually takes
 */
insertCANMessageHandler(0x64, testfunc2, CAN_BUS_2);
//insertCANMessageHandler(0x6B1, BMS_msg2, CAN_BUS_2);
uv_CAN_msg temp1;
uv_CAN_msg temp2;
temp1.data[0] = 1;
temp1.data[1] = 2;
temp1.data[2] = 3;
temp1.dlc = 3;
temp1.msg_id = 0x85;
temp1.flags = CAN_BUS_1;
temp2.data[0] = 9;
temp2.data[1] = 10;
temp2.data[2] = 11;
temp2.dlc = 3;
temp2.msg_id = 0xF5;
temp2.flags = 0x00;
uvSendCanMSG(&temp1);
uvSendCanMSG(&temp2);
TickType_t tick_period = pdMS_TO_TICKS(params->task_period); //Convert ms of period to the RTOS ticks
TickType_t last_time = 0;
/**
This is an example of a task control point, which is the spot in the task where the task decides what needs to be done, based on the commands it has received from the task manager and the SCD
Definition at line 112 of file temp_monitoring.c.
References CAN_BUS_1, CAN_BUS_2, uv_task_info::cmd_data, uv_CAN_msg::data, uv_CAN_msg::dlc, uv_CAN_msg::flags, insertCANMessageHandler(), killSelf(), uv_CAN_msg::msg_id, suspendSelf(), uv_task_info::task_period, testfunc(), testfunc2(), testfunc3(), UV_KILL_CMD, UV_SUSPEND_CMD, uvSendCanMSG(), and uvTaskDelayUntil.
Referenced by initTempMonitor().
testfunc()
void testfunc (uv_CAN_msg * msg)
Definition at line 47 of file temp_monitoring.c.
References changeVehicleState(), UV_DRIVING, UV_ERROR_STATE, UV_READY, and vehicle_state.
Referenced by tempMonitorTask().
testfunc2()
void testfunc2 (uv_CAN_msg * msg)
Definition at line 57 of file temp_monitoring.c.
References uv_CAN_msg::data, uv_CAN_msg::flags, and uvSendCanMSG().
Referenced by tempMonitorTask().
testfunc3()
void testfunc3 (uv_CAN_msg * msg)
Definition at line 70 of file temp_monitoring.c.
References CAN_BUS_1, uv_CAN_msg::data, uv_CAN_msg::flags, and uvSendCanMSG().
Referenced by tempMonitorTask().
Variable Documentation
adc_coolant_temp1
uint16_t adc_coolant_temp1 = 0
Definition at line 12 of file temp_monitoring.c.
adc_coolant_temp2
uint16_t adc_coolant_temp2 = 0
Definition at line 13 of file temp_monitoring.c.
mc_igbt_temp
int16_t mc_igbt_temp [extern]
Definition at line 31 of file motor_controller.c.
Referenced by ProcessMotorControllerResponse().
mc_motor_temp
int16_t mc_motor_temp [extern]
Definition at line 30 of file motor_controller.c.
Referenced by ProcessMotorControllerResponse().