Core/Inc/temp_monitoring.h File Reference
#include "uvfr_utils.h"
Functions
uv_status initTempMonitor (void *args)
void tempMonitorTask (void *args)
Function Documentation
initTempMonitor()
uv_status initTempMonitor (void * args)
Definition at line 17 of file temp_monitoring.c.
References _UV_DEFAULT_TASK_STACK_SIZE, uv_task_info::active_states, uv_task_info::deletion_states, PROGRAMMING, uv_task_info::stack_size, uv_task_info::suspension_states, uv_task_info::task_args, uv_task_info::task_function, uv_task_info::task_name, uv_task_info::task_period, uv_task_info::task_priority, tempMonitorTask(), UV_DRIVING, UV_ERROR, UV_ERROR_STATE, UV_LAUNCH_CONTROL, UV_OK, UV_READY, and uvCreateTask().
Referenced by uvInitStateEngine().
tempMonitorTask()
void tempMonitorTask (void * args)
These here lines set the delay. This task executes exactly at the period specified, regardless of how long the task execution actually takes
 */
insertCANMessageHandler(0x64, testfunc2, CAN_BUS_2);
//insertCANMessageHandler(0x6B1, BMS_msg2, CAN_BUS_2);
uv_CAN_msg temp1;
uv_CAN_msg temp2;
temp1.data[0] = 1;
temp1.data[1] = 2;
temp1.data[2] = 3;
temp1.dlc = 3;
temp1.msg_id = 0x85;
temp1.flags = CAN_BUS_1;
temp2.data[0] = 9;
temp2.data[1] = 10;
temp2.data[2] = 11;
temp2.dlc = 3;
temp2.msg_id = 0xF5;
temp2.flags = 0x00;
uvSendCanMSG(&temp1);
uvSendCanMSG(&temp2);
TickType_t tick_period = pdMS_TO_TICKS(params->task_period); //Convert ms of period to the RTOS ticks
TickType_t last_time = 0;
/**
This is an example of a task control point, which is the spot in the task where the task decides what needs to be done, based on the commands it has received from the task manager and the SCD
Definition at line 112 of file temp_monitoring.c.
References CAN_BUS_1, CAN_BUS_2, uv_task_info::cmd_data, uv_CAN_msg::data, uv_CAN_msg::dlc, uv_CAN_msg::flags, insertCANMessageHandler(), killSelf(), uv_CAN_msg::msg_id, suspendSelf(), uv_task_info::task_period, testfunc(), testfunc2(), testfunc3(), UV_KILL_CMD, UV_SUSPEND_CMD, uvSendCanMSG(), and uvTaskDelayUntil.
Referenced by initTempMonitor().