Core/Inc/tim.h File Reference
This file contains all the function prototypes for the tim.c file.
#include "main.h"
Functions
void MX_TIM3_Init (void)
void MX_TIM11_Init (void)
Variables
TIM_HandleTypeDef htim3
TIM_HandleTypeDef htim11
Detailed Description
This file contains all the function prototypes for the tim.c file.
Attention
Copyright (c) 2024 STMicroelectronics. All rights reserved.
This software is licensed under terms that can be found in the LICENSE file in the root directory of this software component. If no LICENSE file comes with this software, it is provided AS-IS.
Definition in file tim.h.
Function Documentation
MX_TIM11_Init()
void MX_TIM11_Init (void)
Definition at line 71 of file tim.c.
References Error_Handler(), and htim11.
Referenced by main().
MX_TIM3_Init()
void MX_TIM3_Init (void)
Definition at line 31 of file tim.c.
References Error_Handler(), and htim3.
Referenced by main().
Variable Documentation
htim11
TIM_HandleTypeDef htim11 [extern]
Definition at line 28 of file tim.c.
Referenced by MX_TIM11_Init().
htim3
TIM_HandleTypeDef htim3 [extern]
Definition at line 27 of file tim.c.
Referenced by HAL_TIM_PeriodElapsedCallback(), and MX_TIM3_Init().