Core/Src/tim.c File Reference
This file provides code for the configuration of the TIM instances.
#include "tim.h"
Functions
void MX_TIM3_Init (void)
void MX_TIM11_Init (void)
void HAL_TIM_Base_MspInit (TIM_HandleTypeDef *tim_baseHandle)
void HAL_TIM_Base_MspDeInit (TIM_HandleTypeDef *tim_baseHandle)
Variables
TIM_HandleTypeDef htim3
TIM_HandleTypeDef htim11
Detailed Description
This file provides code for the configuration of the TIM instances.
Attention
Copyright (c) 2024 STMicroelectronics. All rights reserved.
This software is licensed under terms that can be found in the LICENSE file in the root directory of this software component. If no LICENSE file comes with this software, it is provided AS-IS.
Definition in file tim.c.
Function Documentation
HAL_TIM_Base_MspDeInit()
void HAL_TIM_Base_MspDeInit (TIM_HandleTypeDef * tim_baseHandle)
Definition at line 124 of file tim.c.
HAL_TIM_Base_MspInit()
void HAL_TIM_Base_MspInit (TIM_HandleTypeDef * tim_baseHandle)
Definition at line 97 of file tim.c.
MX_TIM11_Init()
void MX_TIM11_Init (void)
Definition at line 71 of file tim.c.
References Error_Handler(), and htim11.
Referenced by main().
MX_TIM3_Init()
void MX_TIM3_Init (void)
Definition at line 31 of file tim.c.
References Error_Handler(), and htim3.
Referenced by main().
Variable Documentation
htim11
TIM_HandleTypeDef htim11
Definition at line 28 of file tim.c.
Referenced by MX_TIM11_Init().
htim3
TIM_HandleTypeDef htim3
Definition at line 27 of file tim.c.
Referenced by HAL_TIM_PeriodElapsedCallback(), and MX_TIM3_Init().