Core/Src/uvfr_conifer.c File Reference
#include "uvfr_conifer.h"
#include "uvfr_utils.h"
Macros
#define __dcs default_conifer_settings
#define __ch_list default_conifer_settings.ch_list
Functions
__attribute__ ((constructor))
Generates the default channel list at runtime, because this is less painful than trying to statically declare it.
uv_status coniferInvalidChLocCallback (abstract_conifer_channel *, uint8_t)
static uv_status coniferUpdateChannel (abstract_conifer_channel *ch_ptr)
This is meant to update the hardware to match the hardware abstraction.
void * theScrimDonguloder (uv_task_info *task_to_scrimdongulode)
uv_status coniferInit ()
Initializes the conifer library.
uv_status coniferDeInit ()
uv_status coniferEnLoadShedding ()
uv_status coniferDisLoadShedding ()
uv_status coniferEnChannel (conifer_output_channel ch)
Enables a conifer output channel.
uv_status coniferDisChannel (conifer_output_channel ch)
Disables a conifer output channel.
uv_status coniferToggleChannel (conifer_output_channel ch)
Toggles a conifer output channel.
uv_status coniferSetDutyCycle (conifer_output_channel ch, uint8_t duty)
Sets Duty Cycle of a conifer managed PWM output.
uv_status coniferSetDirection (conifer_output_channel ch, uint8_t dir)
Sets direction of a conifer managed H-bridge output.
uv_status coniferSetDutyCycleAndDirection (conifer_output_channel ch, uint8_t duty, uint8_t dir)
Set duty cycle and direction of a conifer managed.
uint16_t coniferGetChannelCurrent (conifer_output_channel ch)
uint16_t coniferGetChannelFbck (conifer_output_channel ch)
uint16_t coniferGetChannelFaults (conifer_output_channel ch)
Variables
struct conifer_settings default_conifer_settings
conifer_state cstate
static abstract_conifer_channel ch_table [FINAL_CONIFER_OUTPUT]
uv_status(* ch_updaters [8])(abstract_conifer_channel *, uint32_t *) = {0,0,0,0,0,0,0,0}
uv_status(* current_getters [8])(abstract_conifer_channel *, uint32_t *) = {0,0,0,0,0,0,0,0}
Macro Definition Documentation
__ch_list
#define __ch_list default_conifer_settings.ch_list
Definition at line 23 of file uvfr_conifer.c.
Referenced by __attribute__().
__dcs
#define __dcs default_conifer_settings
Definition at line 22 of file uvfr_conifer.c.
Referenced by __attribute__().
Function Documentation
__attribute__()
__attribute__ ((constructor))
Generates the default channel list at runtime, because this is less painful than trying to statically declare it.
Definition at line 41 of file uvfr_conifer.c.
References __ch_list, __dcs, BAMO_PWR, BAMO_RFE, BAMO_RUN, BRAKE_LIGHT, BSPD_PWR, CONIFER_CH_ALLOW_LOAD_SHED, CONIFER_CH_EN_BIT, CONIFER_CH_IN_USE, CONIFER_CH_IS_CRIT_BIT, COOLANT_PUMP1, DASH_PWR, GENERAL_ACCU_PWR1, abstract_conifer_channel::hardware_mapping, HORN, HVIL_PWR, RAD_FANS1, RAD_FANS2, SDC_BOARD_PWR, U19_PDU_20A_1, U19_PDU_20A_2, U19_PDU_20A_3, U19_PDU_20A_5, U19_PDU_20A_6, U19_PDU_20A_7, U19_PDU_5A_10, U19_PDU_5A_11, U19_PDU_5A_12, U19_PDU_5A_13, U19_PDU_5A_14, U19_PDU_5A_15, U19_PDU_5A_16, U19_PDU_5A_9, UV19_PDU_CH, and VCU_PWR.
coniferDeInit()
uv_status coniferDeInit ()
Definition at line 232 of file uvfr_conifer.c.
References UV_OK.
coniferDisChannel()
uv_status coniferDisChannel (conifer_output_channel ch)
Disables a conifer output channel.
Definition at line 300 of file uvfr_conifer.c.
References ch_table, coniferUpdateChannel(), IS_CONIFER_CH_USED, abstract_conifer_channel::status_control_reg, and UV_ABORTED.
Referenced by BeepBeepMotherFucker(), and uvSecureVehicle().
coniferDisLoadShedding()
uv_status coniferDisLoadShedding ()
Definition at line 258 of file uvfr_conifer.c.
References ch_table, CONIFER_CH_LS_ACTIVE, coniferUpdateChannel(), cstate, FINAL_CONIFER_OUTPUT, conifer_state::load_shedding, abstract_conifer_channel::status_control_reg, UV_ABORTED, UV_ERROR, and UV_OK.
coniferEnChannel()
uv_status coniferEnChannel (conifer_output_channel ch)
Enables a conifer output channel.
Definition at line 285 of file uvfr_conifer.c.
References ch_table, CONIFER_CH_EN_BIT, coniferUpdateChannel(), IS_CONIFER_CH_USED, abstract_conifer_channel::status_control_reg, and UV_ABORTED.
Referenced by BeepBeepMotherFucker(), and uvInit().
coniferEnLoadShedding()
uv_status coniferEnLoadShedding ()
Definition at line 236 of file uvfr_conifer.c.
References ch_table, CONIFER_CH_ALLOW_LOAD_SHED, CONIFER_CH_LS_ACTIVE, coniferUpdateChannel(), cstate, FINAL_CONIFER_OUTPUT, conifer_state::load_shedding, abstract_conifer_channel::status_control_reg, UV_ABORTED, UV_ERROR, and UV_OK.
coniferGetChannelCurrent()
uint16_t coniferGetChannelCurrent (conifer_output_channel ch)
Definition at line 362 of file uvfr_conifer.c.
References ch_table, CONIFER_CH_LOC_MASK, ECUMASTER_PMU16_CH, abstract_conifer_channel::hardware_mapping, IS_CONIFER_CH_USED, LOCAL_CH, UV19_PDU_CH, and UV_ABORTED.
coniferGetChannelFaults()
uint16_t coniferGetChannelFaults (conifer_output_channel ch)
Definition at line 407 of file uvfr_conifer.c.
coniferGetChannelFbck()
uint16_t coniferGetChannelFbck (conifer_output_channel ch)
Definition at line 386 of file uvfr_conifer.c.
References ch_table, CONIFER_CH_LOC_MASK, ECUMASTER_PMU16_CH, abstract_conifer_channel::hardware_mapping, LOCAL_CH, and UV19_PDU_CH.
coniferInit()
uv_status coniferInit ()
Initializes the conifer library.
Definition at line 173 of file uvfr_conifer.c.
References ch_table, ch_updaters, conifer_params, coniferUpdateChannel(), EXPECT_UV19PDU, FINAL_CONIFER_OUTPUT, abstract_conifer_channel::hardware_mapping, initPDU(), IS_CONIFER_CH_USED, abstract_conifer_channel::status_control_reg, u19updatePduChannel(), UV19_PDU_CH, UV_OK, and vTaskDelay().
Referenced by uvInit().
coniferInvalidChLocCallback()
uv_status coniferInvalidChLocCallback (abstract_conifer_channel * , uint8_t)
Definition at line 132 of file uvfr_conifer.c.
References UV_ERROR.
coniferSetDirection()
uv_status coniferSetDirection (conifer_output_channel ch, uint8_t dir)
Sets direction of a conifer managed H-bridge output.
Definition at line 340 of file uvfr_conifer.c.
References ch_table, coniferUpdateChannel(), IS_CONIFER_CH_USED, UV_ABORTED, and UV_ERROR.
coniferSetDutyCycle()
uv_status coniferSetDutyCycle (conifer_output_channel ch, uint8_t duty)
Sets Duty Cycle of a conifer managed PWM output.
Definition at line 328 of file uvfr_conifer.c.
References ch_table, coniferUpdateChannel(), IS_CONIFER_CH_USED, UV_ABORTED, and UV_ERROR.
coniferSetDutyCycleAndDirection()
uv_status coniferSetDutyCycleAndDirection (conifer_output_channel ch, uint8_t duty, uint8_t dir)
Set duty cycle and direction of a conifer managed.
Definition at line 352 of file uvfr_conifer.c.
References ch_table, coniferUpdateChannel(), IS_CONIFER_CH_USED, UV_ABORTED, and UV_ERROR.
coniferToggleChannel()
uv_status coniferToggleChannel (conifer_output_channel ch)
Toggles a conifer output channel.
Definition at line 314 of file uvfr_conifer.c.
References ch_table, CONIFER_CH_EN_BIT, coniferUpdateChannel(), IS_CONIFER_CH_USED, abstract_conifer_channel::status_control_reg, and UV_ABORTED.
Referenced by BeepBeepMotherFucker().
coniferUpdateChannel()
static uv_status coniferUpdateChannel (abstract_conifer_channel * ch_ptr) [inline], [static]
This is meant to update the hardware to match the hardware abstraction.
This extracts the hardware mapping of the abstract channel, and then invokes the drivers for the relevant hardware depending on what is mapped in the driver function lookup tables.
Definition at line 142 of file uvfr_conifer.c.
References ch_updaters, CONIFER_CH_IS_CRIT_BIT, CONIFER_CH_LOC_MASK, CONIFER_DRV_OK, abstract_conifer_channel::hardware_mapping, abstract_conifer_channel::status_control_reg, UV_ABORTED, UV_ERROR, UV_OK, and UV_WARNING.
Referenced by coniferDisChannel(), coniferDisLoadShedding(), coniferEnChannel(), coniferEnLoadShedding(), coniferInit(), coniferSetDirection(), coniferSetDutyCycle(), coniferSetDutyCycleAndDirection(), and coniferToggleChannel().
theScrimDonguloder()
void * theScrimDonguloder (uv_task_info * task_to_scrimdongulode)
Definition at line 164 of file uvfr_conifer.c.
Variable Documentation
ch_table
abstract_conifer_channel ch_table[FINAL_CONIFER_OUTPUT] [static]
Definition at line 30 of file uvfr_conifer.c.
Referenced by coniferDisChannel(), coniferDisLoadShedding(), coniferEnChannel(), coniferEnLoadShedding(), coniferGetChannelCurrent(), coniferGetChannelFbck(), coniferInit(), coniferSetDirection(), coniferSetDutyCycle(), coniferSetDutyCycleAndDirection(), and coniferToggleChannel().
ch_updaters
uv_status(* ch_updaters[8])(abstract_conifer_channel *, uint32_t *) (abstract_conifer_channel * , uint32_t *) = {0,0,0,0,0,0,0,0}
Definition at line 33 of file uvfr_conifer.c.
Referenced by coniferInit(), and coniferUpdateChannel().
cstate
conifer_state cstate
Initial value:
= {
    .status_flags = 0,
    .load_shedding = 0
}
Definition at line 25 of file uvfr_conifer.c.
Referenced by coniferDisLoadShedding(), and coniferEnLoadShedding().
current_getters
uv_status(* current_getters[8])(abstract_conifer_channel *, uint32_t *) (abstract_conifer_channel * , uint32_t *) = {0,0,0,0,0,0,0,0}
Definition at line 34 of file uvfr_conifer.c.
default_conifer_settings
struct conifer_settings default_conifer_settings
Initial value:
= {
    .conif_flags = EXPECT_UV19PDU|EN_DYNAMIC_LOAD_SHEDDING,
    .OCP_flt_time = 0,
    .OCP_load_shed_time = 0,
}
Definition at line 15 of file uvfr_conifer.c.
Referenced by setupDefaultSettings(), and uvResetFlashToDefault().