Core/Inc/uvfr_vehicle_commands.h File Reference
#include "uvfr_global_config.h"
#include "uvfr_utils.h"
Data Structures
struct output_channel
struct output_channel_settings
Typedefs
typedef struct output_channel output_channel
typedef struct output_channel_settings output_channel_settings
Functions
void uvActivateHorn ()
void uvSilenceHorn ()
void BeepBeepMotherFucker ()
void uvSecureVehicle ()
Function to put vehicle into safe state.
Typedef Documentation
output_channel
typedef struct output_channel output_channel
output_channel_settings
typedef struct output_channel_settings output_channel_settings
Definition at line 17 of file uvfr_settings.c.
Function Documentation
BeepBeepMotherFucker()
void BeepBeepMotherFucker ()
Definition at line 5 of file uvfr_vehicle_commands.c.
References coniferDisChannel(), coniferEnChannel(), coniferToggleChannel(), HORN, and vTaskDelay().
Referenced by uvInit().
uvActivateHorn()
void uvActivateHorn ()
uvSecureVehicle()
void uvSecureVehicle ()
Function to put vehicle into safe state.
Should perform the following functions in order:
Prevent new MC torque or speed requests
Open shutdown cct
Definition at line 23 of file uvfr_vehicle_commands.c.
References BAMO_RFE, coniferDisChannel(), MC_Shutdown(), and vTaskDelay().
uvSilenceHorn()
void uvSilenceHorn ()