Core/Inc/uvfr_conifer.h File Reference
#include "stdlib.h"
#include "stdint.h"
Data Structures
struct abstract_conifer_channel
struct conifer_ch_setting
struct conifer_settings
struct conifer_state
struct conifer_hw_channel
Macros
#define conifer_params current_vehicle_settings->conifer_settings
#define CONIFER_CH_EN_BIT (0x0001U<<0)
#define CONIFER_CH_IS_CRIT_BIT (0x0001U<<1)
#define CONIFER_CH_PSRC_BIT (0x0001U<<2)
#define CONIFER_CH_HB_DIR_MASK ((0x0001U<<3)|(0x0001U<<4))
#define CONIFER_CH_EN_OCP (0x0001U<<5)
#define CONIFER_CH_FLT_BIT (0x0001U<<6)
#define CONIFER_CH_ILIM_BIT (0x0001U<<7)
#define CONIFER_CH_ALLOW_LOAD_SHED (0x0001U<<8)
#define CONIFER_CH_LS_ACTIVE (0x0001U<<9)
#define CONIFER_CH_IN_USE (0x0001U<<15)
#define CONIFER_CH_LOC_MASK (0x0700U)
#define CONIFER_HW_CH_ID_MASK (0x00FF)
#define IS_CONIFER_CH_USED(ch)
#define GET_CONIFER_CH_LOC(ch)
#define EXPECT_UV19PDU (0x01U<<0)
#define EXPECT_ECUMASTER_PMU16 (0x01U<<1)
#define EN_SW_OCP (0x01U<<2)
#define EN_DYNAMIC_LOAD_SHEDDING (0x01U<<3)
#define ROUND_PWM_ON_BINARY_CHANNELS (0x01U<<8)
#define USE_ABS_VAL_MAPPING_HBRIDGE_TO_PWM (0x01U<<9)
#define CONIFER_CH_TYPE_MASK 0x0007
Typedefs
typedef struct conifer_ch_setting conifer_ch_setting
typedef enum CONIFER_OUTPUT conifer_output_channel
typedef enum conifer_driver_ecode conifer_driver_ecode
typedef struct conifer_settings conifer_settings
typedef enum conifer_ch_location conifer_ch_location
typedef struct conifer_state conifer_state
typedef enum conifer_hw_ch_type conifer_hw_ch_type
typedef struct conifer_hw_channel conifer_hw_channel
Enumerations
enum CONIFER_OUTPUT {
VCU_SAFETY
, BAMO_RFE
, BAMO_RUN
, BAMO_PWR
,
SDC_BOARD_PWR
, HVIL_PWR
, DCDC_EN
, COOLANT_PUMP1
,
COOLANT_PUMP2
, RAD_FANS1
, RAD_FANS2
, RAD_FANS3
,
RAD_FANS4
, ACCU_FANS1
, ACCU_FANS2
, BRAKE_LIGHT
,
HORN
, IMD_PWR
, GENERAL_ACCU_PWR1
, GENERAL_ACCU_PWR2
,
VCU_PWR
, RTML_PWR
, TSSI_PWR
, BSPD_PWR
,
DASH_PWR
, FINAL_CONIFER_OUTPUT
 }
enum conifer_driver_ecode {
CONIFER_DRV_OK
, CONIFER_DRV_INVALID_HW_LOC
, CONIFER_DRV_INVALID_HW_CH_ID
, CONIFER_DRV_INVALID_ABSTRACT_CH
,
CONIFER_EXT_DEVICE_NOT_FOUND
, CONIFER_EXT_DEVICE_NOR_RESPOND
, CONIFER_DRV_INIT_ERR
 }
enum conifer_ch_location {
LOCAL_CH = 0b000
, UV19_PDU_CH = 0b001
, ECUMASTER_PMU16_CH = 0b010
, RESERVED_CH_POS1 = 0b011
,
RESERVED_CH_POS2 = 0b100
, RESERVED_CH_POS3 = 0b101
, RESERVED_CH_POS4 = 0b110
, INVALID_MAPPING = 0b111
 }
enum conifer_hw_ch_type {
BIN_CH = 0x00
, DUAL_BUS_CH = 0x01
, PWM_CH = 0x02
, DUAL_BUS_PWM_CH = 0x03
,
H_BRIDGE = 0x04
, INDEPENDENT_REG_CH = 0x05
, EXT_BIN_CH = 0x06
, SPECIAL = 0x07
 }
Functions
uv_status coniferInit ()
Initializes the conifer library.
uv_status coniferDeInit ()
uv_status coniferEnChannel (conifer_output_channel ch)
Enables a conifer output channel.
uv_status coniferDisChannel (conifer_output_channel ch)
Disables a conifer output channel.
uv_status coniferToggleChannel (conifer_output_channel ch)
Toggles a conifer output channel.
uv_status coniferSetDutyCycle (conifer_output_channel ch, uint8_t duty)
Sets Duty Cycle of a conifer managed PWM output.
uv_status coniferSetDirection (conifer_output_channel ch, uint8_t dir)
Sets direction of a conifer managed H-bridge output.
uv_status coniferSetDutyCycleAndDirection (conifer_output_channel ch, uint8_t duty, uint8_t dir)
Set duty cycle and direction of a conifer managed.
uint16_t coniferGetChannelCurrent (conifer_output_channel ch)
uint16_t coniferGetChannelFbck (conifer_output_channel ch)
uint16_t coniferGetChannelFaults (conifer_output_channel ch)
Macro Definition Documentation
CONIFER_CH_ALLOW_LOAD_SHED
#define CONIFER_CH_ALLOW_LOAD_SHED (0x0001U<<8)
Definition at line 27 of file uvfr_conifer.h.
Referenced by __attribute__(), and coniferEnLoadShedding().
CONIFER_CH_EN_BIT
#define CONIFER_CH_EN_BIT (0x0001U<<0)
Definition at line 20 of file uvfr_conifer.h.
Referenced by __attribute__(), coniferEnChannel(), coniferToggleChannel(), and u19updatePduChannel().
CONIFER_CH_EN_OCP
#define CONIFER_CH_EN_OCP (0x0001U<<5)
Definition at line 24 of file uvfr_conifer.h.
CONIFER_CH_FLT_BIT
#define CONIFER_CH_FLT_BIT (0x0001U<<6)
Definition at line 25 of file uvfr_conifer.h.
Referenced by u19updatePduChannel().
CONIFER_CH_HB_DIR_MASK
#define CONIFER_CH_HB_DIR_MASK ((0x0001U<<3)|(0x0001U<<4))
Definition at line 23 of file uvfr_conifer.h.
CONIFER_CH_ILIM_BIT
#define CONIFER_CH_ILIM_BIT (0x0001U<<7)
Definition at line 26 of file uvfr_conifer.h.
CONIFER_CH_IN_USE
#define CONIFER_CH_IN_USE (0x0001U<<15)
Definition at line 31 of file uvfr_conifer.h.
Referenced by __attribute__().
CONIFER_CH_IS_CRIT_BIT
#define CONIFER_CH_IS_CRIT_BIT (0x0001U<<1)
Definition at line 21 of file uvfr_conifer.h.
Referenced by __attribute__(), and coniferUpdateChannel().
CONIFER_CH_LOC_MASK
#define CONIFER_CH_LOC_MASK (0x0700U)
Definition at line 32 of file uvfr_conifer.h.
Referenced by coniferGetChannelCurrent(), coniferGetChannelFbck(), and coniferUpdateChannel().
CONIFER_CH_LS_ACTIVE
#define CONIFER_CH_LS_ACTIVE (0x0001U<<9)
Definition at line 28 of file uvfr_conifer.h.
Referenced by coniferDisLoadShedding(), coniferEnLoadShedding(), and u19updatePduChannel().
CONIFER_CH_PSRC_BIT
#define CONIFER_CH_PSRC_BIT (0x0001U<<2)
Definition at line 22 of file uvfr_conifer.h.
CONIFER_CH_TYPE_MASK
#define CONIFER_CH_TYPE_MASK 0x0007
Definition at line 188 of file uvfr_conifer.h.
CONIFER_HW_CH_ID_MASK
#define CONIFER_HW_CH_ID_MASK (0x00FF)
Definition at line 33 of file uvfr_conifer.h.
conifer_params
#define conifer_params current_vehicle_settings->conifer_settings
Definition at line 7 of file uvfr_conifer.h.
Referenced by coniferInit(), and initPDU().
EN_DYNAMIC_LOAD_SHEDDING
#define EN_DYNAMIC_LOAD_SHEDDING (0x01U<<3)
Definition at line 97 of file uvfr_conifer.h.
EN_SW_OCP
#define EN_SW_OCP (0x01U<<2)
Definition at line 96 of file uvfr_conifer.h.
EXPECT_ECUMASTER_PMU16
#define EXPECT_ECUMASTER_PMU16 (0x01U<<1)
Definition at line 95 of file uvfr_conifer.h.
EXPECT_UV19PDU
#define EXPECT_UV19PDU (0x01U<<0)
Definition at line 94 of file uvfr_conifer.h.
Referenced by coniferInit().
GET_CONIFER_CH_LOC
#define GET_CONIFER_CH_LOC(ch)
Value:
((ch->hardware_mapping&CONIFER_CH_LOC_MASK)>>8)
Definition at line 36 of file uvfr_conifer.h.
IS_CONIFER_CH_USED
#define IS_CONIFER_CH_USED(ch)
Value:
(ch->hardware_mapping&CONIFER_CH_IN_USE)
Definition at line 35 of file uvfr_conifer.h.
Referenced by coniferDisChannel(), coniferEnChannel(), coniferGetChannelCurrent(), coniferInit(), coniferSetDirection(), coniferSetDutyCycle(), coniferSetDutyCycleAndDirection(), and coniferToggleChannel().
ROUND_PWM_ON_BINARY_CHANNELS
#define ROUND_PWM_ON_BINARY_CHANNELS (0x01U<<8)
Definition at line 99 of file uvfr_conifer.h.
USE_ABS_VAL_MAPPING_HBRIDGE_TO_PWM
#define USE_ABS_VAL_MAPPING_HBRIDGE_TO_PWM (0x01U<<9)
Definition at line 100 of file uvfr_conifer.h.
Typedef Documentation
conifer_ch_location
typedef enum conifer_ch_location conifer_ch_location
conifer_ch_setting
typedef struct conifer_ch_setting conifer_ch_setting
conifer_driver_ecode
typedef enum conifer_driver_ecode conifer_driver_ecode
conifer_hw_ch_type
typedef enum conifer_hw_ch_type conifer_hw_ch_type
conifer_hw_channel
typedef struct conifer_hw_channel conifer_hw_channel
conifer_output_channel
typedef enum CONIFER_OUTPUT conifer_output_channel
conifer_settings
typedef struct conifer_settings conifer_settings
conifer_state
typedef struct conifer_state conifer_state
Enumeration Type Documentation
conifer_ch_location
enum conifer_ch_location
Enumerator
LOCAL_CH
UV19_PDU_CH
ECUMASTER_PMU16_CH
RESERVED_CH_POS1
RESERVED_CH_POS2
RESERVED_CH_POS3
RESERVED_CH_POS4
INVALID_MAPPING
Definition at line 149 of file uvfr_conifer.h.
conifer_driver_ecode
enum conifer_driver_ecode
Enumerator
CONIFER_DRV_OK
CONIFER_DRV_INVALID_HW_LOC
CONIFER_DRV_INVALID_HW_CH_ID
CONIFER_DRV_INVALID_ABSTRACT_CH
CONIFER_EXT_DEVICE_NOT_FOUND
CONIFER_EXT_DEVICE_NOR_RESPOND
CONIFER_DRV_INIT_ERR
Definition at line 84 of file uvfr_conifer.h.
conifer_hw_ch_type
enum conifer_hw_ch_type
Enumerator
BIN_CH
DUAL_BUS_CH
PWM_CH
DUAL_BUS_PWM_CH
H_BRIDGE
INDEPENDENT_REG_CH
EXT_BIN_CH
SPECIAL
Definition at line 169 of file uvfr_conifer.h.
CONIFER_OUTPUT
enum CONIFER_OUTPUT
Enumerator
VCU_SAFETY
BAMO_RFE
BAMO_RUN
BAMO_PWR
SDC_BOARD_PWR
HVIL_PWR
DCDC_EN
COOLANT_PUMP1
COOLANT_PUMP2
RAD_FANS1
RAD_FANS2
RAD_FANS3
RAD_FANS4
ACCU_FANS1
ACCU_FANS2
BRAKE_LIGHT
HORN
IMD_PWR
GENERAL_ACCU_PWR1
GENERAL_ACCU_PWR2
VCU_PWR
RTML_PWR
TSSI_PWR
BSPD_PWR
DASH_PWR
FINAL_CONIFER_OUTPUT
Definition at line 45 of file uvfr_conifer.h.
Function Documentation
coniferDeInit()
uv_status coniferDeInit ()
Definition at line 232 of file uvfr_conifer.c.
References UV_OK.
coniferDisChannel()
uv_status coniferDisChannel (conifer_output_channel ch)
Disables a conifer output channel.
Definition at line 300 of file uvfr_conifer.c.
References ch_table, coniferUpdateChannel(), IS_CONIFER_CH_USED, abstract_conifer_channel::status_control_reg, and UV_ABORTED.
Referenced by BeepBeepMotherFucker(), and uvSecureVehicle().
coniferEnChannel()
uv_status coniferEnChannel (conifer_output_channel ch)
Enables a conifer output channel.
Definition at line 285 of file uvfr_conifer.c.
References ch_table, CONIFER_CH_EN_BIT, coniferUpdateChannel(), IS_CONIFER_CH_USED, abstract_conifer_channel::status_control_reg, and UV_ABORTED.
Referenced by BeepBeepMotherFucker(), and uvInit().
coniferGetChannelCurrent()
uint16_t coniferGetChannelCurrent (conifer_output_channel ch)
Definition at line 362 of file uvfr_conifer.c.
References ch_table, CONIFER_CH_LOC_MASK, ECUMASTER_PMU16_CH, abstract_conifer_channel::hardware_mapping, IS_CONIFER_CH_USED, LOCAL_CH, UV19_PDU_CH, and UV_ABORTED.
coniferGetChannelFaults()
uint16_t coniferGetChannelFaults (conifer_output_channel ch)
Definition at line 407 of file uvfr_conifer.c.
coniferGetChannelFbck()
uint16_t coniferGetChannelFbck (conifer_output_channel ch)
Definition at line 386 of file uvfr_conifer.c.
References ch_table, CONIFER_CH_LOC_MASK, ECUMASTER_PMU16_CH, abstract_conifer_channel::hardware_mapping, LOCAL_CH, and UV19_PDU_CH.
coniferInit()
uv_status coniferInit ()
Initializes the conifer library.
Definition at line 173 of file uvfr_conifer.c.
References ch_table, ch_updaters, conifer_params, coniferUpdateChannel(), EXPECT_UV19PDU, FINAL_CONIFER_OUTPUT, abstract_conifer_channel::hardware_mapping, initPDU(), IS_CONIFER_CH_USED, abstract_conifer_channel::status_control_reg, u19updatePduChannel(), UV19_PDU_CH, UV_OK, and vTaskDelay().
Referenced by uvInit().
coniferSetDirection()
uv_status coniferSetDirection (conifer_output_channel ch, uint8_t dir)
Sets direction of a conifer managed H-bridge output.
Definition at line 340 of file uvfr_conifer.c.
References ch_table, coniferUpdateChannel(), IS_CONIFER_CH_USED, UV_ABORTED, and UV_ERROR.
coniferSetDutyCycle()
uv_status coniferSetDutyCycle (conifer_output_channel ch, uint8_t duty)
Sets Duty Cycle of a conifer managed PWM output.
Definition at line 328 of file uvfr_conifer.c.
References ch_table, coniferUpdateChannel(), IS_CONIFER_CH_USED, UV_ABORTED, and UV_ERROR.
coniferSetDutyCycleAndDirection()
uv_status coniferSetDutyCycleAndDirection (conifer_output_channel ch, uint8_t duty, uint8_t dir)
Set duty cycle and direction of a conifer managed.
Definition at line 352 of file uvfr_conifer.c.
References ch_table, coniferUpdateChannel(), IS_CONIFER_CH_USED, UV_ABORTED, and UV_ERROR.
coniferToggleChannel()
uv_status coniferToggleChannel (conifer_output_channel ch)
Toggles a conifer output channel.
Definition at line 314 of file uvfr_conifer.c.
References ch_table, CONIFER_CH_EN_BIT, coniferUpdateChannel(), IS_CONIFER_CH_USED, abstract_conifer_channel::status_control_reg, and UV_ABORTED.
Referenced by BeepBeepMotherFucker().