Core/Src/uvfr_utils.c File Reference
#include "uvfr_utils.h"
#include "uvfr_conifer.h"
Macros
#define UV_UTILS_SRC_IMPLIMENTATION
Functions
void rtdTask (void *args)
void uvInit (void *arguments)
: Function that initializes all of the car's stuff.
void uvSysResetDaemon (void *args)
enum uv_status_t uvUtilsReset (uint8_t reset_type)
This function is a soft-reboot of the uv_utils_backend and OS abstraction.
void setup_extern_devices (void *argument)
void __uvInitPanic ()
Low Level Panic, that does not require the full UVFR utils functionality to be operational.
void * __uvMallocCritSection (size_t memrequest)
Wrapper function for malloc() that makes it thread safe.
uv_status __uvFreeCritSection (void *ptr)
Thread-safe wrapper for free.
void * __uvMallocOS (size_t memrequest)
malloc() wrapper that calls pvPortMalloc() rather than malloc()
uv_status __uvFreeOS (void *ptr)
OS-based free wrapper that calls pvPortFree.
uv_status uvIsPTRValid (void *ptr)
function that checks to make sure a pointer points to a place it is allowed to point to
Variables
TaskHandle_t init_task_handle
uint8_t TxData [8]
TaskHandle_t reset_handle = NULL
const uint8_t data_size []
Macro Definition Documentation
UV_UTILS_SRC_IMPLIMENTATION
#define UV_UTILS_SRC_IMPLIMENTATION
Definition at line 9 of file uvfr_utils.c.
Function Documentation
__uvFreeCritSection()
uv_status __uvFreeCritSection (void * ptr)
Thread-safe wrapper for free.
This is typically called from the macro expansion of uvFree(x)
Definition at line 407 of file uvfr_utils.c.
References pdTRUE, UV_ERROR, UV_OK, uvIsPTRValid(), vTaskSuspendAll(), and xTaskResumeAll().
__uvFreeOS()
uv_status __uvFreeOS (void * ptr)
OS-based free wrapper that calls pvPortFree.
Definition at line 458 of file uvfr_utils.c.
References UV_ERROR, UV_OK, uvIsPTRValid(), and vPortFree().
__uvInitPanic()
void __uvInitPanic ()
Low Level Panic, that does not require the full UVFR utils functionality to be operational.
Attention
Calling _uvInitPanic() is irreversable and will cause the vehicle to hang itself. This is only to be used as a last resort to stop the vehicle from entering an invalid state.
Definition at line 350 of file uvfr_utils.c.
References vTaskEndScheduler().
Referenced by uvInit(), uvInitStateEngine(), uvSettingsInit(), and uvSVCTaskManager().
__uvMallocCritSection()
void * __uvMallocCritSection (size_t memrequest)
Wrapper function for malloc() that makes it thread safe.
This typically appears in a macro expansion from uvMalloc(x)
Definition at line 371 of file uvfr_utils.c.
References pdTRUE, vTaskSuspendAll(), and xTaskResumeAll().
__uvMallocOS()
void * __uvMallocOS (size_t memrequest)
malloc() wrapper that calls pvPortMalloc() rather than malloc()
The reason we might wanto to be using pvPortMalloc() rather than regular stdlib malloc() is to consolodate the heap between RTOS and non-RTOS functions.
Definition at line 432 of file uvfr_utils.c.
References pvPortMalloc(), UV_OK, and uvIsPTRValid().
rtdTask()
void rtdTask (void * args)
Definition at line 41 of file ready_to_drive.c.
References changeVehicleState(), uv_task_info::cmd_data, killSelf(), suspendSelf(), UV_DRIVING, UV_KILL_CMD, UV_SUSPEND_CMD, and vTaskDelay().
Referenced by initRTDtask().
setup_extern_devices()
void setup_extern_devices (void * argument)
Deprecated
Deprecated I really dunno why this still exists, but this gets called somewhere so Im leaving it. I think we just pass it NULL.
Definition at line 338 of file uvfr_utils.c.
uvInit()
void uvInit (void * arguments)
: Function that initializes all of the car's stuff.
This is an RTOS task, and it serves to setup all of the car's different functions. at this point in our execution, we have already initialized all of our favorite hardware peripherals using HAL. Now we get to configure our convoluted system of OS-level settings and state machines.
It executes the following functions, in order:
Load Vehicle Settings
Initialize and Start State Machine
Start Service Tasks, such as CAN, ADC, etc...
Initialize External Devices such as BMS, IMD, Motor Controller
Validate that these devices have actually booted up
Set vehicle state to UV_READY
Pretty important shit if you ask me.
First on the block is our settings. The uv_settings are a bit strange, in the following way. We will check if we have saved custom settings, or if these settings are the default or not. It will then perform a checksum on the settings, and validate them to ensure they are safe If it fails to validate the settings, it will attempt to return to factory default.
If it is unable to return even to factory default settings, then we are in HUGE trouble, and some catastrophic bug has occurred. If it fails to even start this, it will not be safe to drive We must therefore panic.
Once the settings are initialized, we will initialize the system diagnostics. This is done early, so that future errors will result in events being properly tracked and logged
Next up we will attempt to initialize the state engine. If this fails, then we are in another case where we are genuinely unsafe to drive. This will create the prototypes for a bajillion tasks that will be started and stopped. Which tasks are currently running, depends on the whims of the state engine. Since the state engine is critical to our ability to handle errors and implausibilitys, we cannot proceed without a fully operational state engine.
Once the state machine is initialized we get to actually start the thing.
Once the state machine is initialized we get to actually start the thing.
Once we have initialized the state engine, what we want to do is create the prototypes of all the tasks that will be running.
Next we setup conifer and the associated drivers. This is needed, because we need to enable power to devices such as the BMS, and motor controller so that we can talk to them over CANbus
Now we are going to create a bunch of tasks that will initialize our car's external devices. The reason that these are RTOS tasks, is that it takes a buncha time to verify the existance of some devices. As a direct result, we can sorta just wait around and check that each task sends a message confirming that it has successfully executed. :) However, first we need to actually create a Queue for these tasks to use
  /
QueueHandle_t init_validation_queue = xQueueCreate(8,sizeof(uv_init_task_response));
if(init_validation_queue == NULL){
    __uvInitPanic();
}
 The next big thing on our plate is checking the status of all external devices we need, and initializing them with appropriate parameters. These are split into tasks because it takes a bit of time, especially for devices that need to be configured via CANBus such as the motor controller. That is why it is split the way it is, to allow these to run somewhat concurrently
*/
   BaseType_t retval;
   uint16_t ext_devices_status = 0x0000; //Tracks which devices are currently setup
   //osThreadDef_t MC_init_thread = {"MC_init",MC_Startup,osPriorityNormal,128,0};
   uv_init_task_args* MC_init_args = uvMalloc(sizeof(uv_init_task_args));
   MC_init_args->init_info_queue = init_validation_queue;
   MC_init_args->specific_args = &(current_vehicle_settings->mc_settings);
   retval = xTaskCreate(MC_Startup,"MC_init",256,MC_init_args,osPriorityAboveNormal,&(MC_init_args->meta_task_handle));
   if(retval != pdPASS){
       //FUCK
       error_msg = "bruh";
   }else{
       ext_devices_status |= 0x01U << MOTOR_CONTROLLER;
   }
 This thread is for initializing the BMS
*/
   //osThreadDef_t BMS_init_thread = {"BMS_init",BMS_Init,osPriorityNormal,128,0};
   uv_init_task_args* BMS_init_args = uvMalloc(sizeof(uv_init_task_args));
   BMS_init_args->init_info_queue = init_validation_queue;
   BMS_init_args->specific_args = &(current_vehicle_settings->bms_settings);
   //BMS_init_args->meta_task_handle = osThreadCreate(&BMS_init_thread,BMS_init_args);
   retval = xTaskCreate(BMS_Init,"BMS_init",256,BMS_init_args,osPriorityAboveNormal,&(BMS_init_args->meta_task_handle));
   if(retval != pdPASS){
       //FUCK
       error_msg = "bruh";
   }else{
       ext_devices_status |= 0x01U << BMS;
   }
 This variable is a tracker that tracks which devices have successfully initialized
 */
    uv_init_task_args* IMD_init_args = uvMalloc(sizeof(uv_init_task_args));
    IMD_init_args->init_info_queue = init_validation_queue;
    IMD_init_args->specific_args = &(current_vehicle_settings->imd_settings);
    retval = xTaskCreate(initIMD,"IMD_init",128,IMD_init_args,osPriorityAboveNormal,&(IMD_init_args->meta_task_handle));
    if(retval != pdPASS){
            //FUCK
        error_msg = "bruh";
    }else{
        ext_devices_status |= 0x01U << IMD;
    }
// uv_init_task_args* PDU_init_args = uvMalloc(sizeof(uv_init_task_args));
// PDU_init_args->init_info_queue = init_validation_queue;
// PDU_init_args->specific_args = &(current_vehicle_settings->imd_settings);
// retval = xTaskCreate(initPDU,"PDU_init",128,PDU_init_args,osPriorityAboveNormal,&(PDU_init_args->meta_task_handle)); //pass in the right settings, dumdum
// if(retval != pdPASS){
// //FUCK
// error_msg = "bruh";
// }
    initADCTask(); //START THE ADCs
Wait for all the spawned in tasks to do their thing. This should not take that long, but we wanna be sure that everything is chill If we are say, missing a BMS, then it will not allow you to proceed past the initialisation step This is handled by a message buffer, that takes inputs from all of the tasks
We allocate space for a response from the initialization.
Clean up, clean up, everybody clean up, clean up, clean up, everybody do your share! The following code cleans up all the threads that were running, and free up used memory
Definition at line 50 of file uvfr_utils.c.
References __uvInitPanic(), uv_task_info::active_states, BMS, BMS_Init(), uv_vehicle_settings::bms_settings, CAN_RX_DAEMON_NAME, CAN_TX_DAEMON_NAME, CANbusRxSvcDaemon(), CANbusTxSvcDaemon(), changeVehicleState(), coniferInit(), current_vehicle_settings, uv_init_task_response::device, uv_init_task_response::errmsg, IMD, uv_vehicle_settings::imd_settings, INIT_CHECK_PERIOD, uv_init_task_args::init_info_queue, init_task_handle, initADCTask(), initIMD(), MAX_INIT_TIME, uv_vehicle_settings::mc_settings, MC_Startup(), uv_init_task_args::meta_task_handle, MOTOR_CONTROLLER, uv_init_task_response::nchar, osPriorityAboveNormal, pdMS_TO_TICKS, pdPASS, uv_init_task_args::specific_args, uv_init_task_response::status, uv_task_info::task_function, uv_task_info::task_name, UV_OK, UV_READY, uvCreateServiceTask(), uvInitDiagnostics(), uvInitStateEngine(), uvSettingsInit(), uvStartStateMachine(), uvStartTask(), vTaskDelay(), vTaskDelayUntil(), vTaskDelete(), xQueueReceive(), and xTaskGetTickCount().
Referenced by main().
uvIsPTRValid()
uv_status uvIsPTRValid (void * ptr)
function that checks to make sure a pointer points to a place it is allowed to point to
The primary motivation for this is to avoid trying to dereference a pointer that doesnt exist, and triggering the HardFaultHandler(). That is never a fun time. This allows us to exit gracefully instead of getting stuck in an IRQ handler
Exiting gracefully can be pretty neat sometimes.
Definition at line 480 of file uvfr_utils.c.
References UV_ERROR, UV_OK, and UV_WARNING.
Referenced by __uvFreeCritSection(), __uvFreeOS(), __uvMallocOS(), associateDaqParamWithVar(), and uvCreateTmpSettingsCopy().
uvSysResetDaemon()
void uvSysResetDaemon (void * args)
Definition at line 306 of file uvfr_utils.c.
uvUtilsReset()
enum uv_status_t uvUtilsReset (uint8_t reset_type)
This function is a soft-reboot of the uv_utils_backend and OS abstraction.
The idea here is to basically start from a blank slate and boot up everything. So therefore we must:
Halt state machine.
Nuke vehicle operation related tasks.
Nuke the state machine
Nuke old settings
reinitialize uv_utils
Definition at line 324 of file uvfr_utils.c.
References UV_OK, and vTaskSuspendAll().
Variable Documentation
data_size
const uint8_t data_size[]
Initial value:
= {1,1,
        2,2,
        4,4,
        4,8,
        8,8,
        0}
Definition at line 21 of file uvfr_utils.c.
Referenced by insertParamToRegister(), and uvSettingsProgrammerTask().
init_task_handle
TaskHandle_t init_task_handle [extern]
Definition at line 85 of file main.c.
Referenced by main(), and uvInit().
reset_handle
TaskHandle_t reset_handle = NULL
Definition at line 19 of file uvfr_utils.c.
TxData
uint8_t TxData[8] [extern]
Definition at line 10 of file constants.c.