Core/Inc/uvfr_settings.h File Reference
#include `motor_controller.h`
#include `driving_loop.h`
#include `uvfr_utils.h`
#include `main.h`
#include `daq.h`
#include `bms.h`
Data Structures
struct veh_gen_info
struct uv_vehicle_settings
struct motor_controller_settings
Macros
#define ENABLE_FLASH_SETTINGS 0
#define START_OF_USER_FLASH &_s_uvdata
#define TOP_OF_USER_FLASH &_e_uvdata
#define TOP_OF_FLASH_SBLOCK (void*)0x080FFFFF
#define SBLOCK_CSR_OFFSET 0x0C00
#define SYS_DATA_OFFSET 0x00
#define SIZE_OF_MGROUP 0x0100
#define SBLOCK_CRC_REGION_OFFSET
#define SIZEOF_USER_FLASH 4096
#define SIZEOF_SBLOCK 4096
#define FLASH_SBLOCK_START START_OF_USER_FLASH
#define isPtrToFlash(p) ((p>=0x08000000)&&(p<TOP_OF_USER_FLASH))
#define GENERAL_VEH_INFO_MGROUP 0
#define GENERAL_VEH_INFO_OFFSET 32
#define OS_SETTINGS_MGROUP 0
#define OS_SETTINGS_OFFSET 128
#define OS_SETTINGS_ADDR ((void*)(START_OF_USER_FLASH + OS_SETTINGS_MGROUP*256 + OS_SETTINGS_OFFSET))
#define MOTOR_MGROUP 1
#define MOTOR_OFFSET 0
#define MOTOR_ADDR (struct motor_controller_settings*)(START_OF_USER_FLASH + MOTOR_MGROUP*256 + MOTOR_OFFSET)
#define DRIVING_MGROUP 2
#define DRIVING_OFFSET 0
#define DRIVING_ADDR ((driving_loop_args*)(START_OF_USER_FLASH + DRIVING_MGROUP + DRIVING_OFFSET))
#define BMS_MGROUP 4
#define BMS_OFFSET 0
#define BMS_ADDR NULL
#define IMD_MGROUP 4
#define IMD_OFFSET 128
#define IMD_ADDR ((void*)(START_OF_USER_FLASH + IMD_MGROUP*256 + IMD_OFFSET))
#define PDU_MGROUP 5
#define PDU_OFFSET 0
#define PDU_ADDR ((void*)(START_OF_USER_FLASH + PDU_MGROUP*256 + PDU_OFFSET))
#define DAQ_HEAD_MGROUP 5
#define DAQ_HEAD_OFFSET 128
#define DAQ_HEAD_ADDR ((daq_loop_args*)(START_OF_USER_FLASH + DAQ_HEAD_MGROUP*256 + DAQ_HEAD_OFFSET))
#define DAQ_PARAMS1_MGROUP 6
#define DAQ_PARAMS1_OFFSET 0
#define DAQ_PARAMS1_ADDR ((void*)(START_OF_USER_FLASH + DAQ_PARAMS1_MGROUP*256 + DAQ_PARAMS1_OFFSET))
#define DAQ_PARAMS2_MGROUP 7
#define DAQ_PARAMS2_OFFSET 0
#define DAQ_PARAMS2_ADDR
#define DAQ_PARAMS3_MGROUP 8
#define DAQ_PARAMS3_OFFSET 0
#define DAQ_PARAMS3_ADDR
#define PERSISTENT_DATA_MGROUP 13
#define CRC_MGROUP1 14
#define CRC_MGROUP2 15
#define SETTING_BRANCH_SIZE (256*10)
#define CRC_POLY 0x04C11DB7
#define MAGIC_NUMBER 0xEFBEADDE
Typedefs
typedef struct veh_gen_info veh_gen_info
typedef enum uv_status_t uv_status
typedef struct uv_vehicle_settings uv_vehicle_settings
typedef struct motor_controller_settings motor_controller_settings
Enumerations
enum laptop_CMD {
HANDSHAKE = 0x01,
ENTER_PROGRAMMING_MODE = 0x02,
REQUEST_VCU_STATUS = 0x03,
CLEAR_FAULTS = 0x04,
REQUEST_VCU_FIRMWARE_VERSION = 0x05,
GENERIC_ACK = 0x10,
CANNOT_PERFORM_REQUEST = 0x11,
SET_SPECIFIC_PARAM = 0x20,
END_OF_SPECIFIC_PARAMS = 0x3F,
REQUEST_ALL_SETTINGS = 0x40,
REQUEST_ALL_JOURNAL_ENTRIES = 0x41,
REQUEST_JOURNAL_ENTRIES_BY_TIME = 0x42,
REQUEST_SPECIFIC_SETTING = 0x43,
SAVE_AND_APPLY_NEW_SETTINGS = 0x80,
DISCARD_NEW_SETTINGS = 0x82,
DISCARD_NEW_SETTINGS_AND_EXIT = 0x83,
FORCE_RESTORE_FACTORY_DEFAULT = 0x84
 }
Functions
uv_status uvConfigSettingTask (void *args)
Function to setup the parameters of the setting setter task.
void nukeSettings (uv_vehicle_settings **settings_to_delete)
uv_status uvValidateSettingsFromFlash ()
enum uv_status_t uvSettingsInit ()
this function does one thing, and one thing only, it checks if we have custom settings, then it attempts to get them. If it fails, then we revert to factory defaults.
uv_status setupDefaultSettings ()
Function that allocates the neccessary space for all the vehicle settings, and handles sets all of the settings structs to defaults.
uv_status uvSaveSettingsToFlash ()
uv_status uvComputeMemRegionChecksum (void *sblock, uint32_t *csums, char mregion)
uv_status uvComputeSettingsCheckSums (void *sblock)
uv_status uvValidateChecksums (void *sblock)
Variables
uv_vehicle_settings * current_vehicle_settings
Macro Definition Documentation
BMS_ADDR
#define BMS_ADDR NULL
Definition at line 60 of file uvfr_settings.h.
BMS_MGROUP
#define BMS_MGROUP 4
Definition at line 58 of file uvfr_settings.h.
BMS_OFFSET
#define BMS_OFFSET 0
Definition at line 59 of file uvfr_settings.h.
CRC_MGROUP1
#define CRC_MGROUP1 14
Definition at line 87 of file uvfr_settings.h.
CRC_MGROUP2
#define CRC_MGROUP2 15
Definition at line 88 of file uvfr_settings.h.
CRC_POLY
#define CRC_POLY 0x04C11DB7
Definition at line 92 of file uvfr_settings.h.
DAQ_HEAD_ADDR
#define DAQ_HEAD_ADDR ((daq_loop_args*)(START_OF_USER_FLASH + DAQ_HEAD_MGROUP*256 + DAQ_HEAD_OFFSET))
Definition at line 72 of file uvfr_settings.h.
DAQ_HEAD_MGROUP
#define DAQ_HEAD_MGROUP 5
Definition at line 70 of file uvfr_settings.h.
DAQ_HEAD_OFFSET
#define DAQ_HEAD_OFFSET 128
Definition at line 71 of file uvfr_settings.h.
DAQ_PARAMS1_ADDR
#define DAQ_PARAMS1_ADDR ((void*)(START_OF_USER_FLASH + DAQ_PARAMS1_MGROUP*256 + DAQ_PARAMS1_OFFSET))
Definition at line 76 of file uvfr_settings.h.
DAQ_PARAMS1_MGROUP
#define DAQ_PARAMS1_MGROUP 6
Definition at line 74 of file uvfr_settings.h.
DAQ_PARAMS1_OFFSET
#define DAQ_PARAMS1_OFFSET 0
Definition at line 75 of file uvfr_settings.h.
DAQ_PARAMS2_ADDR
#define DAQ_PARAMS2_ADDR
Definition at line 80 of file uvfr_settings.h.
DAQ_PARAMS2_MGROUP
#define DAQ_PARAMS2_MGROUP 7
Definition at line 78 of file uvfr_settings.h.
DAQ_PARAMS2_OFFSET
#define DAQ_PARAMS2_OFFSET 0
Definition at line 79 of file uvfr_settings.h.
DAQ_PARAMS3_ADDR
#define DAQ_PARAMS3_ADDR
Definition at line 84 of file uvfr_settings.h.
DAQ_PARAMS3_MGROUP
#define DAQ_PARAMS3_MGROUP 8
Definition at line 82 of file uvfr_settings.h.
DAQ_PARAMS3_OFFSET
#define DAQ_PARAMS3_OFFSET 0
Definition at line 83 of file uvfr_settings.h.
DRIVING_ADDR
#define DRIVING_ADDR ((driving_loop_args*)(START_OF_USER_FLASH + DRIVING_MGROUP + DRIVING_OFFSET))
Definition at line 56 of file uvfr_settings.h.
DRIVING_MGROUP
#define DRIVING_MGROUP 2
Definition at line 54 of file uvfr_settings.h.
DRIVING_OFFSET
#define DRIVING_OFFSET 0
Definition at line 55 of file uvfr_settings.h.
ENABLE_FLASH_SETTINGS
#define ENABLE_FLASH_SETTINGS 0
Definition at line 21 of file uvfr_settings.h.
FLASH_SBLOCK_START
#define FLASH_SBLOCK_START START_OF_USER_FLASH
Definition at line 37 of file uvfr_settings.h.
GENERAL_VEH_INFO_MGROUP
#define GENERAL_VEH_INFO_MGROUP 0
Definition at line 43 of file uvfr_settings.h.
GENERAL_VEH_INFO_OFFSET
#define GENERAL_VEH_INFO_OFFSET 32
Definition at line 44 of file uvfr_settings.h.
IMD_ADDR
#define IMD_ADDR ((void*)(START_OF_USER_FLASH + IMD_MGROUP*256 + IMD_OFFSET))
Definition at line 64 of file uvfr_settings.h.
IMD_MGROUP
#define IMD_MGROUP 4
Definition at line 62 of file uvfr_settings.h.
IMD_OFFSET
#define IMD_OFFSET 128
Definition at line 63 of file uvfr_settings.h.
isPtrToFlash
#define isPtrToFlash(p) ((p>=0x08000000)&&(p<TOP_OF_USER_FLASH))
Definition at line 40 of file uvfr_settings.h.
MAGIC_NUMBER
#define MAGIC_NUMBER 0xEFBEADDE
Definition at line 96 of file uvfr_settings.h.
MOTOR_ADDR
#define MOTOR_ADDR (struct motor_controller_settings*)(START_OF_USER_FLASH + MOTOR_MGROUP*256 + MOTOR_OFFSET)
Definition at line 52 of file uvfr_settings.h.
MOTOR_MGROUP
#define MOTOR_MGROUP 1
Definition at line 50 of file uvfr_settings.h.
MOTOR_OFFSET
#define MOTOR_OFFSET 0
Definition at line 51 of file uvfr_settings.h.
OS_SETTINGS_ADDR
#define OS_SETTINGS_ADDR ((void*)(START_OF_USER_FLASH + OS_SETTINGS_MGROUP*256 + OS_SETTINGS_OFFSET))
Definition at line 48 of file uvfr_settings.h.
OS_SETTINGS_MGROUP
#define OS_SETTINGS_MGROUP 0
Definition at line 46 of file uvfr_settings.h.
OS_SETTINGS_OFFSET
#define OS_SETTINGS_OFFSET 128
Definition at line 47 of file uvfr_settings.h.
PDU_ADDR
#define PDU_ADDR ((void*)(START_OF_USER_FLASH + PDU_MGROUP*256 + PDU_OFFSET))
Definition at line 68 of file uvfr_settings.h.
PDU_MGROUP
#define PDU_MGROUP 5
Definition at line 66 of file uvfr_settings.h.
PDU_OFFSET
#define PDU_OFFSET 0
Definition at line 67 of file uvfr_settings.h.
PERSISTENT_DATA_MGROUP
#define PERSISTENT_DATA_MGROUP 13
Definition at line 86 of file uvfr_settings.h.
SBLOCK_CRC_REGION_OFFSET
#define SBLOCK_CRC_REGION_OFFSET
Definition at line 31 of file uvfr_settings.h.
SBLOCK_CSR_OFFSET
#define SBLOCK_CSR_OFFSET 0x0C00
Definition at line 28 of file uvfr_settings.h.
SETTING_BRANCH_SIZE
#define SETTING_BRANCH_SIZE (256*10)
Definition at line 90 of file uvfr_settings.h.
SIZE_OF_MGROUP
#define SIZE_OF_MGROUP 0x0100
Definition at line 30 of file uvfr_settings.h.
SIZEOF_SBLOCK
#define SIZEOF_SBLOCK 4096
Definition at line 35 of file uvfr_settings.h.
SIZEOF_USER_FLASH
#define SIZEOF_USER_FLASH 4096
Definition at line 34 of file uvfr_settings.h.
START_OF_USER_FLASH
#define START_OF_USER_FLASH &_s_uvdata
Definition at line 25 of file uvfr_settings.h.
SYS_DATA_OFFSET
#define SYS_DATA_OFFSET 0x00
Definition at line 29 of file uvfr_settings.h.
TOP_OF_FLASH_SBLOCK
#define TOP_OF_FLASH_SBLOCK (void*)0x080FFFFF
Definition at line 27 of file uvfr_settings.h.
TOP_OF_USER_FLASH
#define TOP_OF_USER_FLASH &_e_uvdata
Definition at line 26 of file uvfr_settings.h.
Typedef Documentation
motor_controller_settings
typedef struct motor_controller_settings motor_controller_settings
uv_status
typedef enum uv_status_t uv_status
Definition at line 112 of file uvfr_settings.h.
uv_vehicle_settings
typedef struct uv_vehicle_settings uv_vehicle_settings
veh_gen_info
typedef struct veh_gen_info veh_gen_info
Enumeration Type Documentation
laptop_CMD
enum laptop_CMD
Enumerator
HANDSHAKE
ENTER_PROGRAMMING_MODE
REQUEST_VCU_STATUS
CLEAR_FAULTS
REQUEST_VCU_FIRMWARE_VERSION
GENERIC_ACK
CANNOT_PERFORM_REQUEST
SET_SPECIFIC_PARAM
END_OF_SPECIFIC_PARAMS
REQUEST_ALL_SETTINGS
REQUEST_ALL_JOURNAL_ENTRIES
REQUEST_JOURNAL_ENTRIES_BY_TIME
REQUEST_SPECIFIC_SETTING
SAVE_AND_APPLY_NEW_SETTINGS
DISCARD_NEW_SETTINGS
DISCARD_NEW_SETTINGS_AND_EXIT
FORCE_RESTORE_FACTORY_DEFAULT
Definition at line 114 of file uvfr_settings.h.
Function Documentation
nukeSettings()
void nukeSettings (uv_vehicle_settings ** settings_to_delete)
Definition at line 260 of file uvfr_settings.c.
setupDefaultSettings()
uv_status setupDefaultSettings ()
Function that allocates the neccessary space for all the vehicle settings, and handles sets all of the settings structs to defaults.
Definition at line 232 of file uvfr_settings.c.
References uv_vehicle_settings::bms_settings, current_vehicle_settings, uv_vehicle_settings::daq_param_list, uv_vehicle_settings::daq_settings, default_bms_settings, default_daq_settings, default_datapoints, default_dl_settings, default_imd_settings, default_os_settings, default_pdu_settings, default_vehicle, uv_vehicle_settings::driving_loop_settings, uv_vehicle_settings::flags, uv_vehicle_settings::imd_settings, mc_default_settings, uv_vehicle_settings::mc_settings, uv_vehicle_settings::os_settings, uv_vehicle_settings::pdu_settings, UV_ERROR, UV_OK, and uv_vehicle_settings::veh_info.
Referenced by uvSettingsInit().
uvComputeMemRegionChecksum()
uv_status uvComputeMemRegionChecksum (void * sblock, uint32_t * csums, char mregion)
Definition at line 463 of file uvfr_settings.c.
References UV_OK, and uvComputeChunkChecksum().
Referenced by uvComputeSettingsChecksums().
uvComputeSettingsCheckSums()
uv_status uvComputeSettingsCheckSums (void * sblock)
uvConfigSettingTask()
uv_status uvConfigSettingTask (void * args)
Function to setup the parameters of the setting setter task.
Definition at line 305 of file uvfr_settings.c.
References ABOVE_NORMAL, uv_task_info::active_states, uv_task_info::deletion_states, PROGRAMMING, uv_task_info::stack_size, uv_task_info::suspension_states, uv_task_info::task_args, uv_task_info::task_function, uv_task_info::task_name, uv_task_info::task_period, uv_task_info::task_priority, UV_ERROR, UV_OK, uvCreateTask(), and uvSettingsProgrammerTask().
Referenced by uvInitStateEngine().
uvSaveSettingsToFlash()
uv_status uvSaveSettingsToFlash ()
uvSettingsInit()
enum uv_status_t uvSettingsInit ()
this function does one thing, and one thing only, it checks if we have custom settings, then it attempts to get them. If it fails, then we revert to factory defaults.
Definition at line 334 of file uvfr_settings.c.
References __uvInitPanic(), current_vehicle_settings, handleIncomingLaptopMsg(), insertCANMessageHandler(), SETTING_BRANCH_SIZE, setupDefaultSettings(), START_OF_USER_FLASH, UV_ERROR, UV_OK, uvLoadSettingsFromFlash(), uvResetFlashToDefault(), uvSendCanMSG(), uvValidateFlashSettings(), and vcu_ack_msg.
Referenced by uvInit().
uvValidateChecksums()
uv_status uvValidateChecksums (void * sblock)
Definition at line 495 of file uvfr_settings.c.
References UV_ERROR, UV_OK, and uvComputeSettingsChecksums().
uvValidateSettingsFromFlash()
uv_status uvValidateSettingsFromFlash ()
Variable Documentation
current_vehicle_settings
uv_vehicle_settings* current_vehicle_settings
Definition at line 20 of file uvfr_settings.c.
Referenced by configureDaqSubTasks(), initDaqTask(), initDrivingLoop(), setupDefaultSettings(), uvInit(), uvLoadSettingsFromFlash(), uvSettingsInit(), and uvStartStateMachine().