Core/Src/uvfr_vehicle_commands.c File Reference
#include "uvfr_utils.h"
Functions
void BeepBeepMotherFucker ()
void uvSecureVehicle ()
Function to put vehicle into safe state.
Function Documentation
BeepBeepMotherFucker()
void BeepBeepMotherFucker ()
Definition at line 5 of file uvfr_vehicle_commands.c.
References coniferDisChannel(), coniferEnChannel(), coniferToggleChannel(), and HORN.
Referenced by uvInit().
uvSecureVehicle()
void uvSecureVehicle ()
Function to put vehicle into safe state.
Should perform the following functions in order:
Prevent new MC torque or speed requests
Open shutdown cct
Definition at line 23 of file uvfr_vehicle_commands.c.
References BAMO_RFE, coniferDisChannel(), and MC_Shutdown().