Core/Src/uvfr_vehicle_logger.c File Reference
#include "uvfr_utils.h"
#include "uvfr_state_engine.h"
#include "uvfr_vehicle_logger.h"
#include "can.h"
Macros
#define MAX_LOG_ENTRIES 32
#define LOG_DUMP_CAN_ID 0x666
Functions
uint32_t getSystemFaultFlags (void)
void clearSystemFaultFlags (uint32_t flags_to_clear)
uint8_t getLogCount (void)
const vehicle_log_entry * getLogEntry (uint8_t index)
void dumpLogsToUART (void)
void logVehicleFault (fault_event_type_e type, uv_task_info *task, const char *msg, const char *file, int line, const char *func, bool is_panic)
void flushLogsToCAN (void)
Macro Definition Documentation
LOG_DUMP_CAN_ID
#define LOG_DUMP_CAN_ID 0x666
Definition at line 22 of file uvfr_vehicle_logger.c.
Referenced by flushLogsToCAN().
MAX_LOG_ENTRIES
#define MAX_LOG_ENTRIES 32
Definition at line 21 of file uvfr_vehicle_logger.c.
Referenced by getLogCount(), and logVehicleFault().
Function Documentation
clearSystemFaultFlags()
void clearSystemFaultFlags (uint32_t flags_to_clear)
clears specific fault flags (set bits) from the bitfield
Definition at line 46 of file uvfr_vehicle_logger.c.
dumpLogsToUART()
void dumpLogsToUART (void)
prints all stored logs to UART (e.x, for debugging)
Definition at line 68 of file uvfr_vehicle_logger.c.
References vehicle_log_entry::file, vehicle_log_entry::func, getLogCount(), getLogEntry(), vehicle_log_entry::is_panic, vehicle_log_entry::line, vehicle_log_entry::msg, vehicle_log_entry::task_id, vehicle_log_entry::task_name, vehicle_log_entry::task_state, vehicle_log_entry::timestamp, vehicle_log_entry::type, and vehicle_log_entry::vehicle_state.
flushLogsToCAN()
void flushLogsToCAN (void)
Flush all current log entries out over CAN for diagnostic laptop tools. Each entry is sent as a single compact CAN frame.
Frame layout: ID = LOG_DUMP_CAN_ID DLC = 8 Byte 0 : fault type Byte 1 : timestamp LSB Byte 2 : timestamp MSB Byte 3 : task ID Byte 4 : is_panic flag Byte 5 : vehicle_state Byte 6 : reserved (0) Byte 7 : reserved (0)
Definition at line 155 of file uvfr_vehicle_logger.c.
References uv_CAN_msg::data, uv_CAN_msg::dlc, uv_CAN_msg::flags, getLogCount(), getLogEntry(), vehicle_log_entry::is_panic, LOG_DUMP_CAN_ID, uv_CAN_msg::msg_id, vehicle_log_entry::task_id, vehicle_log_entry::timestamp, vehicle_log_entry::type, uvSendCanMSG(), and vehicle_log_entry::vehicle_state.
Referenced by handleIncomingLaptopMsg().
getLogCount()
uint8_t getLogCount (void)
returns how many logs are stored right now
Definition at line 53 of file uvfr_vehicle_logger.c.
References MAX_LOG_ENTRIES.
Referenced by dumpLogsToUART(), flushLogsToCAN(), and getLogEntry().
getLogEntry()
const vehicle_log_entry * getLogEntry (uint8_t index)
returns a specific log entry by index
Definition at line 60 of file uvfr_vehicle_logger.c.
References getLogCount().
Referenced by dumpLogsToUART(), and flushLogsToCAN().
getSystemFaultFlags()
uint32_t getSystemFaultFlags (void)
returns the current bitfield (1 bit per fault type)
Definition at line 39 of file uvfr_vehicle_logger.c.
logVehicleFault()
void logVehicleFault (fault_event_type_e type, uv_task_info * task, const char * msg, const char * file, int line, const char * func, bool is_panic)
adds a new log entry for a fault or error.
Definition at line 97 of file uvfr_vehicle_logger.c.
References vehicle_log_entry::file, vehicle_log_entry::func, vehicle_log_entry::is_panic, vehicle_log_entry::line, MAX_LOG_ENTRIES, vehicle_log_entry::msg, uv_task_info::task_id, vehicle_log_entry::task_id, uv_task_info::task_name, vehicle_log_entry::task_name, uv_task_info::task_state, vehicle_log_entry::task_state, vehicle_log_entry::timestamp, vehicle_log_entry::type, UV_TASK_NOT_STARTED, vehicle_log_entry::vehicle_state, and vehicle_state.
Referenced by __uvPanic().