Core/Src/uvfr_settings.c File Reference
#include `uvfr_utils.h`
#include `main.h`
#include `stdlib.h`
Data Structures
struct tx_all_settings_args
struct tx_journal_args
union helper_task_args
struct setting_helper_task
Macros
#define SRC_UVFR_SETTINGS_C_
#define VCU_TO_LAPTOP_ID 0x420
#define LAPTOP_TO_VCU_ID 0x520
#define FLASH_OK 0
#define INVALID_SBLOCK 1
#define FLASH_NOT_UNLOCKED 2
#define DID_NOT_FINISH_PROGRAMMING 3
#define DATA_MISMATCH 4
#define PRE_CHECKSUM 5
#define POST_CHECKSUM 6
Typedefs
typedef struct tx_all_settings_args tx_all_settings_args
typedef struct tx_journal_args tx_journal_args
typedef union helper_task_args helper_task_args
typedef struct setting_helper_task setting_helper_task
Functions
uv_status uvValidateFlashSettings ()
Function that looks into the flash memory of the VCU, and determines if a valid set of settings exists.
uv_status uvResetFlashToDefault ()
void uvSettingsProgrammerTask (void *args) PRIVILEGED_FUNCTION
This is a task that executes the functionality necessary for vehicle diagnostics.
static void settingCopy (uint8_t *from, uint8_t *to, uint16_t length) PRIVILEGED_FUNCTION
Internal function that is used to copy an arbitrary amount of data from point A to point B.
uv_status uvTransmitVehicleStatus ()
Transmits the status of the vehicle, including errorcodes and similar.
uv_status uvAwaitLaptopAckMsg ()
void handleIncomingLaptopMsg (uv_CAN_msg *msg) PRIVILEGED_FUNCTION
Callback function for event where CAN message is received from laptop.
uv_status setupDefaultSettings ()
Function that allocates the neccessary space for all the vehicle settings, and handles sets all of the settings structs to defaults.
void nukeSettings (uv_vehicle_settings **settings_to_delete)
uv_status uvLoadSettingsFromFlash ()
This loads us some new settings from the flash memory.
uv_status uvConfigSettingTask (void *args)
Function to setup the parameters of the setting setter task.
uv_status uvSettingsInit ()
this function does one thing, and one thing only, it checks if we have custom settings, then it attempts to get them. If it fails, then we revert to factory defaults.
uv_status uvUpdateTmpSettings (uint8_t *tmp_settings, uint8_t memgroup, uint8_t m_offset, uint8_t size, uint8_t *data)
Updates a setting in a temporary SBlock by memory group and offset.
uint32_t uvComputeChunkChecksum (uint32_t *chunk)
uv_status uvComputeMemRegionChecksum (void *sblock, uint32_t *csums, char mregion)
uv_status uvComputeSettingsChecksums (void *sblock, uint32_t *csums)
uv_status uvValidateChecksums (void *sblock)
void uvSBlockCorruptionHandler ()
Function to call when the Sblock Flash has become corrupted somehow.
uv_status uvOverwriteCsr (void *sblock, uint32_t *csr)
uv_status uvSaveSettingsToFlash (void *sblock, uint32_t *ecode) PRIVILEGED_FUNCTION
Function to save a finished settings block to flash memory.
uv_status uvSetSettingResponseReminder (uint32_t reminder)
This reminds the VCU to shoot off it's own message later when it reboots.
uv_status uvForceDefaultReversionUponDeviceReset ()
void * uvCreateTmpSettingsCopy ()
Function that creates a temporary copy of the existing settings.
uv_status uvSendSpecificParam (uint8_t *origin, uint8_t mgroup, uint8_t m_offset, uint8_t size)
Function that locates a specific setting parameter and sends the value over canbus.
uv_status uvResetFlashToDefault (void *new_sblock)
uv_status uvSendSettingGroup (uint8_t *origin, uint8_t memgroup, uint8_t m_offset, uint16_t size)
Helper function for sending all settings.
void sendAllSettingsWorker (void *args)
Sub-task that sends all settings from the VCU to the.
void sendJournalWorker (void *args)
Sub-task that reads out the journal.
Variables
PRIVILEGED_DATA uint8_t _s_uvdata
PRIVILEGED_DATA uint8_t _e_uvdata
uv_vehicle_settings * current_vehicle_settings = NULL
struct uv_os_settings default_os_settings
struct motor_controller_settings mc_default_settings
struct driving_loop_args default_dl_settings
struct daq_loop_args default_daq_settings
struct uv_imd_settings default_imd_settings
bms_settings_t default_bms_settings
uv19_pdu_settings default_pdu_settings
daq_datapoint default_datapoints []
veh_gen_info default_vehicle
static bool is_laptop_connected = false
TickType_t last_contact_with_laptop = 0
static QueueHandle_t settings_queue = NULL
static TaskHandle_t ptask_handle = NULL
static TaskHandle_t child_task_handle = NULL
static bool child_task_active = false
const uv_CAN_msg vcu_ack_msg
const uv_CAN_msg vcu_ack_failed_msg
Macro Definition Documentation
DATA_MISMATCH
#define DATA_MISMATCH 4
Definition at line 567 of file uvfr_settings.c.
DID_NOT_FINISH_PROGRAMMING
#define DID_NOT_FINISH_PROGRAMMING 3
Definition at line 566 of file uvfr_settings.c.
FLASH_NOT_UNLOCKED
#define FLASH_NOT_UNLOCKED 2
Definition at line 565 of file uvfr_settings.c.
FLASH_OK
#define FLASH_OK 0
These defines are for the return error code of the next function
Definition at line 563 of file uvfr_settings.c.
INVALID_SBLOCK
#define INVALID_SBLOCK 1
Definition at line 564 of file uvfr_settings.c.
LAPTOP_TO_VCU_ID
#define LAPTOP_TO_VCU_ID 0x520
Definition at line 14 of file uvfr_settings.c.
POST_CHECKSUM
#define POST_CHECKSUM 6
Definition at line 569 of file uvfr_settings.c.
PRE_CHECKSUM
#define PRE_CHECKSUM 5
Definition at line 568 of file uvfr_settings.c.
SRC_UVFR_SETTINGS_C_
#define SRC_UVFR_SETTINGS_C_
Definition at line 7 of file uvfr_settings.c.
VCU_TO_LAPTOP_ID
#define VCU_TO_LAPTOP_ID 0x420
Definition at line 13 of file uvfr_settings.c.
Typedef Documentation
helper_task_args
typedef union helper_task_args helper_task_args
setting_helper_task
typedef struct setting_helper_task setting_helper_task
tx_all_settings_args
typedef struct tx_all_settings_args tx_all_settings_args
These are arguments passed to the `Transmit All Settings Over CANbus` Subroutine.
tx_journal_args
typedef struct tx_journal_args tx_journal_args
Function Documentation
handleIncomingLaptopMsg()
void handleIncomingLaptopMsg (uv_CAN_msg * msg)
Callback function for event where CAN message is received from laptop.
Definition at line 152 of file uvfr_settings.c.
References changeVehicleState(), CLEAR_FAULTS, uv_CAN_msg::data, DISCARD_NEW_SETTINGS, DISCARD_NEW_SETTINGS_AND_EXIT, uv_CAN_msg::dlc, END_OF_SPECIFIC_PARAMS, ENTER_PROGRAMMING_MODE, FIRMWARE_MAJOR_RELEASE, FIRMWARE_MINOR_RELEASE, FIRMWARE_PATCH_NUM, FORCE_RESTORE_FACTORY_DEFAULT, GENERIC_ACK, HANDSHAKE, is_laptop_connected, last_contact_with_laptop, uv_CAN_msg::msg_id, PROGRAMMING, REQUEST_ALL_JOURNAL_ENTRIES, REQUEST_ALL_SETTINGS, REQUEST_JOURNAL_ENTRIES_BY_TIME, REQUEST_SPECIFIC_SETTING, REQUEST_VCU_STATUS, SAVE_AND_APPLY_NEW_SETTINGS, serializeSmallE32, SET_SPECIFIC_PARAM, settings_queue, UV_OK, UV_READY, uvSendCanMSG(), uvTransmitVehicleStatus(), vcu_ack_failed_msg, and vehicle_state.
Referenced by uvSettingsInit().
nukeSettings()
void nukeSettings (uv_vehicle_settings ** settings_to_delete)
Definition at line 260 of file uvfr_settings.c.
sendAllSettingsWorker()
void sendAllSettingsWorker (void * args)
Sub-task that sends all settings from the VCU to the.
Definition at line 1163 of file uvfr_settings.c.
References setting_helper_task::args, BMS_MGROUP, BMS_OFFSET, child_task_active, child_task_handle, DAQ_HEAD_MGROUP, DAQ_HEAD_OFFSET, DAQ_PARAMS1_MGROUP, DAQ_PARAMS1_OFFSET, DRIVING_MGROUP, DRIVING_OFFSET, FLASH_SBLOCK_START, GENERAL_VEH_INFO_MGROUP, GENERAL_VEH_INFO_OFFSET, IMD_MGROUP, IMD_OFFSET, setting_helper_task::meta_task_handle, MOTOR_MGROUP, MOTOR_OFFSET, OS_SETTINGS_MGROUP, OS_SETTINGS_OFFSET, PDU_MGROUP, PDU_OFFSET, tx_all_settings_args::sblock_origin, helper_task_args::setting_tx_args, setting_helper_task::status, UV_OK, and uvSendSettingGroup().
sendJournalWorker()
void sendJournalWorker (void * args)
Sub-task that reads out the journal.
Attention
EVENT LOGGING IS NOT IMPLEMENTED YET, DO NOT TOUCH THIS
Definition at line 1226 of file uvfr_settings.c.
settingCopy()
static void settingCopy (uint8_t * from, uint8_t * to, uint16_t length) [inline], [static]
Internal function that is used to copy an arbitrary amount of data from point A to point B.
Definition at line 128 of file uvfr_settings.c.
Referenced by uvResetFlashToDefault().
setupDefaultSettings()
uv_status setupDefaultSettings ()
Function that allocates the neccessary space for all the vehicle settings, and handles sets all of the settings structs to defaults.
Definition at line 232 of file uvfr_settings.c.
References uv_vehicle_settings::bms_settings, current_vehicle_settings, uv_vehicle_settings::daq_param_list, uv_vehicle_settings::daq_settings, default_bms_settings, default_daq_settings, default_datapoints, default_dl_settings, default_imd_settings, default_os_settings, default_pdu_settings, default_vehicle, uv_vehicle_settings::driving_loop_settings, uv_vehicle_settings::flags, uv_vehicle_settings::imd_settings, mc_default_settings, uv_vehicle_settings::mc_settings, uv_vehicle_settings::os_settings, uv_vehicle_settings::pdu_settings, UV_ERROR, UV_OK, and uv_vehicle_settings::veh_info.
Referenced by uvSettingsInit().
uvAwaitLaptopAckMsg()
uv_status uvAwaitLaptopAckMsg ()
Definition at line 145 of file uvfr_settings.c.
References UV_ABORTED.
uvComputeChunkChecksum()
uint32_t uvComputeChunkChecksum (uint32_t * chunk)
Definition at line 448 of file uvfr_settings.c.
References CRC_POLY, and UV_OK.
Referenced by uvComputeMemRegionChecksum().
uvComputeMemRegionChecksum()
uv_status uvComputeMemRegionChecksum (void * sblock, uint32_t * csums, char mregion)
Definition at line 463 of file uvfr_settings.c.
References UV_OK, and uvComputeChunkChecksum().
Referenced by uvComputeSettingsChecksums().
uvComputeSettingsChecksums()
uv_status uvComputeSettingsChecksums (void * sblock, uint32_t * csums)
Definition at line 472 of file uvfr_settings.c.
References UV_OK, and uvComputeMemRegionChecksum().
Referenced by uvValidateChecksums().
uvConfigSettingTask()
uv_status uvConfigSettingTask (void * args)
Function to setup the parameters of the setting setter task.
Definition at line 305 of file uvfr_settings.c.
References ABOVE_NORMAL, uv_task_info::active_states, uv_task_info::deletion_states, PROGRAMMING, uv_task_info::stack_size, uv_task_info::suspension_states, uv_task_info::task_args, uv_task_info::task_function, uv_task_info::task_name, uv_task_info::task_period, uv_task_info::task_priority, UV_ERROR, UV_OK, uvCreateTask(), and uvSettingsProgrammerTask().
Referenced by uvInitStateEngine().
uvCreateTmpSettingsCopy()
void* uvCreateTmpSettingsCopy ()
Function that creates a temporary copy of the existing settings.
Definition at line 756 of file uvfr_settings.c.
References SETTING_BRANCH_SIZE, and START_OF_USER_FLASH.
Referenced by uvSettingsProgrammerTask().
uvForceDefaultReversionUponDeviceReset()
uv_status uvForceDefaultReversionUponDeviceReset ()
Deprecated
Deprecated
Definition at line 735 of file uvfr_settings.c.
References START_OF_USER_FLASH, UV_ERROR, and UV_OK.
uvLoadSettingsFromFlash()
uv_status uvLoadSettingsFromFlash ()
This loads us some new settings from the flash memory.
Definition at line 274 of file uvfr_settings.c.
References BMS_ADDR, uv_vehicle_settings::bms_settings, current_vehicle_settings, DAQ_HEAD_ADDR, uv_vehicle_settings::daq_param_list, DAQ_PARAMS1_ADDR, uv_vehicle_settings::daq_settings, uv_vehicle_settings::driving_loop_settings, DRIVING_MGROUP, DRIVING_OFFSET, GENERAL_VEH_INFO_MGROUP, GENERAL_VEH_INFO_OFFSET, IMD_ADDR, uv_vehicle_settings::imd_settings, uv_vehicle_settings::mc_settings, MOTOR_MGROUP, MOTOR_OFFSET, uv_vehicle_settings::os_settings, OS_SETTINGS_MGROUP, OS_SETTINGS_OFFSET, PDU_MGROUP, PDU_OFFSET, uv_vehicle_settings::pdu_settings, START_OF_USER_FLASH, UV_ERROR, UV_OK, and uv_vehicle_settings::veh_info.
Referenced by uvSettingsInit().
uvOverwriteCsr()
uv_status uvOverwriteCsr (void * sblock, uint32_t * csr)
Definition at line 555 of file uvfr_settings.c.
References UV_OK.
uvResetFlashToDefault() [1/2]
uv_status uvResetFlashToDefault ()
Referenced by uvSettingsInit(), and uvSettingsProgrammerTask().
uvResetFlashToDefault() [2/2]
uv_status uvResetFlashToDefault (void * new_sblock)
uvSendCanMSG(&vcu_ack_msg);
Definition at line 1057 of file uvfr_settings.c.
References BMS_MGROUP, BMS_OFFSET, DAQ_HEAD_MGROUP, DAQ_HEAD_OFFSET, DAQ_PARAMS1_MGROUP, DAQ_PARAMS1_OFFSET, DATA_MISMATCH, default_bms_settings, default_daq_settings, default_datapoints, default_dl_settings, default_imd_settings, default_os_settings, default_pdu_settings, default_vehicle, DID_NOT_FINISH_PROGRAMMING, DRIVING_MGROUP, DRIVING_OFFSET, FLASH_NOT_UNLOCKED, GENERAL_VEH_INFO_OFFSET, IMD_MGROUP, IMD_OFFSET, INVALID_SBLOCK, MAGIC_NUMBER, mc_default_settings, MOTOR_MGROUP, MOTOR_OFFSET, OS_SETTINGS_OFFSET, PDU_MGROUP, PDU_OFFSET, POST_CHECKSUM, PRE_CHECKSUM, SETTING_BRANCH_SIZE, settingCopy(), daq_loop_args::total_params_logged, UV_ERROR, UV_OK, and uvSaveSettingsToFlash().
uvSaveSettingsToFlash()
uv_status uvSaveSettingsToFlash (void * sblock, uint32_t * ecode)
Function to save a finished settings block to flash memory.
Definition at line 574 of file uvfr_settings.c.
References DATA_MISMATCH, DID_NOT_FINISH_PROGRAMMING, FIRMWARE_MAJOR_RELEASE, FIRMWARE_MINOR_RELEASE, FIRMWARE_PATCH_NUM, FLASH_NOT_UNLOCKED, FLASH_SBLOCK_START, INVALID_SBLOCK, MAGIC_NUMBER, START_OF_USER_FLASH, TOP_OF_FLASH_SBLOCK, UV_ERROR, and UV_OK.
Referenced by uvResetFlashToDefault(), and uvSettingsProgrammerTask().
uvSBlockCorruptionHandler()
void uvSBlockCorruptionHandler ()
Function to call when the Sblock Flash has become corrupted somehow.
Definition at line 511 of file uvfr_settings.c.
References FLASH_SBLOCK_START.
uvSendSettingGroup()
uv_status uvSendSettingGroup (uint8_t * origin, uint8_t memgroup, uint8_t m_offset, uint16_t size)
Helper function for sending all settings.
Definition at line 1143 of file uvfr_settings.c.
References UV_ERROR, UV_OK, and uvSendSpecificParam().
Referenced by sendAllSettingsWorker().
uvSendSpecificParam()
uv_status uvSendSpecificParam (uint8_t * origin, uint8_t mgroup, uint8_t m_offset, uint8_t size)
Function that locates a specific setting parameter and sends the value over canbus.
Definition at line 778 of file uvfr_settings.c.
References uv_CAN_msg::data, uv_CAN_msg::dlc, uv_CAN_msg::flags, uv_CAN_msg::msg_id, START_OF_USER_FLASH, UV_ERROR, UV_OK, and uvSendCanMSG().
Referenced by uvSendSettingGroup(), and uvSettingsProgrammerTask().
uvSetSettingResponseReminder()
uv_status uvSetSettingResponseReminder (uint32_t reminder)
This reminds the VCU to shoot off it's own message later when it reboots.
@deperecated
Definition at line 716 of file uvfr_settings.c.
References START_OF_USER_FLASH, UV_ERROR, and UV_OK.
uvSettingsInit()
uv_status uvSettingsInit ()
this function does one thing, and one thing only, it checks if we have custom settings, then it attempts to get them. If it fails, then we revert to factory defaults.
Definition at line 334 of file uvfr_settings.c.
References __uvInitPanic(), current_vehicle_settings, handleIncomingLaptopMsg(), insertCANMessageHandler(), SETTING_BRANCH_SIZE, setupDefaultSettings(), START_OF_USER_FLASH, UV_ERROR, UV_OK, uvLoadSettingsFromFlash(), uvResetFlashToDefault(), uvSendCanMSG(), uvValidateFlashSettings(), and vcu_ack_msg.
Referenced by uvInit().
uvSettingsProgrammerTask()
void uvSettingsProgrammerTask (void * args)
This is a task that executes the functionality necessary for vehicle diagnostics.
This task is only active once the car has been placed in programming mode.
Definition at line 864 of file uvfr_settings.c.
References changeVehicleState(), uv_task_info::cmd_data, uv_CAN_msg::data, DATA_MISMATCH, data_size, DID_NOT_FINISH_PROGRAMMING, DISCARD_NEW_SETTINGS, DISCARD_NEW_SETTINGS_AND_EXIT, END_OF_SPECIFIC_PARAMS, FLASH_NOT_UNLOCKED, FLASH_SBLOCK_START, FORCE_RESTORE_FACTORY_DEFAULT, INVALID_SBLOCK, killSelf(), POST_CHECKSUM, PRE_CHECKSUM, ptask_handle, REQUEST_ALL_JOURNAL_ENTRIES, REQUEST_ALL_SETTINGS, REQUEST_JOURNAL_ENTRIES_BY_TIME, REQUEST_SPECIFIC_SETTING, SAVE_AND_APPLY_NEW_SETTINGS, SET_SPECIFIC_PARAM, settings_queue, uv_task_info::task_handle, UV_KILL_CMD, UV_OK, UV_READY, uvCreateTmpSettingsCopy(), uvResetFlashToDefault(), uvSaveSettingsToFlash(), uvSendCanMSG(), uvSendSpecificParam(), uvUpdateTmpSettings(), vcu_ack_failed_msg, and vcu_ack_msg.
Referenced by uvConfigSettingTask().
uvTransmitVehicleStatus()
uv_status uvTransmitVehicleStatus ()
Transmits the status of the vehicle, including errorcodes and similar.
Definition at line 141 of file uvfr_settings.c.
References UV_OK.
Referenced by handleIncomingLaptopMsg().
uvUpdateTmpSettings()
uv_status uvUpdateTmpSettings (uint8_t * tmp_settings, uint8_t memgroup, uint8_t m_offset, uint8_t size, uint8_t * data)
Updates a setting in a temporary SBlock by memory group and offset.
This indicates that you are attempting to set a setting that bridges the 128 byte `row` system the STM32F40xx uses to organise the flash memory. Attempting to write a parameter like this will result in a busfault.
Definition at line 411 of file uvfr_settings.c.
References UV_ERROR, and UV_OK.
Referenced by uvSettingsProgrammerTask().
uvValidateChecksums()
uv_status uvValidateChecksums (void * sblock)
Definition at line 495 of file uvfr_settings.c.
References UV_ERROR, UV_OK, and uvComputeSettingsChecksums().
uvValidateFlashSettings()
uv_status uvValidateFlashSettings ()
Function that looks into the flash memory of the VCU, and determines if a valid set of settings exists.
This checks various parameters to ensure that the settings are useable. The first thing it looks at is the very first word of the SBLOCK. If the first word is 0x42069420, then this is a real sblock.
The second thing it checks is the firmware version, which is stored immediately after the first word, and 16 bytes of padding. These 3 16 bit ints need to be correct, in order for it to proceed. This prevents settings made for incompatible firmware versions from being used.
Definition at line 810 of file uvfr_settings.c.
References MAGIC_NUMBER, START_OF_USER_FLASH, UV_ERROR, and UV_OK.
Referenced by uvSettingsInit().
Variable Documentation
_e_uvdata
PRIVILEGED_DATA uint8_t _e_uvdata
_s_uvdata
PRIVILEGED_DATA uint8_t _s_uvdata
child_task_active
bool child_task_active = false [static]
Definition at line 93 of file uvfr_settings.c.
Referenced by sendAllSettingsWorker().
child_task_handle
TaskHandle_t child_task_handle = NULL [static]
Definition at line 92 of file uvfr_settings.c.
Referenced by sendAllSettingsWorker().
current_vehicle_settings
uv_vehicle_settings* current_vehicle_settings = NULL
Definition at line 20 of file uvfr_settings.c.
Referenced by configureDaqSubTasks(), initDaqTask(), initDrivingLoop(), setupDefaultSettings(), uvInit(), uvLoadSettingsFromFlash(), uvSettingsInit(), and uvStartStateMachine().
default_bms_settings
bms_settings_t default_bms_settings
Definition at line 12 of file bms.c.
Referenced by setupDefaultSettings(), and uvResetFlashToDefault().
default_daq_settings
struct daq_loop_args default_daq_settings
Definition at line 30 of file daq.c.
Referenced by setupDefaultSettings(), and uvResetFlashToDefault().
default_datapoints
daq_datapoint default_datapoints[]
Definition at line 38 of file daq.c.
Referenced by setupDefaultSettings(), and uvResetFlashToDefault().
default_dl_settings
struct driving_loop_args default_dl_settings
Definition at line 27 of file driving_loop.c.
Referenced by setupDefaultSettings(), and uvResetFlashToDefault().
default_imd_settings
struct uv_imd_settings default_imd_settings
Definition at line 65 of file imd.c.
Referenced by setupDefaultSettings(), and uvResetFlashToDefault().
default_pdu_settings
uv19_pdu_settings default_pdu_settings
Definition at line 28 of file uvfr_settings.c.
Referenced by setupDefaultSettings(), and uvResetFlashToDefault().
default_vehicle
veh_gen_info default_vehicle
Initial value:
= {
    .wheel_size = 0xEEEEEEEE,
    .drive_ratio = 0xDDDDDDDD,
    .test1 = 0xCCCC,
    .test2 = 0xBBBB,
    .test3 = 0xAAAA,
    .test4 = 0x99,
    .test5 = 0x88,
    .test6 = 0x77777777
}
Definition at line 72 of file uvfr_settings.c.
Referenced by setupDefaultSettings(), and uvResetFlashToDefault().
is_laptop_connected
bool is_laptop_connected = false [static]
Definition at line 84 of file uvfr_settings.c.
Referenced by handleIncomingLaptopMsg().
last_contact_with_laptop
TickType_t last_contact_with_laptop = 0
Definition at line 85 of file uvfr_settings.c.
Referenced by handleIncomingLaptopMsg().
mc_default_settings
struct motor_controller_settings mc_default_settings
Definition at line 14 of file motor_controller.c.
Referenced by MC_Request_Data(), MC_Set_Param(), MC_Startup(), MotorControllerSpinTest(), Parse_Bamocar_Response(), setupDefaultSettings(), and uvResetFlashToDefault().
ptask_handle
TaskHandle_t ptask_handle = NULL [static]
Definition at line 90 of file uvfr_settings.c.
Referenced by uvSettingsProgrammerTask().
settings_queue
QueueHandle_t settings_queue = NULL [static]
Definition at line 88 of file uvfr_settings.c.
Referenced by handleIncomingLaptopMsg(), and uvSettingsProgrammerTask().
vcu_ack_failed_msg
const uv_CAN_msg vcu_ack_failed_msg
Initial value:
= {
    .flags = 0x00,
    .dlc = 1,
    .data = {0x11,0,0,0,0,0,0,0},
    .msg_id = VCU_TO_LAPTOP_ID
}
Pre-created message that indicates the VCU has failed to perform some requested action
Definition at line 111 of file uvfr_settings.c.
Referenced by handleIncomingLaptopMsg(), and uvSettingsProgrammerTask().
vcu_ack_msg
const uv_CAN_msg vcu_ack_msg
Initial value:
= {
    .flags = 0x00,
    .dlc = 1,
    .data = {0x10,0,0,0,0,0,0,0},
    .msg_id = VCU_TO_LAPTOP_ID
}
Pre-create message that is transmitted by the VCU upon successful completion of a settings change or diagnostic operation requested by a laptop
Definition at line 100 of file uvfr_settings.c.
Referenced by uvSettingsInit(), and uvSettingsProgrammerTask().